### ISSUE TITLE
文档中语病太多

### ISSUE THREAD

**Issue by kxxoling** [qiniu/js-sdk#100]
比如这两句，看了几遍没看懂：

```js
    // unique_names: true, // 默认 false，key为文件名。若开启该选项，SDK会为每个文件自动生成key（文件名）
    // save_key: true,   // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK在前端将不对key进行任何处理
```

重新整理下吧！

**Comment by netdxy** [comment]
您好, 是这样的，unique_names是plupload插件下面的一个参数，当值为true时会为每个上传的文件生成一个唯一的文件名，这个是plupload插件自动生成的，如果设置成false，七牛这边是会以上传的原始名进行命名的。
假设上传的文件本地文件名为abc.txt，上传后文件命名有以下几种形式。
1.上传的socpe为bucket的形式，unique_names参数设置为false，上传后文件的key是本地的文件名abc.txt
2.上传的scope为bucket的形式，unique_names参数设置为true，plupload插件会忽略本地文件名，而且这个命名也是没有规律的，上传后文件的key是plupload插件生成的，比如Yc7DZRS1m73o.txt。
3.上传的scope为bucket:key的形式，上传文件本地的名字需要和scope中的key是一致的，不然会报错key doesn‘t match with scope, 注意，这种形式是不能设置unique_names为true的，因为即使上传文件本地名字为abc.txt,但是plupload会给这个文件赋值另外一个文件名。
4.上传的scope为bucket，但是token中有设定saveKey，这种形式save_key是应该设置为true，并且上传的本地文件名也是需要和这个savekey文件名一致的。

**Comment by kxxoling** [comment]
@netdxy 七牛默认是不保存后缀名的吧？插件我会用，只是吐槽下文档写不清楚。

**Comment by codedogfish** [comment]
@kxxoling 谢谢你提出的意见，正在改进文档，有其他问题欢迎吐槽^_^

**Comment by codedogfish** [comment]
已经更新了文档

**Comment by kxxoling** [comment]
话说现在支持 import 了吗？有的话可以加到文档示例中吗？

**Comment by itcuihao** [comment]
确实是这样，现在我是这种上传流程，上传的scope为bucket:key的形式，然后返回前端 uptoken,key ，前端直接上传，有个疑问这个unique_names，save_key的设置是前端设置还是后端设置呢？现在的模式是前端设置的，可以上传成功。不过总被前端妹纸吐槽这样太麻烦了。可是我能怎么办！
