### ISSUE TITLE
Android使用分片上传功能报错。

### ISSUE THREAD

**Issue by icedfish** [qiniu/js-sdk#107]
试了下，官方的Sample也是会报错的。  试了同事的Android手机，问题同样存在。
只要大于4M的图片，上传就会出这个问题，测试了微信内webview和自带浏览器，都报同样错误。

截图如下：

![image](https://cloud.githubusercontent.com/assets/1222861/11719281/fb2bc066-9f94-11e5-8ecd-7aa3cb42bb89.png)

**Comment by longbai** [comment]
收到，我们跟进

**Comment by codedogfish** [comment]
@icedfish 
Hi, 安卓平台上一些 webview（例如：微信和 QQ 内置浏览器） 在 html5 runtime 下，分片上传时chunk取不到内容
- 这个问题暂时在 #104 中解决了，但是 html5 runtime 下会降级成非分片的上传形式
- 为了后续能够在这些问题的平台上支持分片上传， #106 正在开发支持 flash 分块上传
目前这些工作都还在 develop 分支上，稍后会合并到 master 并 release 新版本

**Comment by icedfish** [comment]
@codedogfish OK  我先用Dev分支吧，好像是能用的，不过Plupload的在IOS和Android上的客户端压缩功能问题太多，坑很大，建议文档中提示一下，要不掉进去很久都不容易出来。

PS: Dev分支上有好多Console.log  T_T  我先忍了把，反正这几个功能暂时都不会在老IE用。

**Comment by codedogfish** [comment]
@icedfish dev 分支上加的 logger 默认 log_level 不设置是不会输出日志的，主要是为了方便用户自查或向我们反馈问题时可以提供相应的调试信息，后面甚至会提供打印日志到页面的功能
欢迎提出更多意见(^_^)
