### ISSUE TITLE
请支持 https 上传

### ISSUE THREAD

**Issue by cloverstd** [qiniu/js-sdk#109]
https://up.qbox.me

**Comment by codedogfish** [comment]
@cloverstd 如果当前也面是 https 协议，会自动切换到 https://up.qbox.me

**Comment by cloverstd** [comment]
@codedogfish 我下载的  v1.0.9-beta 这个版本，我发现代码里没有兼容 https 自动切换

**Comment by codedogfish** [comment]
@cloverstd Sorry，那么回复你，v1.0.13 中已经支持，以下是源码中的片段

···
    var qiniuUploadUrl;
    if (window.location.protocol === 'https:') {
        qiniuUploadUrl = 'https://up.qbox.me';
    } else {
        qiniuUploadUrl = 'http://upload.qiniu.com';
    }
···
