### ISSUE TITLE
后缀名过滤

### ISSUE THREAD

**Issue by xcwen** [qiniu/js-sdk#117]
这么才能让用户只能上传特定后缀名的文件
如,只能上传 ".pdf" 文件，其他的提示错误．

**Comment by codedogfish** [comment]
@xcwen 
限制上传文件的类型： 这里又分为两种方法： 1).通过在token中设定mimeLimit字段限定上传文件的类型，示例 “image/*“表示只允许上传图片类型； “image/jpeg;image/png”表示只允许上传jpg和png类型的图片； “!application/json;text/plain”表示禁止上传json文本和纯文本。（注意最前面的感叹号） 2).通过plupload中设定filter参数直接在JS前端限定，如下

```
//可以使用该参数来限制上传文件的类型，大小等，该参数以对象的形式传入，它包括三个属性：
        filters : {
            max_file_size : '100mb',
            prevent_duplicates: true,
            //Specify what files to browse for
             mime_types: [
            {title : "flv files", extensions : "flv"} //限定flv后缀上传格式上传
            {title : "Video files", extensions : "flv,mpg,mpeg,avi,wmv,mov,asf,rm,rmvb,mkv,m4v,mp4"}, //限定flv,mpg,mpeg,avi,wmv,mov,asf,rm,rmvb,mkv,m4v,mp4后缀格式上传
            {title : "Image files", extensions : "jpg,gif,png"}, //限定jpg,gif,png后缀上传
            {title : "Zip files", extensions : "zip"} //限定zip后缀上传
             ]
        },
```

**Comment by xcwen** [comment]
有例子吗?! 不知道往哪写.

**Comment by mikeching** [comment]
就是写在配置上传的地方即可
`var uploader = Qiniu.uploader({
		runtimes: 'html5,flash,html4',
		browse_button: 'pickfiles',
		container: 'container',
		drop_element: 'container',
		max_file_size: '1000mb',
		mime_types: [
			{title: "mp4 files", extensions: "mp4"}
		],
		multi_selection: false,
`

**Comment by mikeching** [comment]
就是写在配置上传的地方即可
> var uploader = Qiniu.uploader({
		runtimes: 'html5,flash,html4',
		browse_button: 'pickfiles',
		container: 'container',
		drop_element: 'container',
		max_file_size: '1000mb',
		mime_types: [
			{title: "mp4 files", extensions: "mp4"}
		],
		multi_selection: false,
		flash_swf_url: 'js/plupload/Moxie.swf',
		dragdrop: true,
		chunk_size: '4mb',
		uptoken_url: $('#uptoken_url').val(),
		domain: $('#domain').val(),

**Comment by xcwen** [comment]
谢谢.
-- 不过 还要叫 filters
        var uploader = Qiniu.uploader({
		    runtimes: 'html5, flash, html4',
		    browse_button: btn_id , //choose files id
		    uptoken: token, 
		    domain: "http://"+domain_name,
		    max_file_size: '30mb',
		    dragdrop: true,
		    flash_swf_url: '/js/qiniu/plupload/Moxie.swf',
		    chunk_size: '4mb',
		    unique_names: false,
		    save_key: false,
		    auto_start: true,
            multi_selection: false,
            filters: {
                mime_types: [
                    {title: "", extensions: ext_file_list.join(",") }
                ]
            },
