### ISSUE TITLE
iphone 6s 微信内置浏览器,出现  文件验证失败,请稍后重试 

### ISSUE THREAD

**Issue by oldfeel** [qiniu/js-sdk#123]
网址:    http://chu.hi-www.com:8001/pw_detail?pw_id=23

![1](https://cloud.githubusercontent.com/assets/1726280/13485952/9684116e-e147-11e5-82a0-d851ed6a6e3a.jpg)

**Comment by codedogfish** [comment]
@oldfeel 你页面上面配置的文件类型过滤是 gif,jpg,png , 会不会因为用户上传的文件是其他后缀的图片文件（比如：jpeg）？

**Comment by oldfeel** [comment]
@codedogfish 谢谢回复.
不是图片的问题,用的 6s 截图,在 6 plus 上可以上传,但是在 6s 上不行.
