### ISSUE TITLE
适配最新版本的 plupload

### ISSUE THREAD

**Issue by codedogfish** [qiniu/js-sdk#131]
暂时只承诺同时适配 2.1.1(当前 js-sdk 依赖的版本) 和 2.1.8 (plupload 最新版本) 这两个版本。
相关的 Issue #64 #70

**Comment by xifat** [comment]
有适配plupload的demo 么？

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
