### ISSUE TITLE
安卓6.0，微信6.3.13 内置浏览器中点击上传按钮弹不出文件选择对话框

### ISSUE THREAD

**Issue by jiaoyanfei** [qiniu/js-sdk#133]
在：安卓6.0，微信6.3.13 内置浏览器中点击上传按钮弹不出文件选择对话框,但是安卓6.0，QQ 测试正常，chorme 测试正常！有没有解决方法！

**Comment by chelsh** [comment]
同样遇到了 怎么解决呢

**Comment by codedogfish** [comment]
@chelsh @jiaoyanfei 收到...已经在 Android 6.0 上 微信内置浏览器中 复现了问题，确认为 plupload 在 Android 6.0 的微信内置浏览器中 html5 模式不可用，可以用 html4 模式，稍后会在 js-sdk 中通过 ua 判断是否为 Android 6.0 的微信内置浏览器，然后自动降级 html4...

**Comment by chelsh** [comment]
@codedogfish  sdk更新后 通知下哈，我们这边急着用额

**Comment by youwater** [comment]
什么时候能解决哦？碰到同样的问题啊

**Comment by wshudong** [comment]
问题解决了吗，很坑啊，官方该声明下，找了很长时间才发现是这个问题。

**Comment by karboom** [comment]
HTML4的模式下好像会出现HTTP错误，
Resource interpreted as Document but transferred with MIME type application/json: "http://upload.qiniu.com/".

**Comment by karboom** [comment]
multi_selection 设置成 false 好像可以解决这个问题

**Comment by colorwin** [comment]
有人跟进这个问题吗?

**Comment by GuGaobai1994** [comment]
plupload和微信浏览器不兼容的问题，可以尝试一下 注释 main.js里的 filters 或者 multi_selection

**Comment by jcyrss** [comment]
这个问题，有人跟进吗？

**Comment by GuGaobai1994** [comment]
新版sdk应该没有这个问题了
![image](https://user-images.githubusercontent.com/20764006/27676843-22378bac-5ce2-11e7-9fa1-0ea994109be2.png)

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，新版本 SDK 已经不会出现类似的情况，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
