### ISSUE TITLE
chrome中点击上传按钮弹不出文件选择框

### ISSUE THREAD

**Issue by LucyLiuluxi** [qiniu/js-sdk#139]
chrome是当前最新版本，引用plupload是1.2.0版本，qiniu是1.0.14-beta

弹出文件选择框是偶尔性的，有时候可以有时候不行，而且在可行时，生成的隐藏上传input的位置不能和设置的上传button完全重合。

```
runtimes: 'html5,flash,html4',
            browse_button: 'ImgUpload',
            container: 'ImgUploadContainer',
            drop_element: 'ImgUploadContainer',
            max_file_size: '100mb',
            flash_swf_url: 'js/plupload/Moxie.swf',
            dragdrop: true,
            chunk_size: '4mb',
            uptoken_url: '/ajax/token',
            domain: QINIU_DOMAIN,
            get_new_uptoken: false,
            auto_start: true,
```

以上是uploader里的setting项

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，是否可以可以尝试使用最新的 3.x jssdk，看下复现的情况。
详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-953

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
