### ISSUE TITLE
可否提供一个设置上传host的option?

### ISSUE THREAD

**Issue by insub** [qiniu/js-sdk#140]
在初始化的时候可否提供一个option，指定上传的host？目前是http下硬编码了 http://upload.qiniu.com，因为有上传到海外服务器接口的需求。希望可以设置成 http://up.qiniug.com

感谢

**Comment by yuanping** [comment]
@insub 我也遇到同样问题，提了pull request: https://github.com/qiniu/js-sdk/pull/148
这样使用：
var qiniu = new QiniuJsSDK();
var uploader = qiniu.uploader({url: 'http://up.qiniug.com', ...});

**Comment by jemygraw** [comment]
sdk内部会自动根据空间所在的机房选择上传的域名，所以不用担心啦。
