### ISSUE TITLE
ios下微信崩溃

### ISSUE THREAD

**Issue by fangxiaowan** [qiniu/js-sdk#142]
在微信聊天中，点击二维码放大查看，然后长按识别二维码。这时打开内置浏览器使用上传控件，选择图片时，微信浏览器就会崩溃。

**Comment by forrest-mao** [comment]
您是否可以可以尝试使用最新的 3.x jssdk，看下是否还可以复现，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
如果可以复现的话，帮忙提供下二维码的截图，以及 iOS 版本、手机版本、微信版本信息，我们来做下复现，如果不方便可以[提交工单](https://support.qiniu.com/tickets/new/form?category=SDK%E4%BD%BF%E7%94%A8&space=%E5%AF%B9%E8%B1%A1%E5%AD%98%E5%82%A8)

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-954

**Comment by yinxulai** [comment]
长时间未得到有效答复，且该版本已不再维护，推荐更新到新版，该 issue 关闭。
