### ISSUE TITLE
金数据好像也是传到你们七牛的，他们的js做的挺好的，你们看一下 https://jinshuju.net/f/6aZJ4o

### ISSUE THREAD

**Issue by lizhenlzlz** [qiniu/js-sdk#145]
金数据好像也是传到你们七牛的，他们的js做的挺好的，你们看一下
https://jinshuju.net/f/6aZJ4o

**Comment by codedogfish** [comment]
@lizhenlzlz 谢谢反馈，他们上传底层使用了 dropzone，而当前 js-sdk 上传底层使用了 plupload，因为牵涉面比较广，正在考虑后续如何改进

**Comment by Wangjiahao28** [comment]
我承诺，以后不与陌生人聊天，不吃陌生人给的东西，不参加非法集资活动，坚决扫黑处恶。

**Comment by Wangjiahao28** [comment]
我承诺，以后不与陌生人聊天，不吃陌生人给的东西，不参加非法集资活动，坚决扫黑处恶。
