### ISSUE TITLE
七牛JS SDK不兼容微软最新的浏览器edge

### ISSUE THREAD

**Issue by aiyuchen** [qiniu/js-sdk#151]
七牛JS SDK在微软最新的浏览器edge上报错了
![图片描述](https://segmentfault.com/img/bVvkWK)

但是在Chrome上没有问题（同一个页面）
![图片描述](https://segmentfault.com/img/bVvkWU)

**Comment by codedogfish** [comment]
@aiyuchen 正在跟进

**Comment by yamingd** [comment]
这个问题是什么进度了？？碰到同样的问题，下周就要给客户演示项目了

**Comment by yamingd** [comment]
在IE-10上window.localStorage会报Access Denied错误，我就注释它。OK了
```
// if current browser is not support localStorage
// use cookie to make a polyfill
// if ( !window.localStorage ) {
    window.localStorage = {
        setItem: function (key, value) {
            createCookie(key, value, 30);
        },
        getItem: function (key) {
            return readCookie(key);
        },
        removeItem: function (key) {
            createCookie(key, '', -1);
        }
    };
// }

```

**Comment by forrest-mao** [comment]
目前最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，看下是否也能顺利解决这个问题，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-955

**Comment by yinxulai** [comment]
长时间未得到有效答复，且该版本已不再维护，遂关闭
