### ISSUE TITLE
求上传功能支持自定义header，项目通过header来控制版本

### ISSUE THREAD

**Issue by Dreampie** [qiniu/js-sdk#153]

**Comment by peaceful321** [comment]
可否明确说明一下你们的需求，不是很清楚你们的问题；

**Comment by forrest-mao** [comment]
建议版本控制通过版本号放入不同的文件名来做控制，因为相同的文件名就算 header 不同也可能因为 CDN 的缓存访问到旧的文件，类似这样的 URL 就行 https://example.com/_next/static/chunks/e0811733abc25a0b247a30ee693f80d3569d354f.9b8b4d525e4ef2aaf5ca.js

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-956

**Comment by yinxulai** [comment]
需求不清晰，进一步的信息没有得到有效补充，遂关闭。
