### ISSUE TITLE
runtimes: 'html4',  单独设置为html4，文件上传成功了，但是会触发ERROR

### ISSUE THREAD

**Issue by huixisheng** [qiniu/js-sdk#154]
以下为控制台调试信息：

![image](https://cloud.githubusercontent.com/assets/1518967/15171806/e0d300be-1783-11e6-93ae-aa546c424ac2.png)

**Comment by peaceful321** [comment]
建议按照我们提供的来设置，runtimes: 'html5,flash,html4',    //上传模式,依次退化

**Comment by peaceful321** [comment]
后续有问题，可以直接提交工单，联系技术支持，每天都有人值班的；
