### ISSUE TITLE
too many data to read, block capacity is 4194304 bytes, 0 byte(s) used

### ISSUE THREAD

**Issue by HFO4** [qiniu/js-sdk#155]
too many data to read, block capacity is 4194304 bytes, 0 byte(s) used是什么情况
听说是老版的问题。具体是出在哪个js文件上

**Comment by peaceful321** [comment]
可以通过浏览器调试窗口查看一下错误信息，定位到具体的js文件；

**Comment by forrest-mao** [comment]
是否可以尝试使用最新的 3.x jssdk，看下是否还可以复现，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-957
