### ISSUE TITLE
提供的npm包不支持webpack等模块化引用

### ISSUE THREAD

**Issue by xieyu33333** [qiniu/js-sdk#156]
提供的npm包不支持webpack等模块化引用, 既然提供了npm包，为什么不把相应的依赖也require进去，真是理解不能，就是加个umd头而已，有那么难么？

**Comment by baoziv587** [comment]
针对这个问题我提了PR。等他们合完就可以了

**Comment by moonshadow** [comment]
没那么简单的， `plupload` ,`mOxie` 这两货还是global的依赖 , 感觉还是用es6重构一波，然后webpack直接打包umd比较靠谱， 暂时还是cdn搞定吧。

**Comment by baoziv587** [comment]
plupload ,mOxie npm仓库有可用版本。 
我就加了个UMD头 已经在生产环境用了3个多月了，没发现有什么问题。
![image](https://cloud.githubusercontent.com/assets/7347513/19212764/e3c63700-8d8a-11e6-8517-0bbd68aeccc3.png)

**Comment by baoziv587** [comment]
另外七牛 对JS SDK好像没怎么维护了，要想等他们做等不了，自己FORK一个可行

**Comment by moonshadow** [comment]
好吧，看了一下cd-plupload这货的index.js 
```
window.mOxie = require('./moxie').mOxie;
window.plupload = plupload;
```
怪不得直接require就行

**Comment by lsxiao** [comment]
为什么要依赖plupload,mOxie这种不支持模块化的反人类的库？！！七牛官方的SDK水准太差了,还不如自己配合Fine Uploader重写，每次引入这个QiniuSDK都是一肚子火。

**Comment by jingzhou123** [comment]
webpack可以考虑用expose-loader把plupload暴露到全局，`require(expose?plupload!plupload!plupload/js/plupload.dev)`

**Comment by cocody** [comment]
暂时不要用 qiniuSDK, 直接用plupload2.2

**Comment by peaceful321** [comment]
js-sdk 依赖的第三方的 Plupload 插件和 Plupload 依赖的 flash 文件，都不支持模块化引用

**Comment by cag2050** [comment]
可以使用CommonJS模块化，例子：https://github.com/cag2050/qiniu_demo

**Comment by forrest-mao** [comment]
问题相关 #61 ，我们来补充下相关文档

**Comment by yinxulai** [comment]
推荐升级使用最新版本，该 `issue` 关闭。
