### ISSUE TITLE
怎么与angularJS结合呢

### ISSUE THREAD

**Issue by ArvinC** [qiniu/js-sdk#158]

**Comment by yzzhuo** [comment]
楼主解决了这个问题吗？同问...

**Comment by ArvinC** [comment]
var directiveModule = angular.module('app-directive', []);
directiveModule.directive('uploadImage', function () {
    return {
        require: 'ngModel',
        scope: {uploadId: '@'},
        link: function (scope, elem, attrs, _ngmodel) {
            var bucketDomain = "http://o71tin5mf.bkt.clouddn.com/"
            //监控
            var watch = scope.$watch('uploadId', function (newValue, oldValue, scope) {
                var Qiniu = new QiniuJsSDK();
                var icon = Qiniu.uploader({
                    runtimes: 'html5,flash,html4',      // 上传模式,依次退化
                    browse_button: scope.uploadId,
                    uptoken_url: "/upload/token",
                    get_new_uptoken: false,
                    unique_names: true,
                    domain: bucketDomain,
                    auto_start: true,
                    filters: {
                        max_file_size: "5mb",//文件大小
                        prevent_duplicates: false,
                        // Specify what files to browse for
                        mime_types: [
                            {title: "Image files", extensions: "jpg,gif,png,jpeg"}, // 限定jpg,gif,png后缀上传
                        ]
                    },
                    init: {
                        'BeforeUpload': function (up, files) {
                            //return checksize(files[0]);
                        },
                        'FileUploaded': function (up, file, info) {
                            var data = $.parseJSON(info);
                            _ngmodel.$setViewValue(data.key);
                            elem.find("img").attr("src", bucketDomain + data.key);
                            scope.$apply();
                        },
                        'Error': function (up, file, info) {
                            alert("图片格式不正确")
                        }
                    }
                });
                watch();
            });

            /**
             * 绑定数据更新时触发
             */
            _ngmodel.$render = function () {
                if (_ngmodel.$viewValue == null || typeof(_ngmodel.$viewValue) == "undefined"||_ngmodel.$viewValue == ""){
                    elem.find("img").attr("src", _ngmodel.$viewValue);
                    return;
                } else {
                    elem.find("img").attr("src", bucketDomain + _ngmodel.$viewValue);
                }
            };
        }
    }
});

**Comment by ArvinC** [comment]
var directiveModule = angular.module('app-directive', []);
directiveModule.directive('uploadImage', function () {
    return {
        require: 'ngModel',
        scope: {uploadId: '@'},
        link: function (scope, elem, attrs, _ngmodel) {
            var bucketDomain = "你的七牛域名"
             #//监控
            var watch = scope.$watch('uploadId', function (newValue, oldValue, scope) {
                var Qiniu = new QiniuJsSDK();
                var icon = Qiniu.uploader({
                    runtimes: 'html5,flash,html4',      // 上传模式,依次退化
                    browse_button: scope.uploadId,
                    uptoken_url: "/upload/token",
                    get_new_uptoken: false,
                    unique_names: true,
                    domain: bucketDomain,
                    auto_start: true,
                    filters: {
                        max_file_size: "5mb",//文件大小
                        prevent_duplicates: false,
                        // Specify what files to browse for
                        mime_types: [
                            {title: "Image files", extensions: "jpg,gif,png,jpeg"}, // 限定jpg,gif,png后缀上传
                        ]
                    },
                    init: {
                        'BeforeUpload': function (up, files) {
                            //return checksize(files[0]);
                        },
                        'FileUploaded': function (up, file, info) {
                            var data = $.parseJSON(info);
                            _ngmodel.$setViewValue(data.key);
                            elem.find("img").attr("src", bucketDomain + data.key);
                            scope.$apply();
                        },
                        'Error': function (up, file, info) {
                            alert("图片格式不正确")
                        }
                    }
                });
                watch();
            });

            /**
             * 绑定数据更新时触发
             */
            _ngmodel.$render = function () {
                if (_ngmodel.$viewValue == null || typeof(_ngmodel.$viewValue) == "undefined"||_ngmodel.$viewValue == ""){
                    elem.find("img").attr("src", _ngmodel.$viewValue);
                    return;
                } else {
                    elem.find("img").attr("src", bucketDomain + _ngmodel.$viewValue);
                }
            };
        }
    }
});

**Comment by ArvinC** [comment]
已解决了，加我qq2239087175 
------------------ Original ------------------

**Comment by peaceful321** [comment]
可否分享下，thks

**Comment by ArvinC** [comment]
directiveModule.directive('uploadImage', function () {    return {        require: 'ngModel',        scope: {uploadId: '@'},        link: function (scope, elem, attrs, _ngmodel) {            var bucketDomain = “你的七牛域名"            //监控            var watch = scope.$watch('uploadId', function (newValue, oldValue, scope) {                var Qiniu = new QiniuJsSDK();                var icon = Qiniu.uploader({                    runtimes: 'html5,flash,html4',      // 上传模式,依次退化                    browse_button: scope.uploadId,                    uptoken_url: “后台获取七牛凭证的URL",                    get_new_uptoken: false,                    unique_names: true,                    domain: bucketDomain,                    auto_start: true,                    filters: {                        max_file_size: "5mb",//文件大小                        prevent_duplicates: false,                        // Specify what files to browse for                        mime_types: [                            {title: "Image files", extensions: "jpg,gif,png,jpeg"}, // 限定jpg,gif,png后缀上传                        ]                    },                    init: {                        'BeforeUpload': function (up, files) {                            //return checksize(files[0]);                        },                        'FileUploaded': function (up, file, info) {                            var data = $.parseJSON(info);                            _ngmodel.$setViewValue(data.key);                            elem.find("img").attr("src", bucketDomain + data.key);                            scope.$apply();                        },                        'Error': function (up, file, info) {                            alert("图片格式不正确")                        }                    }                });                watch();            });                             原始邮件                             发件人: rui xu<notifications@github.com>收件人: qiniu/js-sdk<js-sdk@noreply.github.com>抄送: 曹佳伟<arvin@caojiawei.com>; Author<author@noreply.github.com>发送时间: 2016年12月13日(周二) 16:42主题: Re: [qiniu/js-sdk] 怎么与angularJS结合呢 (#158)可否分享下，thks

**Comment by peaceful321** [comment]
ok

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-958

**Comment by yinxulai** [comment]
“楼主” 已经解决、关闭
