### ISSUE TITLE
如何运行本案例的demo？

### ISSUE THREAD

**Issue by wendaosanshou** [qiniu/js-sdk#162]
看到readme里面说的是在项目根目录里运行`make install`然后在运行`make dev`

可是我运行的时候，会提示make不是内部或外部命令。

如果我使用`npm install`是可以安装package.json里面的包的，但是我不知道该怎么运行了。

**Comment by codedogfish** [comment]
@wendaosanshou 十分抱歉，这就修改文档

**Comment by peaceful321** [comment]
@wendaosanshou   后续可以直接提工单联系七牛的技术支持，那边回复比较及时一点；
