### ISSUE TITLE
Moxie.swf能提供吗，并且，当runtimes单纯的只是flash或html4都报错，所以，如果不是html5都无法上传吧

### ISSUE THREAD

**Issue by lizhenlzlz** [qiniu/js-sdk#164]
Moxie.swf能提供吗，并且，当runtimes单纯的只是flash或html4都报错，所以，如果不是html5都无法上传吧

runtimes: 'html5,flash,html4',
        browse_button: 'pickfiles',
        container: 'container',
        drop_element: 'container',
        max_file_size: '100mb',
        flash_swf_url: 'js/plupload/Moxie.swf',

**Comment by codedogfish** [comment]
- 
- 使用 Bower 安装

    Bower 是一个客户端技术的软件包管理器，它可用于搜索、安装和卸载如 JavaScript、HTML、CSS 之类的网络资源。如果需要更详细的关于 Bower 的使用说明，您可以访问[ Bower 官方网站](http://bower.io/)。
    
    通过 Bower 安装会将 JS-SDK 依赖的 plupload 也一起安装在 `bower_components` 中：

    ```
    bower install qiniu
    ```

    执行之后，JS-SDK 和 plupload 分别在以下位置

    ```
    bower_components
    ├── plupload
    │   └── js
    │       ├── moxie.js
    │       ├── moxie.min.js
    │       ├── plupload.dev.js
    │       ├── plupload.full.min.js
    │       └── plupload.min.js
    └── qiniu
        └── dist
            ├── qiniu.js
            ├── qiniu.min.js
            └── qiniu.min.map
    ```
