### ISSUE TITLE
qq浏览器不能使用？谷歌模拟器模拟的安卓系统也不可用？

### ISSUE THREAD

**Issue by AidanWang** [qiniu/js-sdk#166]
如题

**Comment by AidanWang** [comment]
手机qq浏览器

**Comment by peaceful321** [comment]
当前使用的是自定义域名还是测试域名？

**Comment by forrest-mao** [comment]
是否可以提供更详细的信息，另外也以尝试使用最新的 3.x jssdk，该版本不依赖 plupload 第三方组件，兼容性更强一些，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

**Comment by yinxulai** [comment]
该 PR 长时间未得到有效的信息反馈，且期间 SDK 经历了多次大版本迭代，所以关闭该 issue. 推荐更新最新版本
