### ISSUE TITLE
uptoken_func 不起作用

### ISSUE THREAD

**Issue by stiekel** [qiniu/js-sdk#168]
由于需要根据不同文件，设置不同的 `uptoken` ，所以使用了 `uptoken_func` 参数，但实际上发现，上传的时候，根本不会去通过执行这个方法来获取对应的 `uptoken` 。请问，是否有其它的解决办法。

目前，尝试了如下方法，均失败：
- 使用 `uptoken_func` 参数
- 在 `FilesAdded` 中，请求服务器获取 `uptoken` ，然后使用 `setOption` 的方式设置 `uptoken`
- 在 `BeforeUpload` 中，通过 `setOption` 设置 `uptoken`

**Comment by codedogfish** [comment]
@stiekel 能不能把你的 options 设置贴一下？

**Comment by stiekel** [comment]
当时没有解决，所以已经弃用本模块。

**Comment by shenqihui** [comment]
+ 1

**Comment by shenqihui** [comment]
npm install 的版本，找不到任何 uptoken_func 相关的字眼。估计发包错误了。

**Comment by stiekel** [comment]
@shenqihui 最后我用了 https://www.npmjs.com/package/dropzone ，还不错，你可以考虑一下。

**Comment by peaceful321** [comment]
正常 js  sdk 获取token 有三种方式，都是可以的；
这样的问题，可以通过提交工单，直接找七牛的技术支持；

**Comment by stiekel** [comment]
@peaceful321 现在的我不知道，但发这个 ticket 的时候，这个包的确是有问题的。
如果发布在 github 上的代码有问题，不能够通过 issue 来解决，还需要发工单来寻求支持，这难道不是增加中间步骤，白白的降低效率吗？

**Comment by FrancisKong** [comment]
是 npm 上的包有问题，最新的版本 1.0.14-beta 里面的 getUpToken 是这样实现的

```js
// if op.uptoken has no value
//      get token from 'uptoken_url'
// else
//      set token to be op.uptoken
var getUpToken = function() {
  if (!op.uptoken) {
    // TODO: use mOxie
    var ajax = that.createAjax();
    ajax.open('GET', that.uptoken_url, true);
    ajax.setRequestHeader("If-Modified-Since", "0");
    ajax.onreadystatechange = function() {
      if (ajax.readyState === 4 && ajax.status === 200) {
        var res = that.parseJSON(ajax.responseText);
        that.token = res.uptoken;
      }
    };
    ajax.send();
  } else {
    that.token = op.uptoken;
  }
};
```

看了下 Github 上的代码是正确的，不是很明白为什么两边的代码不一致。
已经放弃使用这个 SDK 了，坑太多了

**Comment by forrest-mao** [comment]
目前已经将 npm 和 github 源码两边的代码做了重构和同步。
