### ISSUE TITLE
IE上传的问题

### ISSUE THREAD

**Issue by David-Pan** [qiniu/js-sdk#169]
根据你们的DEMO进行了修改，然后发现在非IE上上传是没问题的，在IE上上传的时候会弹出一个对话框“您是要打开还是保存来自upload.qiniu.com的oe315e8e？”，我点击保存打开这个文件，发现里面就只有一个key和hash，而且一直上传不了，请问这是什么原因？是否我改写的配置文件出现了问题？
`var key;
var token;
$.getScript("http://xxx.com/getToken");

function getToken(j) {
    alert(JSON.stringify(j));
    key = j.key;
    token = j.token;
    $(function() {
        var uploader = Qiniu.uploader({
            runtimes: 'html5,flash,html4',
            browse_button: 'pickfiles',
            container: 'container',
            drop_element: 'container',
            filters: {
                max_file_size: '100mb',
                prevent_duplicates: true,
                // Specify what files to browse for
                mime_types: [
                    {
                        title: "Video files",
                        extensions: "flv,mpg,mpeg,avi,wmv,mov,asf,rm,rmvb,mkv,m4v,mp4"
                    }, // 限定flv,mpg,mpeg,avi,wmv,mov,asf,rm,rmvb,mkv,m4v,mp4后缀格式上传
                    {
                        title: "Image files",
                        extensions: "jpg,gif,png"
                    }, // 限定jpg,gif,png后缀上传
                    {
                        title: "Zip files",
                        extensions: "zip"
                    } // 限定zip后缀上传
                ]
            },
            flash_swf_url: 'bower_components/plupload/js/Moxie.swf',
            dragdrop: true,
            chunk_size: '4mb',
            multi_selection: !(mOxie.Env.OS.toLowerCase() === "ios"),
            uptoken: token,
            domain: "http://o84wuqkc8.bkt.clouddn.com/",
            get_new_uptoken: false,
            auto_start: true,
            log_level: 5,
            init: {
                'FilesAdded': function(up, files) {
                    alert(JSON.stringify(files))
                },
                'BeforeUpload': function(up, file) {
                    $("#proccess").show();
                },
                'UploadProgress': function(up, file) {},
                'UploadComplete': function() {},
                'FileUploaded': function(up, file, info) {
                    $("#proccess").hide();
                    // 查看简单反馈
                    //              var domain = up.getOption('domain');
                    //              var res = JSON.stringify(info);
                    var sourceLink = "http://o84wuqkc8.bkt.clouddn.com/" + key; //获取上传成功后的文件的Url
                    alert(sourceLink)
                    $("#img-preview").attr("src", sourceLink);
                },
                'Error': function(up, err, errTip) {
                        alert(JSON.stringify(err))
                    }
                    //          ,
                    //          'Key': function(up, file) {
                    //              //                   var key = "";
                    //              // do something with key
                    //              return key;
                    //          }
            }
        })

```
});
```

}`

`---------------------------
## 确定   

`

**Comment by peaceful321** [comment]
使用我们的在线demo 会有这样的问题么
http://jssdk.demo.qiniu.io/

**Comment by yinxulai** [comment]
长时间未得到有效答复，且该版本已不再维护，推荐更新到新版，该 issue 关闭。
