### ISSUE TITLE
demo太坑爹了

### ISSUE THREAD

**Issue by rtsbtx** [qiniu/js-sdk#171]
uptoken_url 设置了压根没用，一直报400，看后台log压根就没去调这个接口，在浪费了我5个小时后，尝试修改js，手动添加了uptoken后，一次跑通！osx+chrome

**Comment by codedogfish** [comment]
@rtsbtx uptoken_url 怎么设置的？chrome 里面具体的报错信息是什么？

**Comment by liveangela** [comment]
@rtsbtx 我使用的也是uptoken_url参数，能够发送成功，也能接受到token。我使用的是plupload2.1.1

**Comment by peaceful321** [comment]
plupload 建议使用 2.1.1  到 2.1.9 ，从2.2.0 开始， plupload js 中已经将mOxie 这个变量去掉了，会报错的；
