### ISSUE TITLE
文件名的问题

### ISSUE THREAD

**Issue by rtsbtx** [qiniu/js-sdk#172]
生成uptoken的时候没有指定key，js中也没有指定key，但是在七牛官网空间查看文件的名字，却是以本地文件名来命名，就是文件名没有变，七牛文档写着是会用hash来命名。

“客户端已指定Key，以Key命名。
客户端未指定Key，上传策略中设置了saveKey，以saveKey的格式命名。
客户端未指定Key，上传策略中未设置saveKey，以文件hash(etag)命名。”

**Comment by rtsbtx** [comment]
unique_names: false, // 默认 false，key为文件名。若开启该选项，SDK为自动生成上传成功后的key（文件名）。

晕死，这sdk强制设置了key。如果设置为true，又变成sdk生成文件名，就是无论如何都用不了hash(etag)来做文件名

**Comment by cuibty** [comment]
+1 这个怎么弄

**Comment by longbai** [comment]
我们看下

**Comment by androidjdx** [comment]
这个问题解决了吗？

**Comment by forrest-mao** [comment]
已经解决，详细问题可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript#faq，且 3.x 版本 SDK 直接通过 `const observable = qiniu.upload(file, key, token, putExtra, config)` 来指定 key 为空或者具体字符串即可，没有其他的开关
