### ISSUE TITLE
北方地区上传报错，incorrect zone, please use up-z1.qiniu.com

### ISSUE THREAD

**Issue by colyll** [qiniu/js-sdk#176]
这个需要官方维护下吧。

**Comment by xfight0** [comment]
我也出现了这个错误, 
SDK代码里面写死了
```
    var qiniuUploadUrls = [
        "http://upload.qiniu.com",
        "http://up.qiniu.com"
    ];

    var qiniuUpHosts = {
       "http": [
           "http://upload.qiniu.com",
           "http://up.qiniu.com"
       ],
       "https": [
           "https://up.qbox.me"
       ]
    };
```

**Comment by huangjunwen** [comment]
我也一样遇到这个问题，原先在测试环境下的七牛账号没问题，新申请了个正式环境的就报 “incorrect region, please use up-z2.qiniu.com”， 而且sdk里面没有任何参数可以改。。。难道要自己hardcode进去吗？？？

**Comment by peaceful321** [comment]
华东的存储空间 使用  up-z0.qiniu.com   或者  up.qiniu.com
华北的存储空间 使用  up-z1.qiniu.com 
华南的存储空间 使用  up-z2.qiniu.com 

在最新的七牛 sdk 中  有提供Configuration 这个对象， 该对象 可以配置 Zone 对象，具体可以先配置最新的sdk试一下；

**Comment by huangjunwen** [comment]
@peaceful321 请问是在 master 分支上吗？

**Comment by peaceful321** [comment]
js sdk  可以设置 uptoken_url 这个属性来获取token试一下；

会自动判断上传空间所在区域的；

**Comment by neevek** [comment]
报了错，官方连个回复都没有吗？

**Comment by lixingdecai** [comment]
incorrect region, please use up-z2.qiniu.com 一样这个错误，什么原因？？

**Comment by TTLty** [comment]
我的七牛后台配置是华南地区(长沙)，token也获取成功了，还是报这个incorrect region
please use up-z2.qiniu.com的错误，在config.php配置了http://up-z2.qiniu.com,还是报错

**Comment by wukong509** [comment]
直接修改qiniu.js中的qiniuUploadUrls为
`var qiniuUploadUrls = [
        "http://up-z2.qiniu.com",
        "http://up.qiniu.com"
    ];`

**Comment by benx203** [comment]
python sdk可以这么设置：
from qiniu.config import *
set_default(default_zone=Zone('up-z1.qiniu.com', 'upload-z1.qiniu.com'))
js sdk应该有类似的设置

**Comment by Huang-Libo** [comment]
@benx203  非常棒, Python 就是这么改的
`from qiniu.config import *
set_default(default_zone=Zone('up-z1.qiniu.com', 'upload-z1.qiniu.com'))`

**Comment by GuGaobai1994** [comment]
只需要修改下qiniu.js里面指定的上传的域名就可以了
https://github.com/qiniu/js-sdk/blob/master/src/qiniu.js#L158

 var qiniuUploadUrls = [
        "http://upload-z1.qiniu.com",
        "http://up-z1.qiniu.com"
    ];

**Comment by Huang-Libo** [comment]
我觉得这些sdk应该把上传域名暴露到配置文件中, 或者根据ip的地理位置自动选择. 总改源码不是个好办法.

**Comment by GuGaobai1994** [comment]
现在是可以通过https://github.com/qiniu/js-sdk/blob/master/src/qiniu.js#L627
来自动获取上传地址的，只是要多一次请求

**Comment by chengkj99** [comment]
ZoneHuabei

```
SrcUpHosts: []string{
	"up-z1.qiniup.com",
},
```
Replace With
```
SrcUpHosts: []string{
	"up-z0.qiniup.com",
},
```

**Comment by zhangdxchn** [comment]
Java 遇到同样的问题，官方文档https://developer.qiniu.com/kodo/sdk/1239/java#upload-config,
Configuration cfg = new Configuration(Region.region0());  指定Region的取值跟开通的区域一致就可以了。

**Comment by forrest-mao** [comment]
目前 3.x 版本 SDK 中，config.region 可以控制具体的 region，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript，且如果 config.region 设置为空，会自动根据 token 指定 bucket 所在的区域来选择域名进行上传
