### ISSUE TITLE
关于如何设置multi_selection让文件对话框只能选一个文件的疑问

### ISSUE THREAD

**Issue by pengfu** [qiniu/js-sdk#177]
1. 设置每次只能选择一个文件

通过 plupload 插件中的 multi_selection 参数控制，如下

// 设置一次只能选择一个文件
multi_selection: false,

只能在plupload插件的源码中设置吗？七牛提供的组件有没有提供接口如何设置？

**Comment by liveangela** [comment]
@pengfu 搭车同问

qiniu说明文档告诉我们，multi_selection和filters都是通过对plupload配置而实现的，但至于具体代码应放在何处，qiniu并没有明确说明。

那么，根据[plupload官方Git文档的示例](http://jsfiddle.net/gh/get/jquery/1.9.1/jayarjo/plupload-demos/tree/master/2.x/core/bundled)，是在定义时进行配置，大致实现如下：

<pre>
<code>
var uploader = new plupload.Uploader({
    ...  // browse_button等其他配置

    filters : [
	{title : "Image files", extensions : "jpg,gif,png"},
	{title : "Zip files", extensions : "zip"}
    ],

    multi_selection: false
});

uploader.init();
</code>
</pre>

这里，配置的时机是在pluploader初始化之前，
但是被Qiniu封装后，使用Qiniu.uploader({ ... })配置时已经完成了pluploader的初始化工作（uptoken已经请求到了），之后我再尝试使用pluploader的setOption()方法去配置，也没有成功

还肯定作者帮忙，明示一下

另外issue中的#97号问题也可能属于此类问题

**Comment by peaceful321** [comment]
@pengfu  可以提工单 找七牛的技术支持，那边可以及时回复的；

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-959

**Comment by yinxulai** [comment]
长时间未得到有效答复，且该版本已不再维护，推荐更新到新版，该 issue 关闭。
