### ISSUE TITLE
npm 安装，install的代码与github仓库不一致

### ISSUE THREAD

**Issue by AllenZeng** [qiniu/js-sdk#179]
今天在用npm安装时候，查看了node_module里面的安装代码，发现与github仓库里面的代码不一致，不知是因为没有把最新的代码发不到npm上吗？

**Comment by ExinCoda** [comment]
+1

npm显示的版本是1.0.14beta，但是没有1.0.14beta添加的uptoken_func，发布有问题呀
还请修复下

**Comment by ExinCoda** [comment]
临时弄了个镜像包 `npm install tbs-qiniu-js`，代码是 a49e839429f06334839af11b0b22de42673b0eae 的，算是能用了

麻烦官方更新npm后@我一下，我去删除这个镜像

**Comment by peaceful321** [comment]
当前 js sdk 最新版本是1.0.17.2，
github上的地址可以看一下， https://github.com/qiniu/js-sdk/tree/v1.0.17.2

**Comment by peaceful321** [comment]
后续有问题，可以直接提工单 联系技术支持， 那边回复及时一点；

**Comment by ExinCoda** [comment]
然而npm上的还是没有更新，失望，whatever

**Comment by peaceful321** [comment]
现在下最新的 js  sdk 使用有问题么？

**Comment by ExinCoda** [comment]
有问题，下载后package.json里版本号是1.0.14，它既不是最新版，也不是真正的1.0.14版，因为1.0.14版新添加了uptoken_func功能并不在里面（这段话我明明打在了2楼了啊

**Comment by luoyeshu0507** [comment]
npm 已经是最新版本 后面会每次发版同步更新
