### ISSUE TITLE
{code: -500, message: "Init error."} 初始化的时候出错 什么原因？

### ISSUE THREAD

**Issue by hirodeng** [qiniu/js-sdk#183]
![snip20160930_57](https://cloud.githubusercontent.com/assets/9270665/18989915/422b938a-8741-11e6-9bd9-58cb829be173.png)

**Comment by peaceful321** [comment]
这个建议提个工单，找技术支持，然后，将 初始化的 js 代码 发一下；

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
