### ISSUE TITLE
支持获取空间的资源列表嘛？

### ISSUE THREAD

**Issue by yaojaa** [qiniu/js-sdk#184]
支持获取空间的资源列表嘛？急需啊。。js搞不定吗？

**Comment by peaceful321** [comment]
这个是支持的，通过前缀进行获取；在java sdk 中都有提供 listFiles 方法的；
你那边使用的是什么开发语言

**Comment by forrest-mao** [comment]
jssdk 目前不支持获取资源列表，获取资源列表的[ list 接口](https://developer.qiniu.com/kodo/api/1284/list) 需要服务端语言来调用，可以尝试使用 nodejs 中的列取资源的方法来实现：https://developer.qiniu.com/kodo/sdk/1289/nodejs#rs-list
