### ISSUE TITLE
分块上传js报错

### ISSUE THREAD

**Issue by yujingwyh** [qiniu/js-sdk#188]
直接设置uptoken值并且分块上传时js报错
访问that.tokenInfo的属性isExpired出错
因为that.tokenInfo是undefined

`var getUptoken = function(file) {
            if (!that.token || that.tokenInfo.isExpired()) {
                return getNewUpToken(file);
            } else {
                return that.token;
            }
        };`
        };

**Comment by BubbleLeaf** [comment]
应该是使用了uptoken或者uptoken_func提供 uptoken的原因，因为这两种是没有提供token有效时间的   如果uptoken_url的方式 应该就可以了

**Comment by BubbleLeaf** [comment]
`        var getUptoken = function(file) {
            if (!that.token || (that.tokenInfo && that.tokenInfo.isExpired())) {
                return getNewUpToken(file);
            } else {
                return that.token;
            }
        };`

我暂时将代码 调整为这个样子 ok啦  将就着用吧

**Comment by huangyunbo** [comment]
@yujingwyh 为什么关掉这个错误？
这个错误一直存在，我希望官方修复它。

它判断是html5或则flash的时候，并且需要用到分块上传的时候，就会调用getUptoken(file)。

这个错误其实让人很茫然，帮助文档里强烈建议写token_url，但是只写token又没问题。这样就是因为我们只写token触发的。

**Comment by dongyado** [comment]
这个bug 应该要解决的 我也遇到这个问题了

**Comment by skyshuilan** [comment]
这个问题也遇到了，上面@BubbleLeaf 同学的解决方法很好，不过可以改动chunk_size的大小，比如设置10M,
![Uploading image.png…]()

**Comment by lliudb** [comment]
这个问题还没解决么？简直了，各种报错

**Comment by Jsmond2016** [comment]
我是[参照文档](https://github.com/qiniu/js-sdk/tree/1.x)写的代码
仔细看一下报错信息，我的是这样
![](https://i.loli.net/2018/03/07/5a9fe3a55091d.png)
然后修改我自己问题解决bug实现多个实例上传 
希望对大家有所帮助
