### ISSUE TITLE
app_secret直接暴露？

### ISSUE THREAD

**Issue by justplus** [qiniu/js-sdk#192]
我看SDK初始化的时候是需要appKey和appSecret的，按照常理appSecret是不应该暴露的，如何处理这个问题？

**Comment by luoyeshu0507** [comment]
@justplus 
sdk初始化的时候需要的是uptoken，uptoken是服务器端根据appKey和appSecret 算出来的，客户端只需要这个算出来的uptoken来保证上传安全，并不会暴露到客户端。详情参考：[上传凭证(uptoken)](http://developer.qiniu.com/article/developer/security/upload-token.html)

**Comment by peaceful321** [comment]
@justplus   后续有关于js sdk 的问题，可以通过提交工单，反馈给技术支持；
那边回复比较及时；

**Comment by forrest-mao** [comment]
文档中描述的密钥对的初始化是服务端使用 nodejs 做演示是做的设置，实际客户端引用服务端前算好的 token 即可，不对终端用户暴露
