### ISSUE TITLE
Please mention how to extract the file src in the document

### ISSUE THREAD

**Issue by aleen42** [qiniu/js-sdk#193]
In most cases when we handle something before upload files to the server, we need to get the original File object. However, with reading the document entirely, I have not found the solution until I read deeper into each object initialized by this sdk.

Actually, I hope that you can write it on the document for how to handle before uploading:
1. Set the variable `auto_start` as `false`
2. Handle in the event `FilesAdded`
3. Get the original File object by calling `up.files[0].getSource().getSource();`
4. Check whether the file is what you want. If not actually we want, terminate the uploading process by not calling `uploader.start();`. If it is, then call it. (Notice that: if it's illegal, we should remove the file from uploader by calling `up.removeFile(up.files[0].id);`

**Comment by forrest-mao** [comment]
Only visible to Qiniu staff: https://jira.qiniu.io/browse/TS-964

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
