### ISSUE TITLE
如果重名了会怎么样

### ISSUE THREAD

**Issue by note4** [qiniu/js-sdk#194]
好像上传后没有处理文件名，如果相同的文件名上传会怎么样？

**Comment by guoxiangwen** [comment]
我们都是自己修改的名字，名字有冲突 但是不是所有的 我也觉得很奇怪

**Comment by luoyeshu0507** [comment]
@note4  使用js-sdk上传，名字重复则保留服务端的文件，上传失败，建议上传前对文件名进行处理，如加入时间戳等。处理办法：在实例化上传对象的时候，在相应的回调函数中对要上传的文件进行重命名。可进行处理的回调函数有：init. FilesAdded、init. BeforeUpload、init.Key。建议使用init.Key对文件名进行处理。

**Comment by peaceful321** [comment]
相同的文件名，如果没有指定上传策略中的scope为 <bucket>:<key> 的格式，会报错，提示文件已存在；
如果指定了，则会进行覆盖上传；
可以看下七牛的上传策略说明文档：
http://developer.qiniu.com/article/developer/security/put-policy.html
