### ISSUE TITLE
分块上传js报错， tokenInfo Cannot read property isExpired of undefined

### ISSUE THREAD

**Issue by dongyado** [qiniu/js-sdk#195]
qiniu.js:663 Uncaught TypeError: Cannot read property 'isExpired' of undefined

由下面的语句引起的
var getUptoken = function(file) { if (!that.token || that.tokenInfo.isExpired()) { return getNewUpToken(file); } else { return that.token; } };
};

当参数设置成uptoken_func时会出现这个问题，使用uptoken_url没有这个问题，我觉得还是需要解决的

**Comment by xunyi** [comment]
我也遇到这个问题了，因为应用在获取token的时候需要传递一些query参数所以无法使用uptoken_url只能使用uptoken_func，最后只能先注销掉chunk_size参数使得不分块上传来避免这个问题，期待能解决一下这个问题

**Comment by peaceful321** [comment]
可以爬一下我们的js 在线demo ，看一下，分片上传也是支持的；
http://developer.qiniu.com/code/v6/sdk/javascript.html

**Comment by forrest-mao** [comment]
目前 3.x 版本的 jssdk 只需要在 qiniu.upload 的 token 参数中传入上传 token 即可，任何方式传入 token 字符串即可上传。
