### ISSUE TITLE
上传超出限制的大小提示有问题

### ISSUE THREAD

**Issue by yujingwyh** [qiniu/js-sdk#196]
现在提示-浏览器最大可上传undefined。更大文件请使用命令行工具。
源码：
var max_file_size = up.getOption && up.getOption('max_file_size');
 max_file_size = max_file_size || (up.settings && up.settings.max_file_size);
 errTip = '浏览器最大可上传' + max_file_size + '。更大文件请使用命令行工具。';

其中max_file_size是在filters对象下的
filters : {
    max_file_size : '100mb',
    prevent_duplicates: true,

**Comment by peaceful321** [comment]
你这修改的地方不对；

**Comment by peaceful321** [comment]
如图：

![image](https://cloud.githubusercontent.com/assets/9206603/21136489/d0dc0ad4-c160-11e6-8017-6a1240394972.png)
