### ISSUE TITLE
plupload 已经升级到 2.2 了,qiniujSDK还是用2.1

### ISSUE THREAD

**Issue by lizy0329** [qiniu/js-sdk#197]
plupload  2.2 解决了 使用 npm 包,出现 'mOxie is not defined' 的问题

**Comment by jiyinyiyong** [comment]
demo 当中 http://jssdk.demo.qiniu.io/bower_components/plupload/js/moxie.js 没有版本号, 跟我从 npm 直接拉的代码并不一样. 我还遇到 `mOxie.Env` undefined 的问题.

**Comment by 1c7** [comment]
`mOxie is not defined`
我也碰到了一样的问题

**Comment by peaceful321** [comment]
因为plupload js在2.2.0开始，就去掉了mOxie 这个变量；
所以建议使用 plupload js 的版本是在 2.1.1   到   2.1.9

**Comment by 1c7** [comment]
@peaceful321 是否有可能让 js-sdk 能用上最新的 plupload 3.0？
近期内有这样升级的打算吗。

**Comment by peaceful321** [comment]
这个暂时好像没有，年底很多事情排不过来；

**Comment by Catouse** [comment]
只有自己动手了，在导入 `plupload.js` 之后且在 `qiniu.js` 之前加上如下代码：
```javascript
if(!window.mOxie) window.mOxie = {
        Env: Moxie.core.utils.Env,
        XMLHttpRequest: Moxie.xhr.XMLHttpRequest
};
```

**Comment by peaceful321** [comment]
可以试一下；有问题，最好可以直接通过工单联系七牛技术支持；

**Comment by 1c7** [comment]
好的，感谢各位。@peaceful321 @Catouse

**Comment by peaceful321** [comment]
没关系，后续有问题，可以再联系我们；

最好通过工单，联系七牛的技术支持，可以很快的获取到回复；

**Comment by 1c7** [comment]
@peaceful321  好，明白~

**Comment by peaceful321** [comment]
ok

**Comment by HappyAdu** [comment]
强烈建议升级，现在Plupload 2.2.1 版本找半天找不到。

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
