### ISSUE TITLE
Vue里，npm install qiniu-js之后不能直接引用吗？import ..."qiniu-js"就报错了

### ISSUE THREAD

**Issue by hopkinson** [qiniu/js-sdk#201]
![image](https://cloud.githubusercontent.com/assets/13248613/21173346/434a3724-c212-11e6-9089-f7b6e935c3a2.png)
npm install qiniu-js 之后运行报错？不能这么引用吗？在vue工程里

**Comment by peaceful321** [comment]
建议先尝试其他方式导入 七牛的js sdk 试一下；
给您带来不便，敬请谅解！

**Comment by peaceful321** [comment]
建议先尝试其他方式导入 七牛的js sdk 试一下；

**Comment by peaceful321** [comment]
最好是能够找七牛的技术支持，通过提交工单，那边回复快一点；

**Comment by luoyeshu0507** [comment]
@hopkinson   js-sdk 因为其依赖的第三方的 Plupload 插件和 Plupload 依赖的 flash 文件，都不支持模块化引用，单独引用 js-sdk 并不能实现上传功能，为了防止误导用户，暂未支持 js-sdk 的模块化引用功能。Vue 的话建议使用 formdata 的方式结合七牛表单上传方式进行上传，没几行代码。。

**Comment by luoyeshu0507** [comment]
@hopkinson 
http://jssdk.demo.qiniu.io/formdata  
formdata upload demo 用的jQuery
vue结合formdata更方便 需要的话可以联系我给你个vue的Demo

**Comment by hopkinson** [comment]
@luoyeshu0507 能请你给我一个vue的demo吗 我想看看 谢谢

**Comment by luoyeshu0507** [comment]
@hopkinson    
hi, 邮件联系下我呗，lizhiwei@qiniu.com

**Comment by cag2050** [comment]
可以使用CommonJS模块化，例子：https://github.com/cag2050/qiniu_demo

**Comment by webzhangbing** [comment]
@luoyeshu0507  你好， 能给我一个vue的demo 吗？   我给你发了一个邮件 。   如果有空的话     请回复一下。谢谢

**Comment by maokeyang** [comment]
@luoyeshu0507  方便给一个vue的demo给我们 邮箱 1195919021@qq.com

**Comment by zetianul** [comment]
这是我在vue中解决的方案，具体忘了是从哪个issue看到的了，就是用Promise确保拿到所有的依赖才会继续初始化plupload，token是后端的接口
```
Promise.all([
                    import ('plupload/js/moxie.min'),
                    import ('plupload/js/plupload.full.min'),
                    import ('qiniu-js')
                ]).then(([moxie, plupload]) => {
                    window.moxie = moxie
                    window.plupload = plupload

                    var uploader = Qiniu.uploader({
                            //uploader配置
                        })
```

**Comment by harlan1012** [comment]
请问这个问题解决了吗？我现在也遇到这个问题了

**Comment by winddies** [comment]
@harlan1012 可以用 2.0 版本，支持模块化引入

**Comment by forrest-mao** [comment]
> 请问这个问题解决了吗？我现在也遇到这个问题了

目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
