### ISSUE TITLE
当x_vars参数值为数字的时候 分块上传js报错，如果为字符串则不会

### ISSUE THREAD

**Issue by vasth** [qiniu/js-sdk#202]
当x_vars参数值为数字的时候 分块上传js报错 
报错代码段为
```
this.URLSafeBase64Encode = function(v) {
        console.log(v);  
        v = this.base64_encode(v);
        return v.replace(/\//g, '_').replace(/\+/g, '-'); //-----这里报错
    };

**Comment by peaceful321** [comment]
测试 输入数字 这个正则表达式 也会 转字符串的，如图：
![image](https://cloud.githubusercontent.com/assets/9206603/21217201/f8af13fe-c2e5-11e6-80d5-0cb89ae0947f.png)

**Comment by luoyeshu0507** [comment]
@vasth  具体报什么错呢？

**Comment by vasth** [comment]
![qiniu](https://cloud.githubusercontent.com/assets/5569305/21249440/f0480340-c378-11e6-8b20-92b3ada82f7f.png)

**Comment by vasth** [comment]
我把x_vars参数修改为字符串的时候就好了，我设置的是大于4m的文件进行分块上传，每个块的大小是4m我上传5m一下的文件不会报错，但是上传大于5m的文件就会报错，所以我感觉应该是分块上传的时候第二个分块获取x_vars参数时有问题

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-960

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
