### ISSUE TITLE
一个页面需要两处地方上传图片（身份证正反面），请问一套js上传代码能否实现？

### ISSUE THREAD

**Issue by chayangge** [qiniu/js-sdk#208]
browse_button和container 该怎么配置？谢谢

**Comment by luoyeshu0507** [comment]
@chayangge 
你好 可以设置两个上传实例 互不影响 具体可以下载本项目运行示例
线上多文件上传示例：http://jssdk.demo.qiniu.io/multiple

**Comment by lidongcn** [comment]
@chayangge browse_button里面可以传数组

**Comment by chayangge** [comment]
谢谢，问题已解决

**Comment by jarvan4dev** [comment]
@chayangge 请问多图上传如何解决？
