### ISSUE TITLE
生产环境是只需要引入plupload.full.min.js吗？为何报错: mOxie is not defined

### ISSUE THREAD

**Issue by wzvoid** [qiniu/js-sdk#209]
在“使用“哪里，”在页面中引入 plupload，plupload.full.min.js（生产环境）或 引入plupload.dev.js和moxie.js（开发调试）“，这句话的意思是生产环境只用plupload.full.min.js这一个js文件，开发调试环境用：plupload.dev.js和moxie.js这两个js文件？那为何我只用plupload.full.min.js的时候报如下错误：
Uncaught ReferenceError: mOxie is not defined
    at QiniuJsSDK.uploader (qiniu.min.js:2)
    at localhost/:27

**Comment by luoyeshu0507** [comment]
@wzvoid  你好 请看下你的plupload的版本 是否为2.1.1  由于新版plupload升级去掉了mOxie变量 不兼容了哦

**Comment by wzvoid** [comment]
@luoyeshu0507 你好，这个问题已解决，谢谢！目前我还有个问题，就是七牛的js-sdk如何与angular完美搭配，现在想要在微信端使用。我看七牛云个人中心的内容管理部分的图片上传功能好像是用的angularjs。之前看了你在另一个issue里面提到的基于jquery的formdata实现（http://jssdk.demo.qiniu.io/formdata），但是formdata方法可以在图片上传之前对图片压缩吗？就是类似于sdk中的resize配置那样，这样的话我想能够节省云端空间。如果可以，可否给出一个基于angular的实现？谢谢😊～

**Comment by luoyeshu0507** [comment]
@wzvoid  你好 不建议在微信端使用js-sdk 太麻烦了！  对于你的这种应用场景，建议：
1：使用formdata + angular，只要把现在的demo中的jquery ajax改为angular的$http或者其他http组件即可简单的进行上传。
2：formdata无法再上传之前对图片进项压缩，但是可以换个思路：把图片画到一个canvas上，比如100x100的图，可以画成50x50的 再获取该区域的图形，转成图片上传。浏览器中：文件对象，canvas对象，base64 都可以这么互转，通过formdata的append，把转好的图片append到formdata中进项formdata上传。

**Comment by wzvoid** [comment]
@luoyeshu0507 嗯嗯，已经基本解决了，十分感谢啊，呜呜～～，因为这个浪费了好几天。不过我还是想了解下js-sdk和angular如何完美搭配，目前项目做完后会紧接着开发一个后台管理的系统，肯定也要用到七牛云的，最好能有个demo，如果没有，麻烦说个思路，谢谢！！

**Comment by luoyeshu0507** [comment]
@wzvoid 
1. 既然你都用angular了 肯定也不考虑太低的浏览器了，其实就可以用formdata的方式了，做一个组件或者directive之类的，代码没几行，简单易用。
2. 如果你坚持用js-sdk的话，就直接引在页面里吧，把plupload qiniujs等等 还有plupload依赖的一些swf文件全放进页面，页面加载的时候会全局引用这些东西，angular直接用window上的对象即可。具体我也没有demo，不好意思哈

**Comment by wzvoid** [comment]
@luoyeshu0507 嗯嗯，有思路就行了。谢谢啦～

**Comment by z2014** [comment]
我也遇到了这个问题，怎么解决呢，换一个低版本的plupload.qiniu.js吗？

**Comment by luoyeshu0507** [comment]
@z2014  下载最新版本试下

**Comment by tzhgkm** [comment]
@luoyeshu0507
我这边 plupload已经是2.3.1版本，qiniu-js我用1.0.19和其他旧的版本，都会报错：
Uncaught ReferenceError: mOxie is not defined
    at QiniuJsSDK.uploader (main.js:3847)
我引入方式如下：
import 'plupload/js/plupload.full.min'
import 'qiniu-js/src/qiniu'
这是怎么回事呢？

**Comment by zhule** [comment]
七牛，是我见过最他妈垃圾的项目，项目运行必须依赖 pluload.js库，而这个库老是报moxie is not defined 这个错误，关键还不是一个两个遇到这个问题，而是一大批遇到这个问题，竟然到现在还没解决，官方的文档的例子也不提醒一下开发者，真尼玛坑，坑了我一个下午。

**Comment by GuGaobai1994** [comment]
您好，可以参考http://7xsjg3.com1.z0.glb.clouddn.com/JavaScriptLatest.zip ， 已经解决了依赖

**Comment by baiyuxiong** [comment]
同样遇到这个问题，只能用2.1.1吗？不打算支持新版本的plupload了？

**Comment by GuGaobai1994** [comment]
建议使用 2.1.1 ~ 2.1.9

**Comment by zhangfan6644777** [comment]
使用2.1.1-2.1.9  还是报错 不起作用

**Comment by zhangfan6644777** [comment]
解决办法 修改moxie.js 源码中两个最外层自执行函数的参数  (function(exports) {...})(this);  改成 (function(exports) {...})(window);  两个都修改

**Comment by zhangfan6644777** [comment]
引用plupload.dev.js和moxie.js

**Comment by zhangfan6644777** [comment]
是由于webapck打包工具出现的问题
https://github.com/moxiecode/moxie/issues/154

**Comment by FrankFang** [comment]
https://github.com/qiniu/js-sdk/issues/266

**Comment by GuGaobai1994** [comment]
楼上正解

**Comment by houmengxin** [comment]
@luoyeshu0507  你好 我在vue+elementui中 引入js文件 一直报
 ReferenceError: mOxie is not defined
    at eval (plupload.full.min.js?12ca:28)
    at Object../src/components/oss/lib/plupload-2.1.2/js/plupload.full.min.js

**Comment by houmengxin** [comment]
@luoyeshu0507 我是在官网下载的oss文件  版本号是2.1.2

**Comment by houmengxin** [comment]
@luoyeshu0507 

`import crypto from './oss/lib/crypto1/crypto/crypto'
import hmac from './oss/lib/crypto1/hmac/hmac'
import sha1 from './oss/lib/crypto1/sha1/sha1'
import base64 from './oss/lib/base64'
import plupload from './oss/lib/plupload-2.1.2/js/plupload.full.min'
import upload from './oss/upload'`

**Comment by houmengxin** [comment]
@wzvoid  你好 想请问一下这个报错 ReferenceError: mOxie is not defined
at eval (plupload.full.min.js?12ca:28)
at Object../src/components/oss/lib/plupload-2.1.2/js/plupload.full.min.js

**Comment by luoyeshu0507** [comment]
@houmengxin 请使用plupload 2.1.1 或者用最新的js-sdk~

**Comment by cuichhenguang** [comment]
@luoyeshu0507 我已经把moxie.js和plupload.dev.js文件给替换调了，

但是又报错 ReferenceError: accessid is not defined at Object.eval (uploads.js?a208:1)，，oss的uploads.js里面的 accessid  accesskey  host 这些我已经配置过了

**Comment by cuichhenguang** [comment]
![QQ图片20190627141544](https://user-images.githubusercontent.com/30429416/60241532-17296680-98e6-11e9-9158-e06f5fa17985.png)
@ @

**Comment by houmengxin** [comment]
@luoyeshu0507我已经把moxie.js和plupload.dev.js文件给替换调了，

但是又报错 ReferenceError: accessid is not defined at Object.eval (uploads.js?a208:1)，，oss的uploads.js里面的 accessid accesskey host 这些我已经配置过了, 如果我定义的话 upload.js文件出连续出现问题

**Comment by luoyeshu0507** [comment]
@cuichhenguang @houmengxin 额 总觉得哪里不对 这个评论针对的是1.x版本的js-sdk 两年前的版本 用的也是老版本的plupload ~ 现在新版的js-sdk 跟这条评论应该没什么关系了啊

**Comment by houmengxin** [comment]
@luoyeshu0507 你之前用的是七牛云的上传？，有qiniu.js   plupload.full.min.js 等。我现在用的是阿里云 oss JavaScript客户端签名文件上传  官方文档内给的demo是传统的代码引入方式，用到的模块有crypto.js、hmac.js、sha1.js、base64.js、plupload.js、、、、、、不过看您是我把这边的plupload版本改为了2.1.1解决了mOxie is not defined的报错

**Comment by luoyeshu0507** [comment]
@houmengxin 这是七牛的js-sdk的git项目呀。。

**Comment by forrest-mao** [comment]
Duplicate of #197
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
