### ISSUE TITLE
上传路径如何指定呢?实在jssdk 操作吗

### ISSUE THREAD

**Issue by muiccc** [qiniu/js-sdk#211]
比如 我想上传到 这个路径  2011/03/03/03/xxx.mp4,那要如何操作呢

**Comment by luoyeshu0507** [comment]
@muiccc 你好 七牛存储没有文件夹的概念 是一种对象存储  key:value的方式   你可以把文件名叫做 2011/03/03/03/xxx.mp4   看起来是一个文件夹的样子 并通过2011前缀在管理平台搜索
