### ISSUE TITLE
在360安全浏览器兼容模式下遇到的问题

### ISSUE THREAD

**Issue by maokeyang** [qiniu/js-sdk#212]
1. 添加图片有时候响应不了

1. 弹出文件选择框，图片ctrl+a 全选不了 （我的系统是win10）

**Comment by luoyeshu0507** [comment]
@maokeyang 
你好，麻烦详细的描述一下你遇到的问题，在什么版本的js-sdk，什么环境下，报什么错，便于我们快速定位问题。谢谢啦，你也可以到七牛官网和文档站提交工单来提问。
