### ISSUE TITLE
初始化未执行uptoken_func方法获取toke

### ISSUE THREAD

**Issue by HappyAdu** [qiniu/js-sdk#213]
代码如下，求解答
![image](https://cloud.githubusercontent.com/assets/18397775/23164492/439f8f4e-f872-11e6-8b09-38feb9ea19f9.png)
![image](https://cloud.githubusercontent.com/assets/18397775/23164501/49c314e0-f872-11e6-8607-2c0e041b8bb5.png)

**Comment by HappyAdu** [comment]
追踪进入qiniu.js发现甚至没有执行getUptoken

**Comment by luoyeshu0507** [comment]
@HappyAdu   你这是个异步方法吧 返回的时候uptoken有值了么？    需要返回一个uptoken的字符串

**Comment by Virgo9** [comment]
这个问题解决了么，我也遇到了
