### ISSUE TITLE
急用，第二次uploadqiniu.com AJAX请求显示400：incorrect region, please use up-z2.qiniu.com

### ISSUE THREAD

**Issue by HappyAdu** [qiniu/js-sdk#214]
求指教，急用。
![image](https://cloud.githubusercontent.com/assets/18397775/23198465/bb47401a-f902-11e6-8a1c-64b495f955dd.png)
![image](https://cloud.githubusercontent.com/assets/18397775/23198496/faf8ff6e-f902-11e6-9c47-4cf1e865a731.png)
![image](https://cloud.githubusercontent.com/assets/18397775/23198506/02ce8984-f903-11e6-84cb-8d8fee0e7a35.png)
![image](https://cloud.githubusercontent.com/assets/18397775/23198510/0bc34ef8-f903-11e6-9fef-571d4b15461d.png)

**Comment by luoyeshu0507** [comment]
@HappyAdu 
如错误提示：incorrect region, please use up-z2.qiniu.com  
错误的区域，请使用up-z2.qiniu.com
不同的上传地址对应不同的上传链接 ，你用的是华东区的上传url，上传的空间是华南的空间

**Comment by HappyAdu** [comment]
这个是后台那儿改吧。前端知识获取token

**Comment by HappyAdu** [comment]
应该怎么改呢？文档里面没看到如何改上传地区url

**Comment by luoyeshu0507** [comment]
@HappyAdu   你要不用个华东的空间？ 我先研究下这个问题，研究好了再回复

**Comment by HappyAdu** [comment]
@luoyeshu0507  好的，我让后台改下。谢谢。

**Comment by luoyeshu0507** [comment]
@HappyAdu 
感觉是设置了get_new_uptoken:true，和一个异步的获取uptoken的方式， 这样每次上传一个文件之前去异步拿一个uptoken，用这个uptoken再去异步拿一个这个uptoken对应的上传空间地址。
在上传地址还未拿回来之前就做了上传操作，导致上传的是错误域名，报错之后域名其实才被改成了正确的，这时候在进行第二次上传其实会成功。
如果不需要每次上传都重新获取一次uptoken的话，可以吧get_new_uptoken设置为false，或者使用华东区域的空间，因为默认是传到华东的，这样就不会报错了。
这是个bug，我看下怎么修复，非常感谢。

**Comment by luoyeshu0507** [comment]
@HappyAdu 
你好，请把 qiniu.js中 第627行，ajax.open('GET', uphosts_url, true);中的true改为false，即可修复该问题，后面会对应发布修订版本

**Comment by HappyAdu** [comment]
@luoyeshu0507   十分感谢。

**Comment by never615** [comment]
![screen shot 2017-03-13 at 12 18 46 pm](https://cloud.githubusercontent.com/assets/9959927/23841332/6086af50-07e7-11e7-9dcf-ef356e28d4fc.png)
遇到了同样的问题,默认地址不能用..空间是华南区的..

**Comment by luoyeshu0507** [comment]
@never615 
这周内会修复 抱歉 请参照上面我回复的修复方法试一下

**Comment by never615** [comment]
@luoyeshu0507 
我的 qiniu-js-sdk v1.0.16-beta,搜不到你那句话.
我改了代码里默认写死的url,改成华南区的就可以了.

**Comment by luoyeshu0507** [comment]
@never615 
beta不是正式版啊  最新的1.0.18吧 行吧 反正解决问题就好~！

**Comment by never615** [comment]
https://developer.qiniu.com/sdk
这里官网给出的下载链接是这个...
https://github.com/qiniu/js-sdk/archive/v1.0.16-beta.zip

**Comment by luoyeshu0507** [comment]
@never615 
哈哈哈。。尴尬 我去让他们更新下~！

**Comment by luoyeshu0507** [comment]
fixed
