### ISSUE TITLE
建议放宽GPL License 到MIT

### ISSUE THREAD

**Issue by mingyuan-xia** [qiniu/js-sdk#217]
前端Js库建议放宽到MIT，GPL大家都知道意味着什么，请参考：
https://github.com/twbs/bootstrap/blob/master/LICENSE
同时七牛的android-sdk，java-sdk以及nodejs-sdk都是MIT

**Comment by luoyeshu0507** [comment]
@mingyuan-xia  
多谢提醒，js-sdk是基于 MIT 协议的，写在了package.json文件中，有个 ```"license": "MIT"```，我下个版本修改下readme.md ！
