### ISSUE TITLE
在IE9上一直调不起flash上传

### ISSUE THREAD

**Issue by ZH4L** [qiniu/js-sdk#220]
引用的js和swf都是直接从你们实例页面down下来的，代码除了token，其他都是一样的，但是IE9上就是用不了flash上传，一直报200错误

**Comment by Koreyhan** [comment]
我也想了解这个问题，官方的demo在IE9上面好像也跑不起来

**Comment by GuGaobai1994** [comment]
直接用flash

**Comment by GuGaobai1994** [comment]
![image](https://user-images.githubusercontent.com/20764006/32814813-8ada5736-c9eb-11e7-88fa-b87c6ef72f19.png)
