### ISSUE TITLE
ios微信公众号开发，点击第一个实例可以上传成功，但是第二个实例就没有反应，代码按照官方的要求写的，这个如何解决（安卓是正常的）？

### ISSUE THREAD

**Issue by anxiaobei** [qiniu/js-sdk#226]

**Comment by GuGaobai1994** [comment]
用微信调试工具看下异常，对于移动端使用formdata比较好

**Comment by HuangXiaoxing** [comment]
我们也遇到这种问题，请问解决了吗？是怎么解决的？

**Comment by forrest-mao** [comment]
是否可以尝试使用最新的 3.x jssdk，该版本不依赖 plupload 第三方组件，兼容性更强一些，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

**Comment by forrest-mao** [comment]
和 #142 类似，仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-954

**Comment by yinxulai** [comment]
长时间未得到有效答复，且该版本已不再维护，推荐更新到新版，该 issue 关闭。
