### ISSUE TITLE
现在是没法支持es6的模块化引用么

### ISSUE THREAD

**Issue by lwyj123** [qiniu/js-sdk#228]
Rt

**Comment by cag2050** [comment]
可以使用CommonJS模块化，例子：https://github.com/cag2050/qiniu_demo

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-961

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
