### ISSUE TITLE
在安卓微信浏览器中无法上传

### ISSUE THREAD

**Issue by ZH4L** [qiniu/js-sdk#231]
图片能选，但是选了之后就没有了，什么都没有执行，一个事件都没有进

**Comment by GuGaobai1994** [comment]
@ZH4L  建议升级微信版本
![qq 20170504092533](https://cloud.githubusercontent.com/assets/20764006/25687751/a2deab04-30ab-11e7-9d37-8108904578a8.jpg)

**Comment by ZH4L** [comment]
@GuGaobai1994 后来发现问题原因了，是由于加了限制文件类型导致的，去掉就可以了，不知道为啥

**Comment by GuGaobai1994** [comment]
@ZH4L 这个是pluploader提供的相关属性，有的应用场景需要限制用户上传文件的类型，比如上传图片的接口，不想让用户上传视屏或者文本文件

**Comment by ZH4L** [comment]
@GuGaobai1994 是的，我原来就是加了filter，只让用户上传图片，当时做完的时候都是可以的，后来不知道为什么突然不行了，可能是因为微信x5干了什么坏事

**Comment by wang-fu** [comment]
目前版本微信内无法上传加了filter的用法的文件，定位了下原因，发现不是原本qiniusdk问题所在，而是七牛sdk 一个依赖plupload.js导致，而plupload依赖moxie.js ，moxie.js是用来处理fileReader。在动态生成input='file'标签的时候，如果七牛设置了filter，则会向input设置对应的accept属性。这个属性通过用于限制上传的格式，微信对它并没有做很好的兼容，上传不对的图片不会触发onchange事件。将moxie.js源码里面这个去掉重新编译就行，一般不会使用accept来限制上传格式，而是js。

**Comment by forrest-mao** [comment]
是否可以尝试使用最新的 3.x jssdk，该版本不依赖 plupload 第三方组件，兼容性更强一些，不会出席那类似的问题，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
