### ISSUE TITLE
七牛 js-sdk 源码中的Bug？？？

### ISSUE THREAD

**Issue by mayon** [qiniu/js-sdk#232]
**先说一个关键的Bug啊，设置 uptoken_url 获取动态 Token 的问题。**

```
// master/dist/qiniu.js
ajax.open('GET', that.uptoken_url + '?' + (+ new Date()), false);    // 693 行
```

```
// master/dist/qiniu.min.js
if(c.open("GET",that.uptoken_url+"?"+ +new Date,!1)
```

that.uptoken_url 直接 Console 出来是 undefined，that 换成 op，没毛病，顺利通过。

**再说下这次项目中遇到的关于获取动态 Token 的问题。**

业务场景是这样的：首先，动态获取 Token，Ajax  请求参数需要带上用户选择 file 的 Key，（有配置 Key 的自定义 func），也就是说，Token 跟 file 的 Key 有绑定关系。然后将服务端返回的 res.downloadurl 指定为 file 的下载地址。那么问题来了：

1. 七牛动态获取 Token 不支持自定义参数，更别说加上 file 的 Key，看上面 693 行代码就知道了，而且源码中设置 file Key 的操作在 获取 动态 Token 之后（参见源码 920 附近代码）；
2. uptoken_url 只是个静态配置，没法添加请求成功后的回调，更没法将请求返回的数据绑定到用户选择的 file 对象上。

好乱啊，写到这里我都不知道我要写啥了，可能跟要发版本了 bug 还没改完心里比较急躁有关吧。
把源码做了改动，能满足业务需求。

---

PS：不知道提过这些问题之后，七牛 js-SDK 会不会有升级呢😁

**Comment by GuGaobai1994** [comment]
可以在服务器端获取token的时候带上key，然后服务器生成token的时候写在scope里
https://developer.qiniu.com/kodo/manual/1206/put-policy
![image](https://user-images.githubusercontent.com/20764006/26864186-558fa12a-4b89-11e7-860e-1b64e30996e6.png)
