### ISSUE TITLE
表单异步提交

### ISSUE THREAD

**Issue by hearAllParties** [qiniu/js-sdk#233]
在上传七牛云之前，先进行截取图像，然后再进行表单上传，但是上传的是base64格式的img，不是file对象，请问此时怎么上传

**Comment by GuGaobai1994** [comment]
参考 https://developer.qiniu.com/kodo/kb/1326/how-to-upload-photos-to-seven-niuyun-base64-code

**Comment by hearAllParties** [comment]
thx
