### ISSUE TITLE
uptoken_func不支持异步

### ISSUE THREAD

**Issue by Gaubee** [qiniu/js-sdk#235]
看了一下源码，由于后端服务器是不同域的问题，所以在使用uptoken_url的时候，没有带上cookies，所以没法安全的授权提供uptoken，故改用uptoken_func，可是发现在居然要写同步代码…… 而我厂这边封装的ajax api是基于fetch的，全是异步的。感觉非常麻烦，需要针对这个Qiniu-js-sdk重新写一个ajax的并处理数据包。

希望提供回调方面的支持。

**Comment by GuGaobai1994** [comment]
如果不获取到uptoken是无法完成上传操作的，此处确实无法异步进行

**Comment by harry91** [comment]
什么时候能支持Promise异步获取呢？

**Comment by Lockseed** [comment]
可以考虑将`auto_start`设置为`false`，在获取`uptoken`后手动`up.start()`的方式。
参考：
```
const uploader = Qiniu.uploader({
    ...
    uptoken_func: function(file, cb) {
        if (!file) {
            console.log('qiniu uptoken func Got No File!');
            return;
        }
        file.key = res.key ? res.key : '';
        return file.uptoken;
    },
    ...
    auto_start: false,
    ...
    init: {
        'FileAdded': function (up, files) {
            plupload.each(files, function(file) {
                getUptokenAsnyc(function(res){
                    file.uptoken = res.uptoken;
                    file.key = res.key;
                    up.start();
                });
            });
        },
        ...
        'Key': function (up, file) {
            var key = '';
            key = file.key ? file.key : '';
            return key
        }
    }
});
```

**Comment by harry91** [comment]
@Lockseed Good idea! Thanks~

**Comment by SilentFlute** [comment]
@Lockseed 哈喽哈喽，话说我也遇到了这个跨域没法带cookie，导致无法从服务端获取uptoken的问题，然后我照你贴的代码试了试，最后发现`uptoken_func`这个方法只会在一开始执行，而选择文件获取token之后就不会再执行了，因此`return file.uptoken;`这句没法设置上uptoken，`auto_start`也设置为`false`了依旧不行，我用的七牛`js-sdk`的版本比较老，是之前老项目的: 
- `plupload.full.min.js`: `v1.3.5`
- `qiniu-js`: `v1.0.18`

最后我是先请求token，然后再在回调中`Qiniu.uploader({...})`，这样倒是没问题，可以传，但是不明白为何照你那个方法不行，求指点🤣🤣

**Comment by forrest-mao** [comment]
目前 3.x 的 SDK 中可以直接给 qiniu.upload 中的 token 字段写入上传凭证字符串即可，不用通过 uptoken url 来获取，获取 token 的方式可以自定义，这样应该可以解决当前的问题。

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-962

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
