### ISSUE TITLE
有没有秒传的功能？

### ISSUE THREAD

**Issue by kivenZhou** [qiniu/js-sdk#240]
在上传多张图片的过程中，可以做到在将图片添加到队列之后，由后端人员根据前端给予后端的图片hash（前端计算的图片hash）,判断哪些图片需要上传，哪些不需要上传。不需要上传的图片实现秒传功能，也就是不需要走七牛云平台，直接显示上传成功（实际上是将不需要上传的图片从队列中删除）？

**Comment by GuGaobai1994** [comment]
目前没有封装这种上传逻辑，根据七牛的上传策略如果同空间内有hash值相同的文件，默认是不会覆盖的，会返回614状态码，如果你想要自行判断hash值,可以参考https://developer.qiniu.com/dora/manual/1297/file-hash-value-qhash

**Comment by kivenZhou** [comment]
好吧，不过其实是因为如果出现同名的hash，那么七牛云不会覆盖，但是网络请求还是需要发的，所以为了节约带宽以及请求资源，所以前端需要一开始就知道哪些需要上传，希望可以完善一下！对于上传策略的优化！
