### ISSUE TITLE
添加队列后如何从队列删除不需要的文件？

### ISSUE THREAD

**Issue by kivenZhou** [qiniu/js-sdk#241]
这里我想问两个问题，第一：在文件添加到队列里面之后（或者之前）如何获取上传的图片信息？如果是用input的file可以获取到图片信息。第二：用plupload的removeFile方法删除队列里面内容的时候，报错！Cannot read property 'getTime' of undefined 还有其他方法将多个上传文件中的某个删除么？

**Comment by kivenZhou** [comment]
删除的方法已经可以用了，直接把代码注释掉就可以了，不过文件添加到队列里面之后如何获取图片的信息以便于给图片添加hash这一块就不知道了，麻烦大神说一下！

**Comment by GuGaobai1994** [comment]
指定key为undifined会默认使用hash值传至七牛空间
   'Key': function(up, file) {
                var key = undefined;
                // do something with key
                return key
            }

**Comment by kivenZhou** [comment]
额。。。我的意思是还没有上传七牛之前，因为我想在图片刚添加到队列之后进行判断，我获取到图片的信息之后自己获取图片的hash，然后根据我们的接口判断数据库是否有这一张图片，如果有的话就不需要走七牛平台，因为七牛平台一定会有，所以前端就不需要重复提交了！可以在刚添加进队列之后获取到图片的信息么？

**Comment by GuGaobai1994** [comment]
可以的。在beforeUpload是，读取file信息
![image](https://user-images.githubusercontent.com/20764006/28047971-7a51de36-6620-11e7-91f7-dc6d7fe1d277.png)

**Comment by GuGaobai1994** [comment]
可以在beforeUpload或者FilesAdded是获取file信息
![image](https://user-images.githubusercontent.com/20764006/28047998-9f224a98-6620-11e7-82d0-8eb2de9a4d82.png)

**Comment by kivenZhou** [comment]
确实可以获取到，不过获取到的是plupload封装过的。。。我再看看吧！谢谢！
