### ISSUE TITLE
设置get_new_uptoken为true时 报错

### ISSUE THREAD

**Issue by RecordYXS** [qiniu/js-sdk#243]
七牛js-sdk  1.0.19版本说修复  设置get_new_uptoken为true时 使用非华东机房的空间报错问题，   可是我使用这个版本发现设置为true还是报错，这是问什么呢？谢谢！

**Comment by GuGaobai1994** [comment]
这边没能复现这个问题，能否给出具体的console信息

**Comment by RecordYXS** [comment]
@GuGaobai1994  你好，问题是这样的，设置为true之后，点击上传，前两次上传没问题，点击第三次上传的时候报错，错误显示为
![image](https://user-images.githubusercontent.com/20061169/28396681-8ea7bd2c-6d2f-11e7-9cb0-e7b3d5d0fa9d.png)
请查看，谢谢！

**Comment by GuGaobai1994** [comment]
用http://ordi6dhbw.bkt.clouddn.com/qiniu.js这个替换现在使用的qiniu.js试一下

**Comment by RecordYXS** [comment]
@GuGaobai1994 非常感谢，替换之后就可以了，谢谢谢谢！
