### ISSUE TITLE
七牛js-SDK   BeforeUpload方法  up.removeFile() 报错

### ISSUE THREAD

**Issue by RecordYXS** [qiniu/js-sdk#244]
问题是这样的，我想上传规定格式的文件，我也知道mime_types可以设置文件上传类型，但是类型设置过多的话，打开上传窗口会很慢，大概在6～9秒之间，所以我打算自己进行判断。
我在BeforeUpload中判断所选图片是否是我规定的文件类型，如果不是，我想把它移除掉，所以用了，up.removeFile()方法，
'BeforeUpload': function(up, file) {
                  // 每个文件上传前，处理相关的事情
                  if(!isUpload){
                    up.removeFile(file);
                  }
             },
提示：
![image](https://user-images.githubusercontent.com/20061169/28413525-69141b64-6d7a-11e7-9a4e-ee458b29e883.png)

当然我认为最简洁的方式，应该是直接在BeforeUpload方法中   return false  
'BeforeUpload': function(up, file) {
                  // 每个文件上传前，处理相关的事情
                  if(!isUpload){
                    return false;
                  }
             },
这样是可以中断上传操作，但是下一次点击上传的时候，因为中断了不能再次上传文件了，麻烦大神帮忙解决一下，谢谢！

**Comment by GuGaobai1994** [comment]
这和remove没有关系，将size改成length

**Comment by RecordYXS** [comment]
@GuGaobai1994   你的意思是说要修改plupload.full.min里面的代码吗？我刚试了一下，改成length又报Cannot read property 'length' of null，请指教，或者有什么办法可以终止当前的上传，下次点击上传不会因为上次的上传中断而无法继续吗？ 谢谢！

**Comment by GuGaobai1994** [comment]
能将完整的uploader构建方法提供一下吗，应该不是remove方法报的错

**Comment by RecordYXS** [comment]
可以的，麻烦了，谢谢！因为在上传图片的时候，我会打开显示上传进度的列表，所以，在FilesAdded的时候就进行了判断。
    var isUpload =false;
    var  uploader = Qiniu.uploader({
         runtimes: 'html5,flash,html4',      // 上传模式，依次退化
         browse_button: 'pickfiles',         // 上传选择的点选按钮，必需
         // 在初始化时，uptoken，uptoken_url，uptoken_func三个参数中必须有一个被设置
         // 切如果提供了多个，其优先级为uptoken > uptoken_url > uptoken_func
         // 其中uptoken是直接提供上传凭证，uptoken_url是提供了获取上传凭证的地址，如果需要定制获取uptoken的过程则可以设置uptoken_func
        //  uptoken:'‘, // uptoken是上传凭证，由其他程序生成
         uptoken_url: uptoken_url,         // Ajax请求uptoken的Url，强烈建议设置（服务端提供）
        //  uptoken_func: function(){    // 在需要获取uptoken时，该方法会被调用
        //  },
         get_new_uptoken: true,             // 设置上传文件的时候是否每次都重新获取新的uptoken
         // downtoken_url: '/downtoken',
         // Ajax请求downToken的Url，私有空间时使用，JS-SDK将向该地址POST文件的key和domain，服务端返回的JSON必须包含url字段，url值为该文件的下载地址
         // unique_names: true,              // 默认false，key为文件名。若开启该选项，JS-SDK会为每个文件自动生成key（文件名）
         // save_key: true,                  // 默认false。若在服务端生成uptoken的上传策略中指定了sava_key，则开启，SDK在前端将不对key进行任何处理
         domain: domain,     // bucket域名，下载资源时用到，必需
         container: 'container',             // 上传区域DOM ID，默认是browser_button的父元素
         max_file_size: '100000mb',             // 最大文件体积限制
         flash_swf_url: '../../static/Moxie.swf',  //引入flash，相对路径
         max_retries: 3,                     // 上传失败最大重试次数
         dragdrop: false,                     // 开启可拖曳上传
         drop_element: 'container',          // 拖曳上传区域元素的ID，拖曳文件或文件夹后可触发上传
         chunk_size: '4mb',                  // 分块上传时，每块的体积
         auto_start: true,                   // 选择文件后自动上传，若关闭需要自己绑定事件触发上传
         init: {
             'FilesAdded': function(up, files) {
                var filesArr=[];
                var navigations=GetFromSessionStorage('navigation',2);
                var album_name='';
                if(navigations&&navigations.length>0){
                   album_name=navigations[navigations.length-1].navigation;
                }
                plupload.each(files, function(file) {
                     // 文件添加进队列后，处理相关的事情
                     if(file.type=='image/jpeg'||file.type=='image/jpg'||file.type=='image/png'||file.type=='image/gif'||file.type=='application/zip'||file.type=='application/pdf'){
                       isUpload =true;
                       file.album_name=album_name;
                       filesArr.push(file);
                     }else {
                       isUpload =false;
                       return false;
                     }
                 });
                 if(isUpload){
                   handleUploading();
                   getUploadAllList(filesArr);
                 }else {
                   message.error('上传类型只能是.jpg,.png,.gif,.pdf,.zip');
                   return false;
                 }
             },
             'BeforeUpload': function(up, file) {
                  // 每个文件上传前，处理相关的事情
                  if(! isUpload){
                    up.removeFile(file);
                  }
             },
             'UploadProgress': function(up, file) {
                    // 每个文件上传时，处理相关的事情
                   getUploadProgress(file);
             },
             'FileUploaded': function(up, file, info) {
                    // 每个文件上传成功后，处理相关的事情
                    // 其中info是文件上传成功后，服务端返回的json，形式如：
                    // {
                    //    "hash": "Fh8xVqod2MQ1mocfI4S4KpRL6D98",
                    //    "key": "gogopher.jpg"
                    //  }
                    // 查看简单反馈
                    // var domain = up.getOption('domain');
                    // var res = parseJSON(info);
                    // var sourceLink = domain +"/"+ res.key; 获取上传成功后的文件的Url
             },
             'Error': function(up, err, errTip) {
                    //上传出错时，处理相关的事情
             },
             'UploadComplete': function() {
                    //队列文件处理完毕后，处理相关的事情
             },
             'Key': function(up, file) {
                 // 若想在前端对每个文件的key进行个性化处理，可以配置该函数
                 // 该配置必须要在unique_names: false，save_key: false时才生效
                var key = "";
               // do something with key here
               return key
             }
         }
      });

**Comment by GuGaobai1994** [comment]
我来看一下

**Comment by GuGaobai1994** [comment]
/*global Qiniu */
/*global plupload */
/*global FileProgress */
/*global hljs */

$(function() {
    var uploader = Qiniu.uploader({
        disable_statistics_report: false,
        runtimes: 'html5,flash,html4',
        browse_button: 'pickfiles',
        container: 'container',
        drop_element: 'container',
        max_file_size: '1000mb',
        flash_swf_url: 'bower_components/plupload/js/Moxie.swf',
        dragdrop: true,
        chunk_size: '4mb',
        multi_selection: !(moxie.core.utils.Env.OS.toLowerCase()==="ios"),
        uptoken: 'FMVCRs2-LO1ivRNi4l7mEZE6ZDvPv-519D12kZCO:R7OxFntI4vdbA7S7z8aK2UbdrS8=:eyJzY29wZSI6InRlc3QiLCJkZWFkbGluZSI6MjUwMDYwODEyMn0=',
        // uptoken_func: function(){
        //     var ajax = new XMLHttpRequest();
        //     ajax.open('GET', $('#uptoken_url').val(), false);
        //     ajax.setRequestHeader("If-Modified-Since", "0");
        //     ajax.send();
        //     if (ajax.status === 200) {
        //         var res = JSON.parse(ajax.responseText);
        //         console.log('custom uptoken_func:' + res.uptoken);
        //         return res.uptoken;
        //     } else {
        //         console.log('custom uptoken_func err');
        //         return '';
        //     }
        // },
        domain: $('#domain').val(),
        get_new_uptoken: true,
        // downtoken_url: '/downtoken',
        // unique_names: true,
        // save_key: true,
        // x_vars: {
        //     'id': '1234',
        //     'time': function(up, file) {
        //         var time = (new Date()).getTime();
        //         // do something with 'time'
        //         return time;
        //     },
        // },
        auto_start: true,
        log_level: 5,
        init: {
            'BeforeChunkUpload':function (up,file) {
                console.log("before chunk upload:",file.name);
            },
            'FilesAdded': function(up, files) {
                $('table').show();
                $('#success').hide();
                plupload.each(files, function(file) {
                    if(file.type=='image/jpeg'||file.type=='image/jpg'||file.type=='image/png'||file.type=='image/gif'||file.type=='application/zip'||file.type=='application/pdf'){
                        console.log('type:' + file.type);
                        isUpload =true;
                        file.album_name=album_name;
                        var progress = new FileProgress(file, 'fsUploadProgress');
                        progress.setStatus("等待...");
                        progress.bindUploadCancel(up);
                    }else {
                        isUpload = false;
                        up.removeFile(file);
                        console.log('上传类型只能是.jpg,.png,.gif,.pdf,.zip');
                        return false;
                    }});
            },
            'BeforeUpload': function(up, file) {
                console.log("this is a beforeupload function from init");
                var progress = new FileProgress(file, 'fsUploadProgress');
                var chunk_size = plupload.parseSize(this.getOption('chunk_size'));
                if (up.runtime === 'html5' && chunk_size) {
                    progress.setChunkProgess(chunk_size);
                }
            },
            'UploadProgress': function(up, file) {
                var progress = new FileProgress(file, 'fsUploadProgress');
                var chunk_size = plupload.parseSize(this.getOption('chunk_size'));
                progress.setProgress(file.percent + "%", file.speed, chunk_size);
            },
            'UploadComplete': function() {
                $('#success').show();
            },
            'FileUploaded': function(up, file, info) {
                var progress = new FileProgress(file, 'fsUploadProgress');
                progress.setComplete(up, info);
            },
            'Error': function(up, err, errTip) {
                $('table').show();
                var progress = new FileProgress(err.file, 'fsUploadProgress');
                progress.setError();
                progress.setStatus(errTip);
            }
                // ,
                // 'Key': function(up, file) {
                //     var key = "";
                //     // do something with key
                //     return key
                // }
        }
    });
    uploader.bind('FilesAdded', function() {
        console.log("hello man, a file added")
    });
    uploader.bind('BeforeUpload', function () {
        console.log("hello man, i am going to upload a file");
    });
    uploader.bind('FileUploaded', function () {
        console.log('hello man,a file is uploaded');
    });
    $('#container').on(
        'dragenter',
        function(e) {
            e.preventDefault();
            $('#container').addClass('draging');
            e.stopPropagation();
        }
    ).on('drop', function(e) {
        e.preventDefault();
        $('#container').removeClass('draging');
        e.stopPropagation();
    }).on('dragleave', function(e) {
        e.preventDefault();
        $('#container').removeClass('draging');
        e.stopPropagation();
    }).on('dragover', function(e) {
        e.preventDefault();
        $('#container').addClass('draging');
        e.stopPropagation();
    });



    $('#show_code').on('click', function() {
        $('#myModal-code').modal();
        $('pre code').each(function(i, e) {
            hljs.highlightBlock(e);
        });
    });


    $('body').on('click', 'table button.btn', function() {
        $(this).parents('tr').next().toggle();
    });


    var getRotate = function(url) {
        if (!url) {
            return 0;
        }
        var arr = url.split('/');
        for (var i = 0, len = arr.length; i < len; i++) {
            if (arr[i] === 'rotate') {
                return parseInt(arr[i + 1], 10);
            }
        }
        return 0;
    };

    $('#myModal-img .modal-body-footer').find('a').on('click', function() {
        var img = $('#myModal-img').find('.modal-body img');
        var key = img.data('key');
        var oldUrl = img.attr('src');
        var originHeight = parseInt(img.data('h'), 10);
        var fopArr = [];
        var rotate = getRotate(oldUrl);
        if (!$(this).hasClass('no-disable-click')) {
            $(this).addClass('disabled').siblings().removeClass('disabled');
            if ($(this).data('imagemogr') !== 'no-rotate') {
                fopArr.push({
                    'fop': 'imageMogr2',
                    'auto-orient': true,
                    'strip': true,
                    'rotate': rotate,
                    'format': 'png'
                });
            }
        } else {
            $(this).siblings().removeClass('disabled');
            var imageMogr = $(this).data('imagemogr');
            if (imageMogr === 'left') {
                rotate = rotate - 90 < 0 ? rotate + 270 : rotate - 90;
            } else if (imageMogr === 'right') {
                rotate = rotate + 90 > 360 ? rotate - 270 : rotate + 90;
            }
            fopArr.push({
                'fop': 'imageMogr2',
                'auto-orient': true,
                'strip': true,
                'rotate': rotate,
                'format': 'png'
            });
        }

        $('#myModal-img .modal-body-footer').find('a.disabled').each(function() {

            var watermark = $(this).data('watermark');
            var imageView = $(this).data('imageview');
            var imageMogr = $(this).data('imagemogr');

            if (watermark) {
                fopArr.push({
                    fop: 'watermark',
                    mode: 1,
                    image: 'http://www.b1.qiniudn.com/images/logo-2.png',
                    dissolve: 100,
                    gravity: watermark,
                    dx: 100,
                    dy: 100
                });
            }

            if (imageView) {
                var height;
                switch (imageView) {
                    case 'large':
                        height = originHeight;
                        break;
                    case 'middle':
                        height = originHeight * 0.5;
                        break;
                    case 'small':
                        height = originHeight * 0.1;
                        break;
                    default:
                        height = originHeight;
                        break;
                }
                fopArr.push({
                    fop: 'imageView2',
                    mode: 3,
                    h: parseInt(height, 10),
                    q: 100,
                    format: 'png'
                });
            }

            if (imageMogr === 'no-rotate') {
                fopArr.push({
                    'fop': 'imageMogr2',
                    'auto-orient': true,
                    'strip': true,
                    'rotate': 0,
                    'format': 'png'
                });
            }
        });

        var newUrl = Qiniu.pipeline(fopArr, key);

        var newImg = new Image();
        img.attr('src', 'images/loading.gif');
        newImg.onload = function() {
            img.attr('src', newUrl);
            img.parent('a').attr('href', newUrl);
        };
        newImg.src = newUrl;
        return false;
    });

});

**Comment by GuGaobai1994** [comment]
看一下这种方式合用吗

**Comment by RecordYXS** [comment]
@GuGaobai1994 非常感谢，谢谢提供了代码供我参考，根据你的思路，我在FilesAdded方法中使用up.removeFile(file)没问题，并且中断了上传操作，👍
