### ISSUE TITLE
请教下，有没有最简化的浏览器上传实例？

### ISSUE THREAD

**Issue by 285858315** [qiniu/js-sdk#246]

**Comment by GuGaobai1994** [comment]
https://github.com/qiniu/js-sdk/?ref=developer.qiniu.com
https://github.com/qiniu/js-sdk/blob/master/demo/views/formdata.html

**Comment by Klauszhao** [comment]
https://blog.csdn.net/randompeople/article/details/79657920
本人自己实现的，有源码
