### ISSUE TITLE
https://github.com/qiniu/js-sdk/blob/master/src/qiniu.js#L1515 报错

### ISSUE THREAD

**Issue by sunsly1991** [qiniu/js-sdk#248]
`file._start` file 可能不存在，导致代码无法继续执行

**Comment by sunsly1991** [comment]
https://github.com/qiniu/js-sdk/blob/master/src/qiniu.js#L1515

**Comment by GuGaobai1994** [comment]
可以在option里设置op.disable_statistics_report

**Comment by sunsly1991** [comment]
是的，已设置。是新版本引入的，之前版本并没有该参数才会报错。

**Comment by jemygraw** [comment]
可以使用demo看看是否出错么？http://jssdk.demo.qiniu.io/

**Comment by sunsly1991** [comment]
感谢，报错的原因是因为设置了drop_container的默认参数，但并页面并没有该dom元素。

这种情况下，未设置disable_statistics_report，代码就挂了，可以复现下。旧版本这个行为不会报错，所以一直没注意到。

**Comment by jemygraw** [comment]
好的。谢谢
