### ISSUE TITLE
多个文件上传时，一个文件上传暂停，怎么使后续文件上传？

### ISSUE THREAD

**Issue by commitqdy** [qiniu/js-sdk#249]
暂停继续调用的是stop()与start()方法，不能实现后续文件上传。removeFile()方法可以实现，但该方法实现暂停，不知道怎么重新启动。求大神告知怎么解决这个问题

**Comment by GuGaobai1994** [comment]
removeFile()会将文件移除队列，无法恢复上传。使用stop和start可以实现后续文件上传，具体可以参考jsdemo.gugaobai.top/index1.html

**Comment by commitqdy** [comment]
这个demo里上传多个文件时，暂停第一个上传，后面的也不会开始呀

**Comment by GuGaobai1994** [comment]
这个目前sdk无法无法做到，需要将上传任务移除

**Comment by commitqdy** [comment]
恩恩，谢谢啦
