### ISSUE TITLE
最新Chrome JS SDK发生错误

### ISSUE THREAD

**Issue by Novia-liang** [qiniu/js-sdk#251]
Chrome  版本 60.0.3112.78（正式版本） 
错误：Uncaught TypeError: Cannot read property '2' of null
          at plupload.Uploader.<anonymous> (qiniu.js:1356)
          at plupload.Uploader.dispatchEvent (plupload.dev.js:2193)
          at plupload.Uploader.trigger 
代码：(qiniu.js:1356) var matchedGroups = (err && err.responseHeaders && err.responseHeaders.match) ? err.responseHeaders.match(/(X-Reqid\:\ )([\w\.\%-]*)/) : [];
                        var req_id = matchedGroups[2];

**Comment by Novia-liang** [comment]
qiuniu.js:1515
var req_id = info.responseHeaders.match(/(x-reqid\:\ )([\w\.\%-]*)/)[2];
chrmone貌似x-reqid是小写

**Comment by GuGaobai1994** [comment]
收到，感谢

**Comment by devrsi0n** [comment]
@GuGaobai1994 我也遇到这个问题了，第二次上传就不行了。难道要每次上传完都重新初始化uploader？

**Comment by GuGaobai1994** [comment]
http://demo.gugaobai.top/scripts/qiniu.js 用新版试一下

**Comment by devrsi0n** [comment]
@GuGaobai1994 试了下，仍然报这个错

**Comment by GuGaobai1994** [comment]
![image](https://user-images.githubusercontent.com/20764006/29118562-0758111c-7d35-11e7-84da-e899d26898bb.png)
初始化时指定disable_statistics_report: true,

**Comment by GuGaobai1994** [comment]
使用http://demo.gugaobai.top/scripts/qiniu.js?v=1231 替换旧版本

**Comment by devrsi0n** [comment]
@GuGaobai1994 统计的正则表达式在IE下面还是有问题，删掉以后就好了。多谢～

**Comment by cage1618** [comment]
同样的问题，设置了 disable_statistics_report 为 true 只是没有把错误打出来，上传还是不成功
