### ISSUE TITLE
配置downtoken_url了，FileUploaded返回的info信息不对

### ISSUE THREAD

**Issue by y284663247** [qiniu/js-sdk#253]
配置downtoken_url 
现在不确定FileUploaded这个方法是在ajax请求了downtoken_url 之前还是之后，为什么FileUploaded参数的info会不一样，有时候返回的key,domain，还有时候返回的是ctx等信息

**Comment by y284663247** [comment]
如果把FileUploaded放到init里面可以，但是
`
uploader.bind('FileUploaded', function (up, file, info) {
        console.log(info);
        var res = $.parseJSON(info.response);
        console.log(res);
        var filen = file.name.split('.');
        filen[filen.length - 1] = '';
        var id = $(up.getOption().browse_button[0]).attr('id');
        $('.' + id + 'process').css('width', '0');
//        $('#'+video.browse_button).attr('disabled',false);
        $('#file_id').val(res.fileid);
        $('.' + id).find('a').html('重新上传');
    })
`
这样就不可以

**Comment by GuGaobai1994** [comment]
大文件会使用分片上传，分片上传的返回信息是ctx. 实现逻辑参考
   uploader.bind('FileUploaded', (function (_FileUploaded_Handler) {
                return function (up, file, info) {
                    logger.debug("FileUploaded event activated");
                    logger.debug("FileUploaded file: ", file);
                    logger.debug("FileUploaded info: ", info);
                    var nowTime = new Date();
                    var last_step = function (up, file, info) {
                        logger.debug("FileUploaded last step:", info);
                        if (op.downtoken_url) {
                            // if op.dowontoken_url is not empty
                            // need get downtoken before invoke the _FileUploaded_Handler
                            var ajax_downtoken = that.createAjax();
                            ajax_downtoken.open('POST', op.downtoken_url, true);
                            ajax_downtoken.setRequestHeader('Content-type', 'application/x-www-form-urlencoded');
                            ajax_downtoken.onreadystatechange = function () {
                                if (ajax_downtoken.readyState === 4) {
                                    if (ajax_downtoken.status === 200) {
                                        var res_downtoken;
                                        try {
                                            res_downtoken = that.parseJSON(ajax_downtoken.responseText);
                                        } catch (e) {
                                            throw ('invalid json format');
                                        }
                                        var info_extended = {};
                                        plupload.extend(info_extended, that.parseJSON(info.response), res_downtoken);
                                        info.response = that.stringifyJSON(info_extended);
                                        if (_FileUploaded_Handler) {
                                            _FileUploaded_Handler(up, file, info);
                                        }
                                    } else {
                                        uploader.trigger('Error', {
                                            status: ajax_downtoken.status,
                                            response: ajax_downtoken.responseText,
                                            file: file,
                                            code: plupload.HTTP_ERROR
                                        });
                                    }
                                }
                            };
                            ajax_downtoken.send('key=' + that.parseJSON(info.response).key + '&domain=' + op.domain);

**Comment by y284663247** [comment]
分片大小设置为2mb,上传个3.4mb的文件，最后报错了
{"error":"block 0: unexpected block size 2097152"}

**Comment by GuGaobai1994** [comment]
分片大小只能为0 关闭分片或者设为4MB
