### ISSUE TITLE
上传完成之后

### ISSUE THREAD

**Issue by NormanZhang** [qiniu/js-sdk#255]
https://github.com/qiniu/js-sdk/blob/d8b1a5815251103f3df851e6444d5ed163b447d1/src/qiniu.js#L1514

Uncaught TypeError: Cannot read property '2' of null
    at o.Uploader.<anonymous> (qiniu.js?v=1502331960478:1514)
    at o.Uploader.dispatchEvent (plupload.full.min.js?v=1502331960478:29)
    at o.Uploader.trigger (plupload.full.min.js?v=1502331960478:13)
    at f.m.onload (plupload.full.min.js?v=1502331960478:29)
    at f.<anonymous> (plupload.full.min.js?v=1502331960478:13)
    at Array.<anonymous> (plupload.full.min.js?v=1502331960478:13)
    at i (plupload.full.min.js?v=1502331960478:13)
    at Object.r [as inSeries] (plupload.full.min.js?v=1502331960478:13)
    at f.dispatchEvent (plupload.full.min.js?v=1502331960478:13)
    at i.<anonymous> (plupload.full.min.js?v=1502331960478:14)

我调试时：
 var req_id = info.responseHeaders.match(/(X-Reqid\:\ )([\w\.\%-]*)/)[2];
info.responseHeaders=
"pragma: no-cache
x-reqid: fgkAAEzhxiUiW9kU, fgkAAEzhxiUiW9kU
x-log: RA:14.152.37.4:80;body:2;s.ph;s.put.tw;s.put.tr:1;s.put.tw;s.put.tr;s.ph;PFDS:1;PFDS:1;rs4_4.sel/not found;rdb.g/no such key;DBD/404;v4.get/Document not found;rs4_4.ins;rwro.ins:1;mc.s/500;mc.d/404;mc.d/404;RS:2;rs.put:2;rs-upload.putFile:5;UP:11;NUPROXY:48
content-type: application/json
cache-control: no-store, no-cache, must-revalidate
"

**Comment by GuGaobai1994** [comment]
var uploader = Qiniu.uploader({
        disable_statistics_report: true,
        ..........
}
初始化时禁止report即可

**Comment by NormanZhang** [comment]
还有一个问题，我想请教一下，并不是JavaScript模块的问题：

persistentOps中如何加入force字段：

String accessKey = "access key";
String secretKey = "secret key";
String bucket = "bucket name";
Auth auth = Auth.create(accessKey, secretKey);
StringMap putPolicy = new StringMap();
//数据处理指令，支持多个指令
String saveMp4Entry = String.format("%s:avthumb_test_target.mp4", bucket);
String saveJpgEntry = String.format("%s:vframe_test_target.jpg", bucket);
String avthumbMp4Fop = String.format("avthumb/mp4|saveas/%s", UrlSafeBase64.encodeToString(saveMp4Entry));
String vframeJpgFop = String.format("vframe/jpg/offset/1|saveas/%s", UrlSafeBase64.encodeToString(saveJpgEntry));
//将多个数据处理指令拼接起来
String persistentOpfs = StringUtils.join(new String[]{
        avthumbMp4Fop, vframeJpgFop
}, ";");
putPolicy.put("persistentOps", persistentOpfs);
//数据处理队列名称，必填
putPolicy.put("persistentPipeline", "mps-pipe1");
//数据处理完成结果通知地址
putPolicy.put("persistentNotifyUrl", "http://api.example.com/qiniu/pfop/notify");
long expireSeconds = 3600;
String upToken = auth.uploadToken(bucket, null, expireSeconds, putPolicy);
System.out.println(upToken);

其中另存为的文件名avthumb_test_target.mp4是定死的，
如果不加入force字段，那么在不重新刷新，请求upToken的情况下，会重复存到avthumb_test_target.mp4这个地址，但又不会替换原来的文件。
请问怎么解决

**Comment by GuGaobai1994** [comment]
StringMap params = new StringMap().putWhen("force", 1, true).putNotEmpty("pipeline", pipeline);
