### ISSUE TITLE
页面里存在一个以上实例，uptoken_url参数竟然会被覆盖

### ISSUE THREAD

**Issue by kagadorapeko** [qiniu/js-sdk#260]
Qiniu.uploader({
    // 省略其他参数
    browse_button: 'upload-image',
    uptoken_url: 'https://www.xxx.com/image'
});

Qiniu.uploader({
    // 省略其他参数
    browse_button: 'upload-audio',
    uptoken_url: 'https://www.xxx.com/audio'
});

Qiniu.uploader({
    // 省略其他参数
    browse_button: 'upload-video',
    uptoken_url: 'https://www.xxx.com/video'
});

结果三个实例请求uptoken的url竟然都是https://www.xxx.com/video

**Comment by GuGaobai1994** [comment]
您好，需要新建一个实例
参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
![image](https://user-images.githubusercontent.com/20764006/29443551-887592d8-840b-11e7-9b0a-4239702f2143.png)

**Comment by forrest-mao** [comment]
目前 3.x 的 SDK 中可以直接给 qiniu.upload 中的 token 字段写入上传凭证字符串即可，不用通过 uptoken url 来获取，获取 token 的方式可以自定义，这样就可以每次上传的时候使用不同的 token 来上传了。
