### ISSUE TITLE
分片上传导致UploadProgress的file.status无法正确获取

### ISSUE THREAD

**Issue by l3ve** [qiniu/js-sdk#264]
感觉是时间点问题，调用stop()的时候，如果分片还在上传，是否会导致先暂停，而在分片上传结束后并不会触发UploadProgress？

**Comment by GuGaobai1994** [comment]
您好，分片上传可以使用chunk_size来确定上传进度

**Comment by GuGaobai1994** [comment]
var chunk_size = plupload.parseSize(this.getOption('chunk_size'));

**Comment by taoqf** [comment]
`UploadProgress`和`ChunkUploaded`我都无法获取文件的上传进度以及百分比会是什么原因，我上传的文件大小约20兆，分片大小使用默认的4兆，有回调，但speed和percent都没变化，percent一直是100,speed也不变。@GuGaobai1994

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-966

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。

**Comment by taoqf** [comment]
新版本这问题修复了吗？还是说需要我自己去试？

**Comment by yinxulai** [comment]
> 新版本这问题修复了吗？还是说需要我自己去试？

感谢关注，如果该用例依然存在，升级新版本后依然存在该问题，推荐重新创建 issue，我们将会立即关注并开始处理。@taoqf
如果有需要我们也可以重新开启这个 issue
