### ISSUE TITLE
UploadComplete 只是队列处理完成，文件还没真正的上传完成就被调用了。

### ISSUE THREAD

**Issue by sdandroid** [qiniu/js-sdk#265]
有没有，文件都上传完成的回调？

**Comment by GuGaobai1994** [comment]
您好，可以试一下 FileUploaded

**Comment by GuGaobai1994** [comment]
根据您的需求可以UploadComplete在处理就可以了，如果文件上传失败会走error
 'Error': function(up, err, errTip) {
                 //上传出错时，处理相关的事情
          },

**Comment by sdandroid** [comment]
不是这个意思，如果文件过大，走了分片上传的话，会先回调 UploadComplete，只有 qiniu 后台回调成功后，FileUploaded 才会被调用，有没有一个队列里面 都收到 后台返回值后的，一个事件？

**Comment by dtdths** [comment]
我也遇到这个问题了，请问怎么处理，急！！！！！！！！！！

**Comment by sdandroid** [comment]
@dtdths 现在是在 FileUploaded 里面判断是不是都上传完了。比较麻烦。

**Comment by dtdths** [comment]
@sdandroid 我是在vue里上传大文件时碰到的，现在用的是vue里的watch监听，也好麻烦-_-|||
