### ISSUE TITLE
多个uploader同时start

### ISSUE THREAD

**Issue by largetalk** [qiniu/js-sdk#272]
请问我能在一个页面new多个uploader，并且同时start吗，文件大小小于4mb时好像是可以成功，但是文件大于4mb的时候会报413 Request Entity Too Large错误。

**Comment by GuGaobai1994** [comment]
您好，可以通过callback来实现，但是效率很低，建议当一个uploader执行时，将下一个置为等待

**Comment by largetalk** [comment]
好的，多谢 @GuGaobai1994
