### ISSUE TITLE
选择多张图片时，每张图片上传之前都要重新获取uptoken？

### ISSUE THREAD

**Issue by zenghongcong** [qiniu/js-sdk#278]
在uptoken_func里面获取然后返回，但是并没有改变uptoken的值。

然后又尝试了在每个文件上传时把uptoken setOption 进去，也不行。

不知道是不是我的配置写得不对呢？

**Comment by GuGaobai1994** [comment]
需要将get_new_uptoken设置为true

**Comment by GuGaobai1994** [comment]
var uploader = Qiniu.uploader(
        options);
    uploader.bind('FilesAdded', function() {
        options.uptoken = "FMVCRs2-LO1ivRNi4l7mEZE6ZDvPv-519D12kZCO:Tr_BQ2wcCLhaqA9B8bzUuIkN2Q8=:eyJzY29wZSI6InRlc3QiLCJkZWFkbGluZSI6MjUwNDA5OTQ0N30=";
        uploader = Qiniu.uploader(
            options);
        console.log("hello man, a file added");
    });

**Comment by zenghongcong** [comment]
是我配置写得不对，已经解决了。谢谢啦。
