### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by yursile** [qiniu/js-sdk#285]
亲，我是唯一一个报require错的吗
npm install bowerinstall 后 npm start打开index.html就报错了
难道要手动引require.js？

求支援呀

**Comment by GuGaobai1994** [comment]
您好，请问您是怎么引入的？可以参考 https://developer.qiniu.com/kodo/sdk/4033/the-introduction-of-the-js-sdk-method

**Comment by yursile** [comment]
我是直接跑的这个demo，没有改任何代码，我觉得可能是依赖包版本的问题，你们试试把bower和npm的包删掉再跑一下呢

**Comment by GuGaobai1994** [comment]
运行示例参考
https://github.com/qiniu/js-sdk/?ref=developer.qiniu.com#demo
![image](https://user-images.githubusercontent.com/20764006/30843997-448f06ca-a252-11e7-83e9-3a089cb31ac9.png)

**Comment by yursile** [comment]
确实是按照这个步骤跑的，打开http://127.0.0.1:19110后控制台就报这个错
你能试试拉最新的代码，按照这个步骤跑一次吗

万分感谢呀

`qiniu.js:69 Uncaught ReferenceError: require is not defined
    at new QiniuJsSDK (qiniu.js:69)
    at qiniu.js:1830
    at qiniu.js:1844
main.js:7 Uncaught ReferenceError: Qiniu is not defined
    at HTMLDocument.<anonymous> (main.js:7)
    at c (jquery.min.js:3)
    at Object.fireWith [as resolveWith] (jquery.min.js:3)
    at Function.ready (jquery.min.js:3)
    at HTMLDocument.H (jquery.min.js:3)`

**Comment by yursile** [comment]
![d122512f-c3b8-438a-b857-b94d49223691](https://user-images.githubusercontent.com/8502944/30847600-ad618ce6-a2ce-11e7-9c5a-3c6897b7e7c5.png)

**Comment by GuGaobai1994** [comment]
嗯，要改两个地方,我提个pr
1. sever.js
![image](https://user-images.githubusercontent.com/20764006/30852397-426616a8-a271-11e7-87ff-999457c480da.png)
app.use('/dist', express.static(__dirname + '/../dist'));

2. index.html
![image](https://user-images.githubusercontent.com/20764006/30852545-b9fb4472-a271-11e7-9cd3-c5512cdb49f1.png)
<script type="text/javascript" src="dist/qiniu.min.js"></script>

**Comment by yursile** [comment]
THX!
