### ISSUE TITLE
incorrect region, please use up-z2.qiniu.com

### ISSUE THREAD

**Issue by kimown** [qiniu/js-sdk#290]
官方demo, Formdata 上传 demo, 输入key后上传报上面错误

```
{"error":"incorrect region, please use up-z2.qiniu.com"}
```

请问如何解决

看到类似的问题是去年的，https://github.com/qiniu/js-sdk/issues/176

**Comment by kimown** [comment]
https://github.com/qiniu/js-sdk/blob/master/demo/scripts/formdata.js#L24

问题已找到

**Comment by tammybi** [comment]
链接404 ......
