### ISSUE TITLE
require is not defined

### ISSUE THREAD

**Issue by Rockroc** [qiniu/js-sdk#291]
git clone 下来的文件，分别引进了moxie.js、plupload.dev.js、qiniu.js，
执行时候报require is not defined

qiniu.js:69 Uncaught ReferenceError: require is not defined
    at new QiniuJsSDK (qiniu.js:69)
    at qiniu.js:1841
    at qiniu.js:1855

**Comment by GuGaobai1994** [comment]
您好，这个是基于webpack构建的，直接使用dist目录下的js就可以了
