### ISSUE TITLE
在IOS系统下上传文件，文件名为id+文件后缀

### ISSUE THREAD

**Issue by commitqdy** [qiniu/js-sdk#292]
引入js-sdk进行操作，在安卓端上传文件名与本地文件名一致，在IOS浏览器上上传文件名为id+文件后缀。是需要设置什么参数吗？还是设计如此？

**Comment by GuGaobai1994** [comment]
是什么版本的ios？用http://jssdk.demo.qiniu.io/ 这个也是这样吗

**Comment by commitqdy** [comment]
好像跟版本没关系，你用谷歌浏览器打开这个地址，打开开发者模式，模拟iPhone6上传就可以看到了
![2017-10-20_135206](https://user-images.githubusercontent.com/24648359/31807040-50d76e5e-b59e-11e7-8138-1693afd6475f.png)

**Comment by GuGaobai1994** [comment]
我目前没有找到iphone6 的实体机器，用6s是正常的。应该是unique_name的配置没有生效，所以使用plupload生成的随机文件名

**Comment by GuGaobai1994** [comment]
可以强制unique_name为flase试下

**Comment by commitqdy** [comment]
unique_name为flase也不行，不需要实体机器，你用chrome浏览器在上传页面右击检查，然后打开点击Toggle device toolbar就可以了
![2017-10-21_090037](https://user-images.githubusercontent.com/24648359/31846492-195ed2ea-b63f-11e7-9a83-70a427404d54.png)

**Comment by GuGaobai1994** [comment]
![image](https://user-images.githubusercontent.com/20764006/31847114-d1c0ce84-b648-11e7-80a7-b6d2fdeab78c.png)
没有复现额，是否有详细步骤

**Comment by commitqdy** [comment]
你进入到iPhone6模式后，刷新一下页面，再上传

**Comment by GuGaobai1994** [comment]
可以复现了，感谢

**Comment by GuGaobai1994** [comment]
应该是chrome带的ua

**Comment by GuGaobai1994** [comment]
![image](https://user-images.githubusercontent.com/20764006/31920417-612bc39e-b82e-11e7-9bf6-9082691db093.png)

**Comment by commitqdy** [comment]
找到问题了吗？

**Comment by GuGaobai1994** [comment]
是plupload的问题，会自动生成一个随机值作为文件名，可以在代码里手动获取下文件名，指定为上传的Key. 或者直接用不指定文件名，用hash值作为文件名可以是一个好办法

**Comment by commitqdy** [comment]
嗯嗯，好的，我试试，谢啦
