### ISSUE TITLE
android webview 使用七牛上传组件，不能打开上传文件弹出框

### ISSUE THREAD

**Issue by MatchLemon** [qiniu/js-sdk#293]
1 以前可以使用。现在为什么不可以使用了。

**Comment by GuGaobai1994** [comment]
是否有更新版本？
参考https://developer.qiniu.com/kodo/sdk/1283/javascript
![image](https://user-images.githubusercontent.com/20764006/32254554-74f5a9a2-be6f-11e7-9868-5fabadc37f00.png)

**Comment by MatchLemon** [comment]
android 需要写代码支持 type='file'
