### ISSUE TITLE
除了图片什么都不能上传的限制，无法解决

### ISSUE THREAD

**Issue by 1094549944** [qiniu/js-sdk#295]
使用七牛的上传文件功能，要求是只上传图片，限制其他的格式上传，写的代码是：
'FilesAdded': function(up, files) { // 文件添加进队列后，处理相关的事情
                        plupload.each(files, function(file) {
                            if (file.type == 'image/jpeg' || file.type == 'image/jpg' || file.type == 'image/png' || file.type == 'image/bmp' || file.type == 'image/tiff' || file.type == 'image/jpeg') {
                                console.log('type:' + file.type);
                                isUpload = true;
                            } else {
                                isUpload = false;
                                up.removeFile(file);
                                base.toast('暂不支持视频、GIF格式文件上传');
                                return false;
                            }
                        });

                    },

上传图片可以通过，一旦上传其他格式，比如mp4,在控制台报
qiniu.js:1540 Uncaught TypeError: Cannot read property 'getTime' of undefined

不知道怎么解决。

**Comment by GuGaobai1994** [comment]
是否有外网可以访问的地址

**Comment by 1094549944** [comment]
在iphone6s手机上，上传图片，在UploadProgress这个函数中，有的图片，会卡在中途不动，无法上传

**Comment by 1094549944** [comment]
我提了工单。

**Comment by 1094549944** [comment]
在七牛官方提供的demo中，上传了一张图片，也存在个问题。
问题描述：
在iphone6s中，使用safari浏览器，上传图片，就会卡，无法上传。

**Comment by GuGaobai1994** [comment]
麻烦工单号给下
