### ISSUE TITLE
官方在线的demo在IE9下无法上传成功

### ISSUE THREAD

**Issue by Koreyhan** [qiniu/js-sdk#298]
Runtime 'html5' failed to initialize
Runtime 'flash' failed to initialize
Runtime 'html4' failed to initialize

三种模式都初始化失败了

**Comment by Koreyhan** [comment]
[qiniu-js-sdk][error] err:  {"code":-200,"message":"HTTP Error.","file":{"id":"o_1bus9pqf1eofd7erg76j1ntkn","name":"avatar1.jpg","type":"image/jpeg","loaded":0,"percent":0,"status":2,"lastModifiedDate":"2017年11月14日 11:40:12","completeTimestamp":0,"_start_at":"2017-11-14T03:40:12.228Z","speed":0},"response":"","status":0,"responseHeaders":""}

**Comment by GuGaobai1994** [comment]
直接用flash模式

**Comment by old-bin** [comment]
IE8 在 flash 下会报错，IE9在 html4  下也会报错，这两个版本的IE 都没法使用上 第一版的 上传，而第二版的又不支持 IE8、9了，真是没法用了，官方 demo 都不去 测 flash/html4 上传方式？
