### ISSUE TITLE
上传成功后传值到vue

### ISSUE THREAD

**Issue by chinahxf** [qiniu/js-sdk#300]
vue 页面中的mounted，写了调用this.upImg();
Vue.prototype.upImg = function (){
            var Q2=new QiniuJsSDK()
            // 创建上传对象
            var uploader = Q2.uploader({
                    'FileUploaded': function(up, file, info) {
                        var sourceLink = domain + res.key; //获取上传成功后的文件的Url
                        this.form_data.thumb_img=sourceLink;
                    },
                }
  ，上传成功后如何把url绑定到页面,

 export default {
        data() {
            return {
                form_data: {
                    thumb_img:''
                },

,直接this.form_data.thumb_img,会报Cannot set property 'thumb_img' of undefined，应该如何把url绑定到vue页面？有什么好的方法？this的指向问题吗？求大佬们指点一下，本人主要做后端的，前段不太懂

**Comment by chinahxf** [comment]
我通过dom元素可以传过去，不过感觉有点别扭，有没有什么直接的方法，可以直接绑定到vue？

**Comment by GuGaobai1994** [comment]
component

**Comment by chinahxf** [comment]
我定义了全局的js，想把全局的js方法获得到的数据传递给具体调用这个方法的vue页面，可否详细告知一下，查资料查到是全局注册，并没有找到好的方法解决这个问题

**Comment by chinahxf** [comment]
已解决，通过在 
Vue.prototype.upImg = function (){
        **_this=this;**
            var Q2=new QiniuJsSDK()

 _this.form_data.thumb_img=sourceLink;

可能是this的指向问题吧
