### ISSUE TITLE
使用resize压缩大图片的时候就挂了

### ISSUE THREAD

**Issue by ZH4L** [qiniu/js-sdk#304]
现在照片越来越大了，动不动就5，6M，上传起来太慢了，所以看了下plupload的文档，发现有个resize参数可以上传前压缩图片，但是图片小还好，图片一大，就挂掉了，上传不了了

**Comment by GuGaobai1994** [comment]
看下plupload的版本

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-967

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
