### ISSUE TITLE
qiniu  jssdk 前端上传视频

### ISSUE THREAD

**Issue by YSH20110105** [qiniu/js-sdk#307]
http://test.aimeichuang.com/qiniu/index2.html

添加 filters : {

        max_file_size : '100mb',

        prevent_duplicates: true,

        // Specify what files to browse for

        mime_types: [

           /* {title : "flv files", extensions : "flv"}, // 限定flv后缀上传格式上传*/

            {title : "Video files", extensions : "mp4"} // 限定flv,mpg,mpeg,avi,wmv,mov,asf,rm,rmvb,mkv,m4v,mp4后缀格式上传

            /*{title : "Image files", extensions : "jpg,gif,png"}, // 限定jpg,gif,png后缀上传

            {title : "Zip files", extensions : "zip"} // 限定zip后缀上传*/

        ],

    },

能限制视频类型 1.但安卓微信浏览器打开选择文件时显示  没有应用可执行此操作   ；2.手机qq浏览器上传后点击上传链接只能下载 不能在线看

如果把filters去掉就好了  但不能现在文件类型

**Comment by GuGaobai1994** [comment]
这样写就可以绕过去了

**Comment by YSH20110105** [comment]
谢谢 非常感谢
