### ISSUE TITLE
1.0.23版本import路径有误

### ISSUE THREAD

**Issue by chenli1989** [qiniu/js-sdk#309]
import 'qiniu-js' 报错

dist目录下只有qiniu.min.js
而package.json里的路径是这样，
![image](https://user-images.githubusercontent.com/8178749/34205855-054b51ac-e5bf-11e7-8d26-f654da15cc56.png)

**Comment by hu-zhi-hang** [comment]
+1 😔

**Comment by chenli1989** [comment]
version 1.0.24已修复
