### ISSUE TITLE
addFile 问题

### ISSUE THREAD

**Issue by w550** [qiniu/js-sdk#312]
类似 这个 https://github.com/qiniu/js-sdk/issues/56

具体错误实现及解决办法
```
var uploader =  Qiniu.uploader({ ... })
uploader.addFile(File) // 添加一个 blob转换成的 File 文件。
```
这个时候查看uploader.files = []
没有添加成功
换个写法
```
var uploader =  Qiniu.uploader({ ... })
setTimeout(()=>{
    uploader.addFile(File) // 添加一个 blob转换成的 File 文件。
},400)
```
这个时候查看uploader.files.length  = 1
添加成功
为什么延迟一会会就能添加成功？

**Comment by w550** [comment]
版本都是最新版

**Comment by GuGaobai1994** [comment]
console里有啥提示吗

**Comment by w550** [comment]
@GuGaobai1994
没有提示，也没有错误。

**Comment by w550** [comment]
官网文档
https://github.com/moxiecode/plupload/wiki/Uploader#addFile-method-filefileName

init 里面还有一个init 事件。可以写在里面。

**Comment by lihualingMiss** [comment]
请问最后怎么解决的

**Comment by lihualingMiss** [comment]
设置了延迟也不起效

**Comment by WangJi** [comment]
试了好几种办法，目前只能用Init事件来加，这个可以成功。   
从 `const uploader = Qiniu.uploader()` 获取实例，再调用 `uploader.addFile` 方法不起作用，但两个`uploader` 的实例确是一致，非常诡异。
```javascript
Qiniu.uploader({
 //...options
 init: {
     Init(uploader) {
         uploader.addFile(file); 
     },
})
```
