### ISSUE TITLE
Is there any CDN could I use?

### ISSUE THREAD

**Issue by taoqf** [qiniu/js-sdk#319]
I wish I could find the latest version in http://staticfile.org/ , but only find 1.0.14-beta , any idea?

**Comment by jcyrss** [comment]
同问这个问题， 为什么七牛的公告前端cdn库 只到 1.10.14-beta?

**Comment by taoqf** [comment]
七牛这破玩意儿现在根本没人维护了，在七牛网站上提交工单倒是有人回，上周就说安排人处理这些事情，到现在也没人处理。

**Comment by taoqf** [comment]
估计是原来维护这东西的人辞职不干了，新招的人不会玩。

**Comment by jcyrss** [comment]
哎， 看来还得自己研究。

**Comment by winddies** [comment]
@taoqf @jcyrss 目前js-sdk更新到2.x版本，不再依赖plupload了，后续会更新cdn库

**Comment by taoqf** [comment]
终于本家来人了

**Comment by taoqf** [comment]
https://github.com/qiniu/js-sdk/pull/316
能合并吗？

**Comment by taoqf** [comment]
对啦，cdn问题我找到了一个解决办法，但不知道适合不适合你们用。至少可以减少一些七牛开发人员的工作负担
```html
<script src="https://unpkg.com/qiniu-js/dist/qiniu.min.js"></script>
```

**Comment by taoqf** [comment]
https://github.com/qiniu/js-sdk/pull/316/commits/6a6c9d6e0a2f50d0b5aa796019c39ec4ca36bd33
特别是这个，这是一个bug
