### ISSUE TITLE
选择重复文件

### ISSUE THREAD

**Issue by protectyourcode** [qiniu/js-sdk#320]
`filters: {
          prevent_duplicates: true // 不允许选取重复文件
 }`
qiniu.js 中并未对 plupload.FILE_DUPLICATE_ERROR 错误码进行处理，
而是当成未知错误处理：unknow_error_retry...
导致第二次选择重复文件直接上传

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-968

**Comment by ChinaPoger** [comment]
[qiniu-js-sdk][error] err:  message: "Duplicate file error."
目前console报错信息是有的，错误信息也比较明确

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
