### ISSUE TITLE
用promise写的获取token方法不能用

### ISSUE THREAD

**Issue by commitqdy** [qiniu/js-sdk#321]
`uptoken_func: function(file){
     _this.getUploadtoken(file).then(function(data){
          return data;
     })
 }, `
token一直获取不到，是不是不正常用promise去获取token呢？

**Comment by GuGaobai1994** [comment]
这个地方不需要promise吧

**Comment by commitqdy** [comment]
本来想在这个函数里获取token的，好像获取不到，现在把auto_start改为false,在FilesAdded里用promise获取每个文件的token之后再开始上传，已经解决异步获取不到token的问题了

**Comment by taoqf** [comment]
它这个库很多东西不支持异步的我一开始也觉得就应该支持异步的，但看源码发现根本没这方面的实现。凑合用吧，它这个东西基本没人维护了。
