### ISSUE TITLE
七牛web客户端js库不支持新版本的plupload 库, 最多支持到2.1.9

### ISSUE THREAD

**Issue by jcyrss** [qiniu/js-sdk#322]
plupload库在2.2.X 以后的版本里面对上传图片的质量做了很大的优化，

参考

https://github.com/moxiecode/plupload/issues/707

但是目前的七牛web客户端js库好像不支持新版本的plupload 库。最多支持到2.1.9

我用的是你们 公共前端库 开发cdn 里面的sdk。 就是下面的地址
https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.min.js

**Comment by GuGaobai1994** [comment]
看下最新的吧，是根据2.3.1做的
![image](https://user-images.githubusercontent.com/20764006/35615269-9f4e85ae-06ac-11e8-94c0-5666e28050f0.png)

**Comment by jcyrss** [comment]
但是你们  公共前端库 cdn 里面的sdk 里面只到 1.0.14 啊
https://cdn.staticfile.org/qiniu-js-sdk/1.0.14-beta/qiniu.min.js
