### ISSUE TITLE
matchedGroups 没有判断是空数组的情况

### ISSUE THREAD

**Issue by old-bin** [qiniu/js-sdk#323]
https://github.com/qiniu/js-sdk/blob/2576d4a5fe1dd1d8f4a113fa406de5e8483da892/src/qiniu.js#L1373

当matchedGroups 为[] 的时候 matchedGroups[2] 是 undefined, 自然也没有 replace 方法了

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-969

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
