### ISSUE TITLE
分片上传 701 错误

### ISSUE THREAD

**Issue by yyleocn** [qiniu/js-sdk#336]
js-sdk中给出了 demo1 和 demo2 两个例子，但是配置后均无法运行
其中demo2报错如下：
`GET http://localhost:8000/api/uptoken 500 (Internal Server Error)`

参考 demo2 自己写了一下上传代码，如下：
```
fileUpload(file_) {
            let next = (response_) => {
                console.log(response_.total.percent);
            };
            console.log(file_);
            let config = {
                useCdnDomain: true,
                region: qiniu.region.z2
            };
            let putExtra = {
                fname: "",
                params: {},
                mimeType: null
            };
            let observable = qiniu.upload(
                file_,
                file_.name,
                token_,
                putExtra,
                config
            );
            observable.subscribe(next);
        }
```
测试发现问题
上传小文件一切正常，上传超过4M的文件后会返回 701 错误，内容如下：
`{"error":"block 0: invalid context"}`

出错 request 的截图
![_20180228212809](https://user-images.githubusercontent.com/8280724/36790009-5afefcac-1cce-11e8-9853-fe27b7a24550.png)

**Comment by winddies** [comment]
@yyleocn  701问题已解决，至于demo，我本地测了一下是没问题的，不知道你这边环境是什么样的？

**Comment by winddies** [comment]
[2.1.1版本](https://github.com/qiniu/js-sdk/releases/tag/v2.1.1)已经解决这个问题 @yyleocn
