### ISSUE TITLE
最新版本七牛有个bug

### ISSUE THREAD

**Issue by ningmengs** [qiniu/js-sdk#339]
七牛SDK里面把mimeType写成了mimeTyp，漏了个e
![image](https://user-images.githubusercontent.com/21259884/36830746-eb8d83c4-1d5f-11e8-96df-6f9c9961a766.png)

**Comment by ningmengs** [comment]
var putExtra = {
      fname: "",
      params: {},
      mimeType:["image/png"]
    };
当mimeType为数组的时候，会报错，如果填了null就不会

**Comment by winddies** [comment]
这个问题在版本[2.1.2](https://github.com/qiniu/js-sdk/releases/tag/v2.1.2)已解决， @ningmengs
