### ISSUE TITLE
选择单文件时FileUploaded 重复调用

### ISSUE THREAD

**Issue by sunshinebaby00** [qiniu/js-sdk#341]
设置了multi_selection: false 选择单文件上传的时候，init中的属性FileUploaded调用一次，但是下面的方式会重复调用多次
```
uploader.bind('FileUploaded', function(up, file, info) {
                            console.log("上传完成"+file.name);
                            var domain = up.getOption('domain');
                            var res = JSON.parse(info.response);
                            var sourceLink = domain + res.key; //获取上传成功后的文件的Url
 })
```
日志截图
![image](https://user-images.githubusercontent.com/9410296/36881118-68e701a4-1e07-11e8-80b6-191b1ce4a79e.png)

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript

新版本的 SDK 如果希望只选择单文件只需要控制 button 组件去掉 multiple 属性即可

**Comment by forrest-mao** [comment]
1.x 版本的 SDK 可以参考文档 https://developer.qiniu.com/kodo/sdk/4244/the-javascript-sdk-historical-documents-1-x#5 中的【11. 关于多个按钮选择文件的 Demo】
