### ISSUE TITLE
找遍了所有文档就是没找到2.X版本的cdn加速链接

### ISSUE THREAD

**Issue by FWiner** [qiniu/js-sdk#344]
求一个，只找到3个1.X的很老版本的cdn链接

**Comment by winddies** [comment]
抱歉，cdn链接目前有点问题，会在近期解决掉 @a81584944

**Comment by winddies** [comment]
可以先用这个静态地址 [sdk](https://unpkg.com/qiniu-js@2.1.2/dist/qiniu.min.js) @a81584944

**Comment by a81584944** [comment]
@winddies 好的 谢谢

**Comment by EagleWolf** [comment]
@winddies 5个月过去，还没有cdn加速啊?
