### ISSUE TITLE
js-sdk  domain如何设置，qiniu.js源码可以直接提供吗？

### ISSUE THREAD

**Issue by lihua123569** [qiniu/js-sdk#348]
var observable = qiniu.upload(file, key, token, putExtra, config)
var subscription = observable.subscribe(observer) // 上传开始
// or
var subscription = observable.subscribe(next, error, complete) // 这样传参形式也可以
subscription.unsubscribe() // 上传取消
 这里没看到domain如何设置

**Comment by winddies** [comment]
domain通过后端接口得到，在README里有提到，可以先阅读下readme里关于运行示例的内容，参考demo中的例子 @lihua123569

**Comment by lihua123569** [comment]
下面是最新代码的demo1案例，下面是main.js  imageControl，这个方法是处理domain的，但是在qiniu.mini.js里面没有看到这个方法，其他文件也没看到，理解不了
$.ajax({url: "/api/uptoken", success: function(res){
    var token = res.uptoken;
    var domain = res.domain;
    var config = {
      useCdnDomain: true,
      disableStatisticsReport: false,
      region: qiniu.region.z2
    };
    var putExtra = {
      fname: "",
      params: {},
      mimeType: null
    };
    $(".nav-box")
      .find("a")
      .each(function(index) {
        $(this).on("click", function(e) {
          switch (e.target.name) {
            case "h5":
              uploadWithSDK(token, putExtra, config, domain);
              break;
            case "expand":
              uploadWithOthers(token, putExtra, config, domain);
              break;
            case "directForm":
              uploadWithForm(token, putExtra, config);
              break;
            default:
              "";
          }
        });
      });
    imageControl(domain);
    uploadWithSDK(token, putExtra, config, domain);
  }})

**Comment by winddies** [comment]
domain这个参数是图像处理用到的，通过请求后端拿到，如果只是上传，是用不到domain这个参数，这个参数在图像处理的方法中需要带上

**Comment by lihua123569** [comment]
换个我知道，我就想在上传后在页面直接显示，找不到这个方法在哪里写的，还有：私有空间图片的回显有案例，只看到公共空间的： var sourceLink = domain +"/"+ res.key; 获取上传成功后的文件的Url

**Comment by lihua123569** [comment]
有交流群吗？案例真心不够完善，文档也是，看的太费劲了，我换了1.x版本，js上传图片可以了,回显没看到有案例处理，文档也没看到合适的，java的下载到时有方法（已经测试可用了），但是js的没看到

**Comment by lihua123569** [comment]
domain这个在上传也用到了吧，不然上传到哪个空间怎么指定？

**Comment by winddies** [comment]
上传空间是后端配置的，麻烦你仔细看下README,这个配置跟1.x是一样的：
* “我换了1.x版本，js上传图片可以了” ：2.x版本无法上传文件吗？
* “我就想在上传后在页面直接显示，找不到这个方法在哪里写的“：如你所说，你要把上传后的图片在页面显示，这个方法跟sdk并没有关系，只是你上传文件后要做的操作，你可以通过拼接url

**Comment by winddies** [comment]
“domain这个在上传也用到了吧，不然上传到哪个空间怎么指定？"这个是后端配置的，麻烦你看下上传所需的参数。。。不需要domain

**Comment by winddies** [comment]
{
  "AccessKey": "<Your Access Key>",
  "SecretKey": "<Your Secret Key>",
  "Bucket": "<Your Bucket Name>",
  "Port": 9000,
  "UptokenUrl": "<Your Uptoken_Url>", // demo 启动后会在本地 /uptoken 上提供获取 uptoken 的接口，所以这里可以填 'token'
  "Domain": "<Your Bucket Domain>" // Bucket 的外链默认域名，在 Bucket 的内容管理里查看，如：'http://xxx.bkt.clouddn.com/'
}
demo中config.json.example是配置server的，server通过node sdk来提供客户端所需要的token,同时也可以根据读取config.json的配置信息提供domain,你前端拿到domain可以通过拼接url来得到上传成功的图片，这个操作不在sdk方法里，你所说的imageControl(domain)只是demo中关于图片所做的一些操作，只是用于demo本身的业务逻辑而已

**Comment by winddies** [comment]
var observable = qiniu.upload(file, key, token, putExtra, config)
var subscription = observable.subscribe(observer) // 上传开始
// or
var subscription = observable.subscribe(next, error, complete) // 这样传参形式也可以
subscription.unsubscribe() // 上传取消
这里没看到domain如何设置？
这个是上传文件的操作，跟domain一点关系没有，你想对上传后的图片进行图片处理，可以结合sdk提供的图像处理方法得到相应的url,如果你要获得下载图片的地址，可以通过后端node sdk的相应方法拿到，这个不在客户端sdk中,[下载凭证](https://developer.qiniu.com/kodo/manual/1202/download-token)

**Comment by winddies** [comment]
有些东西是后端sdk提供的方法，不在前端js-sdk中，后端可以给你一个接口用来拿下载地址，例如：
app.post("/downtoken", function(req, res) {
  var key = req.body.key;
  var domain = req.body.domain;

  //trim '/' if the domain's last char is '/'
  if (domain.lastIndexOf("/") === domain.length - 1) {
    domain = domain.substr(0, domain.length - 1);
  }

  var deadline = 3600 + Math.floor(Date.now() / 1000);
  var privateDownUrl = bucketManager.privateDownloadUrl(domain, key, deadline);
  res.json({
    url: privateDownUrl
  });
});

**Comment by winddies** [comment]
java-sdk是后端sdk,像node sdk也提供了下载方法，因为js-sdk属于客户端sdk,使用的时候是结合后端sdk一起的，像私有空间下载文件，在后端sdk会有提供，因为这里涉及到用户的安全信息，如果放在js-sdk会不安全

**Comment by lihua123569** [comment]
好吧，我以为是js直传七牛，然后百度了下，貌似私有空间没有提供上传后的显示图片地址（需要结合后台下载凭证处理）；再有个问题，2.x有qiniu.js 的源码吗，看到的都是大包的min.js，npm大包后还是没有qiniu.js，都是min.js

**Comment by winddies** [comment]
github上你可以clone下repo, src 目录下就是源码，。。。。
