### ISSUE TITLE
xhr request failed 但是 code 是 0 ；官方的错误文档没有这个

### ISSUE THREAD

**Issue by johnnycsy** [qiniu/js-sdk#352]
{"code":0,"message":"xhr request failed, code: 0;","reqId":"","isRequestError":true}

**Comment by winddies** [comment]
code为0 目前发现的是服务器内部错误报599的时候，请求状态码未识别599标记为0了，sdk有自动重试，对于未知错误会自动重试,

**Comment by A-Circle-Zhang** [comment]
用的什么浏览器呢，是不是火狐？

**Comment by Rem486** [comment]
请问这个问题怎么解决的呢？现在iphone x 图片上传的时候提示这个
