### ISSUE TITLE
低版本android浏览器中无法触发xhr progress事件导致上传报错

### ISSUE THREAD

**Issue by palm-civet** [qiniu/js-sdk#362]
报错信息：cannot read property 'total' of null
错误来源：https://github.com/qiniu/js-sdk/blob/master/src/upload.js#L272

设备型号：HUAWEI TIT-AL00
Android版本：5.1

错误分析：低版本android浏览器中无法触发xhr progress事件导致上传报错，可参考https://github.com/qiniu/js-sdk/blob/1.x/src/plupload/plupload.dev.js#L1538

**Comment by iwege** [comment]
iOS 11 在某些情况下也会导致同样的错误。

**Comment by winddies** [comment]
好的，这个我们后面会去测试一下相关问题

**Comment by zackteng** [comment]
@winddies 现在ios9.3上也会有这个问题 目前有修复计划和方案么？

**Comment by iwege** [comment]
@zackteng 初始化的时候不要让progress 赋值为null

**Comment by zackteng** [comment]
@iwege 关键是progress事件不会正常触发 无法获取进度

**Comment by iwege** [comment]
@zackteng https://github.com/qiniu/js-sdk/blob/master/src/upload.js#L46  只要这个地方不为null，貌似就能正常触发...

**Comment by zackteng** [comment]
@iwege 可能你版本比较高吧 我用的IOS9.3测试 触发行为有异常 无法正常获取进度

**Comment by winddies** [comment]
@zackteng  我们初步准备在下周解决这个问题

**Comment by iwege** [comment]
@winddies 请问该问题是否已经解决？

**Comment by lzfee0227** [comment]
[pr#400](https://github.com/qiniu/js-sdk/pull/400)
