### ISSUE TITLE
vue引入新版js-sdk报错，TypeError: o.upload.addEventListener is not a function

### ISSUE THREAD

**Issue by winfs** [qiniu/js-sdk#367]
import * as qiniu from 'qiniu-js'
 ...

getUploadToken().then(res => {
          if (res.data.statusCode == 200) {
            const token = res.data.data.token
            const file = this.file.raw
            const key = this.file.name
            const putExtra = {
              fname: '',
              params: {},
              mimeType: null // 限制上传文件类型
            }
            const config = {
              useCdnDomain: false,
              disableStatisticsReport: false
            }
            const subObject = {
              next: this.next,
              error: this.error,
              complete: this.complete
            }
            const observable = qiniu.upload(file, key, token, putExtra, config)
            observable.subscribe(subObject) // 开始上传
    }
}

**Comment by winddies** [comment]
[参考]（https://github.com/nuysoft/Mock/issues/127）
这个问题应该不是sdk的问题
