### ISSUE TITLE
获取上传速度

### ISSUE THREAD

**Issue by hu-zhi-hang** [qiniu/js-sdk#369]
有没有什么合适的方法在 next 中获取到或者计算出上传速度呢？

**Comment by winddies** [comment]
next里已经给了上传大小，上传进度，上传的总量，你可以自己计算上传速度

**Comment by kklook** [comment]
@winddies  你们那个loaded是什么东西啊，24MB的东西上传1秒钟就显示我传了50%？ 我靠你们写东西能不能靠点谱？

**Comment by winddies** [comment]
第一：loaded代表已上传的大小，readme里写的很清楚
第二: 首先sdk是有断点续传的，假如你之前传了一部分，在一天时间内继续上传，会从断点继续，网速很好的情况下几秒钟传完24m的大小是很正常的一件事，
第三：我们欢迎提意见，但是不要乱喷，就目前进度来说，我们本身也测试了不少，你所说的问题自己先搞清楚

**Comment by kklook** [comment]
@winddies 我今天仔细看了下，发现是国内IP表现是正常的，但国外IP就会发生我说的那种情况
