### ISSUE TITLE
图片显示异常

### ISSUE THREAD

**Issue by karboom** [qiniu/js-sdk#371]
目前使用版本：1.0.24
相关参数：
resize: {
            quality: 85
},
chunk_size: 0

![image](https://user-images.githubusercontent.com/6102230/39986949-d5ebd88e-5795-11e8-9cc9-0e9e7b15b6ba.png)

**Comment by winddies** [comment]
麻烦表述清晰一点？无法判断问题原因

**Comment by karboom** [comment]
在华为和vivo手机上传，有概率发生图片变成左边的样子，右边原图

**Comment by winddies** [comment]
你使用的是哪个版本的sdk?
