### ISSUE TITLE
钉钉浏览器兼容有问题

### ISSUE THREAD

**Issue by GavinZhuLei** [qiniu/js-sdk#372]
使用钉钉浏览器上传图片时报错
![wechatimg15](https://user-images.githubusercontent.com/3376636/40406138-15e791a0-5e92-11e8-9bd4-0e0fb4109c6c.jpeg)
其实图片已经传到七牛镜像了

**Comment by iwege** [comment]
link #362

**Comment by GavinZhuLei** [comment]
@iwege 
自己的解决办法：
采用图片转换成base64上传，可以上传成功（有成功返回的信息），但是仍然没有progress的返回

**Comment by lzfee0227** [comment]
[pr#400](https://github.com/qiniu/js-sdk/pull/400)
