### ISSUE TITLE
升级iOS12 开发者版本后出现http Error，iOS11.x -是正常的

### ISSUE THREAD

**Issue by oikewll** [qiniu/js-sdk#376]
![image](https://user-images.githubusercontent.com/244491/41231782-d526f3f2-6db6-11e8-9b82-5c48ead50b59.png)

![image](https://user-images.githubusercontent.com/244491/41231812-eda98e80-6db6-11e8-963b-62e4f260bbe6.png)

**Comment by winddies** [comment]
使用cdnDomain也是这样吗？这个http error目前无法定位问题

**Comment by pacoyang** [comment]
Same error

**Comment by pacoyang** [comment]
我发现是 iOS 12 beta1 在跨域 post https 时出现无法到达的网络错误，换成 http 时就正常了。iOS 12 beta2 修复了这个错误。

**Comment by oikewll** [comment]
是的beta2就好了。再也不想升级beta

PacoYang <notifications@github.com>于2018年8月25日 周六11:52写道：
