### ISSUE TITLE
startsWith 方法不兼容导致 IE 全系列无法上传成功

### ISSUE THREAD

**Issue by A-Circle-Zhang** [qiniu/js-sdk#379]
![default](https://user-images.githubusercontent.com/11173242/42103227-014db7ca-7bfb-11e8-938d-2363f49cecd4.png)

IE 11 下，最新版本（v2.4.0）的 JS-SDK 上传无法成功，因为 utils.js 中检测 putExtra.params 中变量是否是 x: 开头的自定义变量时用到了 String.startsWith，而这个方法 IE 全系列都没有支持。

![default](https://user-images.githubusercontent.com/11173242/42103327-4a55d88a-7bfb-11e8-860f-e01edd197f62.png)

Cannot upload with the latest version of JS-SDK due to the compatibility of String.prototype.startsWith() in IE

**Comment by winddies** [comment]
可以引用下polyfill来兼容这些语法, 在README里开头就说了
