### ISSUE TITLE
compressImage接口对exif为竖图的图片出错

### ISSUE THREAD

**Issue by reezon** [qiniu/js-sdk#383]
压缩参数：
```
let options = {
        quality: 0.92,
        noCompressIfLarger: true,
        maxWidth: 1400,
        maxHeight: 1400
    }
```
然后选择一张单反里拍摄的竖版图片，上传之后出现压缩错误。

素材图片：
https://img.picbling.cn/538A8674.JPG

压缩错误的结果：
https://img.picbling.cn/b8c9bb9f-f689-48f1-a38b-f8db9556b621.jpeg

将素材图片在ps中保存了一次后，再上传，就正常了，结果见：
https://img.picbling.cn/fb1e27c2-8883-4684-ad3d-e79a236d6981.jpeg

**Comment by lzfee0227** [comment]
好的，感谢，最近时间比较忙，之后会处理这个问题

**Comment by Mr-xue** [comment]
@lzfee0227 你好，问一下这个问题修复了吗？ 我用七牛直传，手机拍照压缩上传也遇到这个问题：1.旋转不正确  2.压缩后图片部分区域出现空白

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-970

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
