### ISSUE TITLE
2.4.0版本如何兼容ie8，引入plupload一样报错

### ISSUE THREAD

**Issue by EagleWolf** [qiniu/js-sdk#384]
引入的qiniu版本是2.4.0，
plupload.full.min.js  ：  3.1.2，

在ie8下
![image](https://user-images.githubusercontent.com/4488399/43831058-7d505ab8-9b35-11e8-90ca-08a9d91337cf.png)

在ie9下
无报错代码，但是点击上传按钮没有弹出选择上传框。

ie10没有问题。

针对qiniu.min.js  2.x的版本有兼容ie8、ie9的嘛？

**Comment by winddies** [comment]
在低版本浏览器需要引入 babel-polyfill 来解决 sdk 里某些语法或者属性浏览器不能识别的问题，README里开头就说了这个问题。。。
