### ISSUE TITLE
qiniu 2.4.0 jsSDK,在ie8, ie9下不支持cors访问

### ISSUE THREAD

**Issue by EagleWolf** [qiniu/js-sdk#385]
直接访问就是下载文件，可以参考以下链接做个兼容

https://github.com/moxiecode/plupload/issues/1267#issuecomment-119556589

https://juejin.im/post/5a7d790b6fb9a0633e51cae0

![image](https://user-images.githubusercontent.com/4488399/43945197-032cdb96-9cb4-11e8-8f91-7cdd0f7c0cff.png)

**Comment by winddies** [comment]
为什么会用sdk在ie8，ie9下发请求？文档里有说过不支持ie9,ie8,只是提供一些接口结合plupload使用

**Comment by puretang** [comment]
只是提供一些接口结合plupload使用

**Comment by puretang** [comment]
只是提供一些接口结合plupload使用， 那么请问v2.4.0怎么和plupload结合使用呢，有没有官方示例，像v1.x版本哪样的
