### ISSUE TITLE
ios 11.4 七牛2.4.0，上传图片直接失败，而且这报错信息我根本无从下手

### ISSUE THREAD

**Issue by zicong-zhang** [qiniu/js-sdk#386]
![img_20180815_115920_ b 2fdb84c](https://user-images.githubusercontent.com/32116218/44131277-76610898-a084-11e8-9124-15a1181d2b1c.jpg)

![](https://static.dingtalk.com/media/lADPBbCc1rOB7RXNC7jND6A_4000_3000.jpg_620x10000q90g.jpg)

**Comment by zicong-zhang** [comment]
从subscribe的error事件的参数中获取到的Error对象，network无报错，但一直处于pending状态

**Comment by tjru** [comment]
我遇到了，IOS版本的UC和百度浏览器用官方JSSDK上传会出现一直卡pending的问题，抓包之后发现，实际接口已经返回，但是SDK报了null is not an Object  (evaluating '' this.progress.total)的错误，并在控制台输出了没有一点用的报错信息！！！

**Comment by tjru** [comment]
[注释掉这行代码](https://github.com/qiniu/js-sdk/blob/7e07e597e59bfd37eab6220ffa44ec15e7cd1bee/src/upload.js#L156)手动编译源码之后解决了这个问题

**Comment by justinyueh** [comment]
在ios 钉钉 里面报错：null is not an Object (evaluating '' this.progress.total)

**Comment by justinyueh** [comment]
抓包看是上传成功了

**Comment by lzfee0227** [comment]
#372

**Comment by lzfee0227** [comment]
[pr#400](https://github.com/qiniu/js-sdk/pull/400)
