### ISSUE TITLE
新版本的2.5sdk 使用方式

### ISSUE THREAD

**Issue by ouaisheinie** [qiniu/js-sdk#392]
初始化都做好了   但是纠结怎么使用  官方文档没有明确说明

**Comment by ouaisheinie** [comment]
uploadImg(imgSource) {
    const uptoken  = this.props.uiStore.imgupload.token;
    const file = imgSource //Blob 对象，上传的文件
    const key = null  // 上传后文件资源名以设置的 key 为主，如果 key 为 null 或者 undefined，则文件资源名会以 hash 值作为资源名。

    let config = {
      useCdnDomain: true,   //表示是否使用 cdn 加速域名，为布尔值，true 表示使用，默认为 false。
      region: qiniu.region.z0     // 根据具体提示修改上传地区,当为 null 或 undefined 时，自动分析上传域名区域
    };

    let putExtra = {
      fname: "",  //文件原文件名
      params: {}, //用来放置自定义变量
      mimeType: null  //用来限制上传文件类型，为 null 时表示不对文件类型限制；限制类型放到数组里： ["image/png", "image/jpeg", "image/gif"]
    };

    let observable = qiniu.upload(file, key, uptoken, putExtra, config);
    observable.subscribe({
      next: (res) => {
      // 主要用来展示进度
        let total = res.total;
        window.Qapp.showLoad({content:'上传图片中！'})
        // console.log("进度：" + parseInt(total.percent) + "% ")
      },
      error: (err) => {
      // 失败报错信息
        console.log(err)
        window.Qapp.hideLoad()
        window.Qapp.showToast({content:'上传错误！'})
      },
      complete: (res) => {
      // 接收成功后返回的信息
        window.Qapp.hideLoad()
        console.log(res.hash)
      }
    })
  }

**Comment by ouaisheinie** [comment]
上面是初始化的函数,但是就不知道你们里面的参数 比如file  要怎么取到
我用filereader处理一下得到？

**Comment by winddies** [comment]
<input type="file" onchange=""/>  onchange方法里可以拿到file...这个是基础知识

**Comment by y284663247** [comment]
怎么限制上传的文件数及上传文件类型，下面代码限制了，但是还是选择到非图片的文件
` mimeType = ['image/png', 'image/jpeg', 'image/gif', 'image/jpg', '!application/json;text/plain'];`

**Comment by winddies** [comment]
不太懂你这里的限制上传的文件数具体是指哪方面？ 是指上传到七牛云上的文件数吗？还是本次上传的最大上传文件数？第一种你空间存储量不够的情况下是上传不成功的，第二种在业务代码里可以自己去控制

**Comment by winddies** [comment]
对于限制类型，sdk里只是限制你这次上传的文件，但是你要想不能选，那就在input里设置accept属性就好了
