### ISSUE TITLE
大文件上传失败,

### ISSUE THREAD

**Issue by wsxc451** [qiniu/js-sdk#399]
{code: 400, message: "xhr request failed, code: 400; response: {"error":"invalid encoded mimeType AAAA"}", reqId: "Gw0AABJ_atnZ4l0V", isRequestError: true}

**Comment by wsxc451** [comment]
小文件上传没问题.大文件上传就出400错误; 用xhr原生写没问题. 貌似loaded!=size,感觉总是少1的样子;

 total:loaded:55510742 
percent:
99.9999981985469
size:55510743

**Comment by winddies** [comment]
这里是因为sdk里目前对 mimeType不能设置为 [],  如果没有限制的话可以设置为 null ， size跟loaded是不对应的， reademe里有说明
