### ISSUE TITLE
上传图片 xhr request failed ，code: 0

### ISSUE THREAD

**Issue by Rem486** [qiniu/js-sdk#401]
上传环境 ios 12.0
app webview 内上传的时候，报错返回，由于查官方文档错误码也没有对应的提示，不知道怎么调试啊

{"code":0,"message":"xhr request failed, code: 0;","reqId":"","isRequestError":true}

同这个问题，请问最后解决方案是什么呢？
[https://github.com/qiniu/js-sdk/issues/352](url)

**Comment by Rem486** [comment]
<img width="375" alt="781c3dc36bc4b00ed6f2ee686348b99b" src="https://user-images.githubusercontent.com/22462424/47784838-d0c53d00-dd41-11e8-91a3-0069be655d0c.png">

使用官方demo嵌入进行上传的时候这样报错了，请问具体是什么问题呢？

**Comment by Rem486** [comment]
@li2go 嵌入app之后是百分百出现的，最后也没有解决。改用上传到服务器再传给七牛了。请问，有什么解决办法吗？

**Comment by winddies** [comment]
可以使用 sdk 2.0版本

**Comment by Rem486** [comment]
@winddies 当时使用的版本是   "qiniu-js": "^2.5.1"

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-971

**Comment by yinminqian** [comment]
请问解决了吗？最近也遇到了这个问题

**Comment by yinxulai** [comment]
> 请问解决了吗？最近也遇到了这个问题

你好，您的版本号是多少

**Comment by yinxulai** [comment]
推荐升级到最新版本，同时指定参数 `debugLogLevel `，显示更详细的调试信息以确定问题的原因。

本 issue 由于长期无法获取更详细的信息，因此关闭。
