### ISSUE TITLE
如何自行编译 qiniu.min.js

### ISSUE THREAD

**Issue by hoythan** [qiniu/js-sdk#408]
项目使用了七牛的sdk，需要修改一些代码进行扩展。
使用的版本是七牛JS-SDK v1.0.6-beta
想咨询一下如何进行打包成  qiniu.min.js ？
使用 grunt production 进行打包出来的内容和官方提供的 qiniu 文件不同，

```
/*global plupload ,mOxie*/
/*global ActiveXObject */
/*exported Qiniu */
```
没有被打包进去

**Comment by winddies** [comment]
npm run build 1.x的版本是用webpack编的，推荐使用2.x版本
