### ISSUE TITLE
自定义变量问题，文档麻烦写完整，最好加个演示，putExtra.params = {“x:name”: 'demo'}

### ISSUE THREAD

**Issue by qinhongqi1234** [qiniu/js-sdk#413]
初次写自定义变量putExtra.params = {name: 'demo'}，测试了半天不行，然后用数组写法，还是不通过，网上也找不到答案，最后去看源码的，发现是对象模式，对象key开头必须是x:，按道理说，这种不合常规的写法，在文档里面，要特别备注，你这整一出，是拿大家时间不当时间啊。

**Comment by forrest-mao** [comment]
感谢提醒，目前已经在 https://developer.qiniu.com/kodo/sdk/1283/javascript#usage，加入了相关描述和示例
![image](https://user-images.githubusercontent.com/4973955/88030428-ca0dd780-cb6d-11ea-928f-0faa9e2ff412.png)
