### ISSUE TITLE
图片压缩，关于maxWidth或者maxHeight

### ISSUE THREAD

**Issue by liugonghe** [qiniu/js-sdk#416]
图片压缩，如果compressImage方法参数option里传了maxWidth或者maxHeight，compress.js里的doScale方法缩放有bug，图片并没有合理如期的完整缩放！

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-973

**Comment by yinxulai** [comment]
能否补充没有如期的细节，例如，图片尺寸对不上？或者发生了变形？出现了雪花？
以方便我们进一步跟踪

**Comment by hojas** [comment]
是按原比例缩小的吗？
