### ISSUE TITLE
token 问题导致的 Cannot read property 'split' of null

### ISSUE THREAD

**Issue by g1f9** [qiniu/js-sdk#417]
## token 问题
![image](https://user-images.githubusercontent.com/32266694/57570797-a367f300-7438-11e9-85bf-2f1df83f1484.png)

不知道出于什么原因，后端传过来的 token，切割解码后，scope 参数为 null，如果这个参数是必须的话，还请麻烦优化下报错提示，不然这种报错挺难受的

**Comment by winddies** [comment]
scope 在 token里是必须设置的， 这里scope 为 null 说明你的 token本身就有问题，[上传策略](https://developer.qiniu.com/kodo/manual/1206/put-policy)

**Comment by g1f9** [comment]
> scope 在 token里是必须设置的， 这里scope 为 null 说明你的 token本身就有问题，[上传策略](https://developer.qiniu.com/kodo/manual/1206/put-policy)

我知道 scope 是必须设置的，就是希望能优化一些报错的提示，能帮助更快定位问题，不然 split null 这种报错比较难定位

**Comment by g1f9** [comment]
而生成 token 的时候传进去 null 的 scope 值又能成功生成 token

**Comment by forrest-mao** [comment]
和 #412 类似

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-972

**Comment by yinxulai** [comment]
已经针对 token 可能存在的问题添加了更多、更友好的错误提示及处理方式，升级到 3.2.0 及以上版本即可
