### ISSUE TITLE
什么时候可以支持Typescript？

### ISSUE THREAD

**Issue by iysf** [qiniu/js-sdk#418]
如题，目前项目源码更改为Typescript了。

假如没有Typescript的SDK的话，有推荐其他的上传方式吗？在不更改源码的情况下~ 

感谢~

**Comment by zhengxsFE** [comment]
自己定义 .d.ts 文件吧，这样后面支持就可以移除了

**Comment by winddies** [comment]
ts 的支持我们已经在处理，应该会在11月左右，目前没有 ts 的支持也不影响在 ts 的项目中的使用的

**Comment by winddies** [comment]
@iysf 你好，新版本3.x已经支持 typescript

**Comment by iysf** [comment]
> @iysf 你好，新版本3.x已经支持 typescript

好的~~~已经在项目内进行更新了，抱歉这么晚才回复，感谢辛苦奉献！
