### ISSUE TITLE
怎么自定义错误信息啊？

### ISSUE THREAD

**Issue by y284663247** [qiniu/js-sdk#420]
```
file type doesn't match with what you specify
```
怎么自定义错误信息啊？现在添加上传类型限制，直接按返回的message进行判断吗？

**Comment by winddies** [comment]
是的

**Comment by y284663247** [comment]
是这个链接吗？
https://developer.qiniu.com/kodo/api/3928/error-responses
没有上传类型限制的错误码

**Comment by winddies** [comment]
这里的 code 都是接口相关的返回，而这里的文件类型其实是 sdk 帮你做了判断，你可以在 input 上就做输入限制，用户选文件的时候就选不了，避免使用这个错误信息
