### ISSUE TITLE
文档有一处错误

### ISSUE THREAD

**Issue by zhengxsFE** [qiniu/js-sdk#421]
[qiniu.compressImage](https://github.com/qiniu/js-sdk#qiniucompressimagefile-blob-options-object--promise-%E4%B8%8A%E4%BC%A0%E5%89%8D%E5%9B%BE%E7%89%87%E5%8E%8B%E7%BC%A9) 方法的参数，maxWidh 应该改成 maxWidth，开始没仔细看，结果直接复制，压缩结果一致不正确

**Comment by winddies** [comment]
ok,,,thank you
