### ISSUE TITLE
ios 9.3.2 使用 compressImage 方法上传的图片，显示的时候，图片没有自动校正

### ISSUE THREAD

**Issue by zhengxsFE** [qiniu/js-sdk#422]
用 compressImage 方法得到的图片，位置没有校正，但是看 代码是有处理的

```javascript
const result = await compressImage(file, {
   noCompressIfLarger: true
})
```

用 imageMogr2 方法，可以将图片旋转成正常的

**Comment by winddies** [comment]
如果发现压缩后得到的图片大小比之前的大，实际上我们是返回原图片的

**Comment by zhengxsFE** [comment]
那可能是这个问题，我试试看，多谢

**Comment by zhengxsFE** [comment]
果然是这个问题，设置为 false 之后就正常了，如果是这样，那 ios 9.3.2 的版本可能是需要特殊处理，不知道其他版本的 ios 是不是也有这个问题，感觉发际线越来越高了，看来是开始保温杯配枸杞的生活了，我还没到 30 啊，哎哎哎
