### ISSUE TITLE
 Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by XPgan** [qiniu/js-sdk#430]
TypeError: Cannot read property 'split' of undefined
    at eval (qiniu.min.js?7291:1)
    at eval (qiniu.min.js?7291:1)
    at e.getUploadUrl (qiniu.min.js?7291:1)
    at t.putFile (qiniu.min.js?7291:1)
    at t.eval [as subscribeAction] (qiniu.min.js?7291:1)
    at t.subscribe (qiniu.min.js?7291:1)
    at VueComponent.updatafile (QrCode.vue?7233:130)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)
    at VueComponent.invoker (vue.esm.js?efeb:2188)
    at invokeWithErrorHandling (vue.esm.js?efeb:1863)

请问这个怎么解决啊

**Comment by winddies** [comment]
这个一般都是传的 token 有问题导致的，确认下 token 是不是没设置 scope，参考[上传策略](https://developer.qiniu.com/kodo/manual/1206/put-policy)

**Comment by XPgan** [comment]
> 这个一般都是传的token有问题导致的，确认下token是不是没设置scope，参考[上传策略](https://developer.qiniu.com/kodo/manual/1206/put-policy)

但是app端和我这边web端用的是同一个后端返回生成token的方法啊

**Comment by XPgan** [comment]
app端是没有问题端

**Comment by winddies** [comment]
如果是web端的话，你可以打断点跟踪下，这个从报错信息看，应该是跟 token 有关系

**Comment by XPgan** [comment]
` return function(t) {
                try {
                    var e = function(t) {
                        var e = t.split(":")
                          , n = e[0]
                          , r = JSON.parse((0,
                        v.urlSafeBase64Decode)(e[2]));
                        return r.ak = n,
                        r.bucket = r.scope.split(":")[0],
                        r
                    }(t);
                    return l(h() + "//api.qiniu.com/v2/query?ak=" + e.ak + "&bucket=" + e.bucket, {
                        method: "GET"
                    })
                } catch (t) {
                    return p.default.reject(t)
                }

 var e = function(t) { 的t的值为
{checkByMD5: false
concurrentRequestLimit: 3
disableStatisticsReport: false
forceDirect: false
region: null
retryCount: 3
uphost: null
useCdnDomain: true}

所以 var e = t.split(":")  才会报错

**Comment by XPgan** [comment]
应该是e.split(":")吗， e的值是七牛的token

**Comment by winddies** [comment]
嗯，e.split(":") 这里的 e 是 token, 看起来是你这里 token 没拿到就开始上传了吧

**Comment by XPgan** [comment]
这个是后端返回给我的token生成错误，第三段字符，解析出来，没有scope 属性，感谢大佬
