### ISSUE TITLE
CDNJS 中找不到七牛SDK库

### ISSUE THREAD

**Issue by scott-leung** [qiniu/js-sdk#431]
希望官方向 CDNJS 提交请求，以便我们直接通过 CDN 引用 SDK。

**Comment by aszx0413** [comment]
七牛是 staticfile 的赞助商，但在 staticfile 没有收录，反而又拍云收录了，想不明白

**Comment by forrest-mao** [comment]
> 希望官方向 CDNJS 提交请求，以便我们直接通过 CDN 引用 SDK。

https://cdnjs.com/libraries/qiniu-js 目前已经加入 cdnjs

**Comment by forrest-mao** [comment]
> 七牛是 staticfile 的赞助商，但在 staticfile 没有收录，反而又拍云收录了，想不明白

http://staticfile.org/ 已经加入 qiniu-js
![image](https://user-images.githubusercontent.com/4973955/88031470-376e3800-cb6f-11ea-9597-ded62c95ab6d.png)
