### ISSUE TITLE
暂停

### ISSUE THREAD

**Issue by q1104133609** [qiniu/js-sdk#442]
2.x如何暂停

**Comment by winddies** [comment]
![image](https://user-images.githubusercontent.com/25814552/82771718-82b9e200-9e6f-11ea-851a-95cdb30d2b27.png)
@q1104133609

**Comment by q1104133609** [comment]
这只是取消吧 我需要暂停某个上传然后 过段时间继续上传呢

**Comment by winddies** [comment]
@q1104133609 作用一样，上传取消/上传暂停

**Comment by winddies** [comment]
你这是自己的业务逻辑，很好实现。。。

**Comment by q1104133609** [comment]
好的我试试 谢谢
