### ISSUE TITLE
file type does't match with what you specify

### ISSUE THREAD

**Issue by zhaolei11** [qiniu/js-sdk#444]
机型：iPhone7
系统： ios13.2.3
环境： 微信
问题： 用input标签拍照后上传图片时报错：file type does't match with what you specify

望解答 十分感谢！

**Comment by winddies** [comment]
应该是你设置了 mimeType ，而上传的文件类型却不匹配你所设置的

**Comment by zhaolei11** [comment]
微信版本太旧
