### ISSUE TITLE
请增加urlSafeBase64Encode的导出。

### ISSUE THREAD

**Issue by oalpha** [qiniu/js-sdk#455]
在index.ts里添加urlSafeBase64Encode的导出
`
export { urlSafeBase64Encode } from './base64'
`
![图片](https://user-images.githubusercontent.com/8610145/85958201-4c1f3c00-b9c6-11ea-8849-59f25515e190.png)

**Comment by nighca** [comment]
@winddies  感觉挺合理的； @oalpha 方便直接提个 PR 吗？
