### ISSUE TITLE
uploadManager.put(uploadBytes, key, upToken); 太糟糕了

### ISSUE THREAD

**Issue by xunkoo** [qiniu/js-sdk#457]
put方法的 upToken 明显和 Auth 耦合了
```
Auth auth = Auth.create(accessKey, secretKey);
String upToken = auth.uploadToken(bucket);

uploadManager.put(uploadBytes, key, **upToken**); 
```
建议改造成用 uploadManager 的构造方法 或者 用Configuration 注入 accessKey, secretKey ，否则把配置写在业务代码里太糟糕了！特别是整合Spring的时候不能优雅的编码太难受了！！

**Comment by winddies** [comment]
> put方法的 upToken 明显和 Auth 耦合了
> 
> ```
> Auth auth = Auth.create(accessKey, secretKey);
> String upToken = auth.uploadToken(bucket);
> 
> uploadManager.put(uploadBytes, key, **upToken**); 
> ```
> 
> 建议改造成用 uploadManager 的构造方法，或者用Configuration 注入 upToken ，否则把配置写在业务层太糟糕了！
不清楚你说的 put方法的 upToken 明显和 Auth 耦合了是啥意思? js-sdk 里并没有暴露 Auth 的概念，还有你说的把配置写在业务层，token 本身是从服务端获取的，前端并不会涉及到构造 token 的东西

**Comment by xunkoo** [comment]
> > put方法的upToken明显和Auth补充了
> > ```
> > Auth auth = Auth.create(accessKey, secretKey);
> > String upToken = auth.uploadToken(bucket);
> > 
> > uploadManager.put(uploadBytes, key, **upToken**); 
> > ```
> > 
> > 
> > 建议改造成用uploadManager的构造方法，或者用Configuration注入upToken，否则把配置写在业务层太糟糕了！
> > 显然你说的put方法的upToken明显和Auth补充了是啥意思？js-sdk里并没有暴露Auth的概念，还有你说的把配置写在业务层，token本身是从服务端获取的，前端并不会涉及到构造token的东西

抱歉！我写错了，我本意是: 把 accessKey 和 secretKey 使用构造或者配置注入
这样的话我们编码的时候就可以使用配置的方法注入UploadManager 的bean了
![image](https://user-images.githubusercontent.com/67527425/86444120-df4bcf00-bd42-11ea-9da3-ef72b5e72921.png)

**Comment by winddies** [comment]
> > > put方法的upToken明显和Auth补充了
> > > ```
> > > Auth auth = Auth.create(accessKey, secretKey);
> > > String upToken = auth.uploadToken(bucket);
> > > 
> > > uploadManager.put(uploadBytes, key, **upToken**); 
> > > ```
> > > 
> > > 
> > > 建议改造成用uploadManager的构造方法，或者用Configuration注入upToken，否则把配置写在业务层太糟糕了！
> > > 显然你说的put方法的upToken明显和Auth补充了是啥意思？js-sdk里并没有暴露Auth的概念，还有你说的把配置写在业务层，token本身是从服务端获取的，前端并不会涉及到构造token的东西
> 
> 抱歉！我写错了，我本意是: 把 accessKey 和 secretKey 使用构造或者配置注入
> 这样的话我们编码的时候就可以使用配置的方法注入UploadManager 的bean了
> ![image](https://user-images.githubusercontent.com/67527425/86444120-df4bcf00-bd42-11ea-9da3-ef72b5e72921.png)
> 
> ` @bean
> @ConfigurationProperties(prefix="xxx.qiniu")
> public QiniuUploadProp uploadProperties(){
> return new QiniuUploadProp();
> }
> 
> ```
> @Bean
> public UploadManager upQiniu(QiniuUploadProp prop){
>     Auth auth = Auth.create(prop.getAccessKey(), prop.getSecretKey());
>     String token = auth.uploadToken(prop.getBucket());
>     return new UploadManager(new Configuration(Region.autoRegion(),token));
> }`
> ```

我大概明白你的意思，你是不想每次都去进行 create Auth ，然后想把这个操作放到装饰器里是吗？不过你这个是 [java-sdk](https://developer.qiniu.com/kodo/sdk/1239/java) 吧，我这里是 js-sdk....,

**Comment by winddies** [comment]
贴个地址 https://github.com/qiniu/java-sdk

**Comment by xunkoo** [comment]
> 贴个地址 https://github.com/qiniu/java-sdk

卧槽！！！我直接搜索地址就进来了反馈了，天呐抱歉
