### ISSUE TITLE
上传不了文件了

### ISSUE THREAD

**Issue by ruikc** [qiniu/js-sdk#458]
`{"error":"json: cannot unmarshal number into Go struct field CompleteMultipart.customVars of type string"}`

上传内容：
`{"parts":[{"etag":"Fl-MRUSwjsfzMJJiJAZw5l7PSVLS","partNumber":1},{"etag":"FiMETvDGGRTPN0gYfif0igrvVC42","partNumber":2},{"etag":"FkM5gEmC8z66OF2GofKFnnTQQAuM","partNumber":3},{"etag":"FiPwLowMTBqrhtHUHmRhnrWadNIX","partNumber":4},{"etag":"Ftw4q8YNTW2G3pGgp2kHwoytSgon","partNumber":5}],"fname":"lgb_V1.0.5.apk","customVars":{"x:ext":"apk","x:size":18412396,"x:name":"lgb_V1_0_5"}}`

**Comment by winddies** [comment]
看起来是你传的 `customVars` 的参数值类型是 `number` 导致的，参数值只能是 `string`

**Comment by ruikc** [comment]
> 看起来是你传的 `customVars` 的参数值类型是 `number` 导致的，参数值只能是 `string`

猜到可能是这的问题，已经处理了
