### ISSUE TITLE
js断电续传，继续上传怎么从原有进度开始

### ISSUE THREAD

**Issue by xushuo** [qiniu/js-sdk#465]
js-SDK   怎么实现上传文件进行时，暂停，然后点继续上传，在原有进度的基础上继续上传。

官网给的 js的DEMO，继续上传时进度是从0开始的。并不是原有上传进度开始。

**Comment by forrest-mao** [comment]
可以参考 http://jssdk-v2.demo.qiniu.io/ 这个 demo，这里的七牛 h5 上传中，其实断点记录是一个分块（4M）为粒度的断点记录，一个分块上传完成后，不会重新上传，不足 4M 的上传会从单个分块开始重新上传

**Comment by xushuo** [comment]
多谢，只能断电从已经完成的分片信息处开始上传

**Comment by forrest-mao** [comment]
> 多谢，只能断电从已经完成的分片信息处开始上传

恩恩 是的，确实只能从已经完成的分片开始断点续传，没有完成的分片只能重头开始上传

**Comment by xushuo** [comment]
ok
