### ISSUE TITLE
处理打 lib 包时，对于 polyfill 的处理

### ISSUE THREAD

**Issue by atzcl** [qiniu/js-sdk#466]
项目库应该显式引入对应 polyfill 版本依赖，而不是像现在，丢给上层开发者处理;

这可能会导致出现这样的问题： qiniu-js lib 打的 polyfill 是基于 core-js 2.x 的，而上层开发者可能使用的是 core-js 3.x，因为 core-js 没有向下兼容，就会导致报 `Cannot find module 'core-js/modules/xxxxx'`

**Comment by winddies** [comment]
@atzcl 你说的显示引入对应 polyfill 版本依赖是指？

**Comment by atzcl** [comment]
@winddies 打错字了，显示 ===> 显式。。。就是在项目库加上 core-js 2.x 的依赖，然后让 npm/yarn 处理依赖版本问题吧

**Comment by winddies** [comment]
> @winddies 打错字了，显示 ===> 显式。。。就是在项目库加上 core-js 2.x 的依赖，然后让 npm/yarn 处理依赖版本问题吧

![image](https://user-images.githubusercontent.com/25814552/91625277-9332a900-e9d8-11ea-9067-453e7152bcbf.png)
已经加了依赖的

**Comment by atzcl** [comment]
这打包出来的产物不对，建议再加上 core-js 2.x 的依赖

举一个例子，可以在线看下 [https://cdn.jsdelivr.net/npm/qiniu-js@3.1.1/lib/index.js](https://cdn.jsdelivr.net/npm/qiniu-js@3.1.1/lib/index.js)，会发现它引入了一个 bind 的 polyfill

```
require("core-js/modules/es6.function.bind");
```

如果上层开发者用的是 core-js 2.x，那这是没问题的，但是如果是用的 3.x，就会异常了

看了下 `@babel/runtime-corejs2`，它的确有显式添加 core-js 2.x 的依赖

https://github.com/babel/babel/blob/ce6a7f1d98f07497160e6c62d0ff2e6f72497fa5/packages/babel-runtime-corejs2/package.json#L16

但是在包管理工具里面，比如 yarn，它会将第三方包引入的相同依赖的不同版本，会放置在该包的 node_modules 中，然后就近查找，所以 `@babel/runtime-corejs2` 加的 core-js 2.x 的依赖只存在于它自身的目录下

![image](https://user-images.githubusercontent.com/28823188/91625830-f9b9c600-e9dc-11ea-9165-356b556fb05d.png)

而开发者是直接使用 `qiniu-js` 的，这就导致在查找依赖的时候，在 qiniu-js 里面找不到 `node_modules/core-js 2.x`，那么就到外层去找，而如果开发者用的是 core-js 3.x，那么找到的就是 core-js 3.x 的依赖，就会导致依赖不对等的异常

**Comment by dickwu** [comment]
同样遇到这个问题了，其实最好是都是用 core-js 3

**Comment by winddies** [comment]
@dickwu @atzcl 有 demo 嘛，麻烦贴一下代码我测试一下，或者给一下用到的哪个包导致了sdk 有 core-js 的冲突问题
