### ISSUE TITLE
next回调函数内没有uploadInfo信息

### ISSUE THREAD

**Issue by zhoufanglu** [qiniu/js-sdk#469]
![I}L{J34%77V Z7_@92B% 41](https://user-images.githubusercontent.com/24451091/93547669-22a7f800-f998-11ea-8403-8c77ed25b861.png)
如图，我想删除，但是需要用到uploadInfo,文档内说next会返回，但是没有.
```
qiniu.deleteUploadedChunks(token: string, key: stting, uploadInfo: object): Promise
删除指定上传任务中已上传完成的片，key 为目标文件名，uploadInfo 可通过 next 的返回获取，token 由服务端生成
```
`"qiniu-js": "^3.1.1",`

**Comment by winddies** [comment]
![image](https://user-images.githubusercontent.com/25814552/93552263-a1099780-f9a2-11ea-8b8d-cfeaa97a90e8.png)
应该是你文件比较小，目前是默认是大于 4M 的文件会自动分片上传

**Comment by zhoufanglu** [comment]
> ![image](https://user-images.githubusercontent.com/25814552/93552263-a1099780-f9a2-11ea-8b8d-cfeaa97a90e8.png)
> 应该是你文件比较小，目前是默认是大于 4M 的文件会自动分片上传

我刚刚试了下，确实是文件小于4M,就没有uploadInfo, 但是我删除api该如何用？ 我发现报404

```js
qiniu.deleteUploadedChunks(
          this.qiniu.token,
          '0.gif',
          {}
      )
```

**Comment by winddies** [comment]
> > ![image](https://user-images.githubusercontent.com/25814552/93552263-a1099780-f9a2-11ea-8b8d-cfeaa97a90e8.png)
> > 应该是你文件比较小，目前是默认是大于 4M 的文件会自动分片上传
> 
> 我刚刚试了下，确实是文件小于4M,就没有uploadInfo, 但是我删除api该如何用？ 我发现报404
> 
> ```js
> qiniu.deleteUploadedChunks(
>           this.qiniu.token,
>           '0.gif',
>           {}
>       )
> ```

你都没有分片上传，如何 `deleteUploadedChunks ` ?

**Comment by zhoufanglu** [comment]
> > > ![image](https://user-images.githubusercontent.com/25814552/93552263-a1099780-f9a2-11ea-8b8d-cfeaa97a90e8.png)
> > > 应该是你文件比较小，目前是默认是大于 4M 的文件会自动分片上传
> > 
> > 
> > 我刚刚试了下，确实是文件小于4M,就没有uploadInfo, 但是我删除api该如何用？ 我发现报404
> > ```js
> > qiniu.deleteUploadedChunks(
> >           this.qiniu.token,
> >           '0.gif',
> >           {}
> >       )
> > ```
> 
> 你都没有分片上传，如何 `deleteUploadedChunks ` ?

好的 谢谢，我有时间再仔细看下。
