### ISSUE TITLE
npm run build 报错 ts+vue

### ISSUE THREAD

**Issue by vxinv** [qiniu/js-sdk#471]
ERROR  Failed to compile with 2 errors                                                                                                                                                                                                      10:06:07 AM

 error  in /Volumes/OD_MAC/App/ts-vue/node_modules/qiniu-js/src/utils.ts

ERROR in /Volumes/OD_MAC/App/ts-vue/node_modules/qiniu-js/src/utils.ts
111:10 Value of type 'ActiveXObject' is not callable. Did you mean to include 'new'?
    109 |   }
    110 | 
  > 111 |   return window.ActiveXObject('Microsoft.XMLHTTP')
        |          ^
    112 | }
    113 | 
    114 | export async function computeMd5(data: Blob): Promise<string> {

 error  in /Volumes/OD_MAC/App/ts-vue/node_modules/qiniu-js/src/utils.ts

ERROR in /Volumes/OD_MAC/App/ts-vue/node_modules/qiniu-js/src/utils.ts
280:56 Property 'mozURL' does not exist on type 'Window & typeof globalThis'.
    278 | 
    279 | export function createObjectURL(file: File) {
  > 280 |   const URL = window.URL || window.webkitURL || window.mozURL
        |                                                        ^
    281 |   return URL.createObjectURL(file)
    282 | }
    283 | 

 ERROR  Build failed with errors.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ts-vue@0.1.0 build: `vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ts-vue@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by forrest-mao** [comment]
我们确认下，内部跟进 issue KS-26

**Comment by yinxulai** [comment]
已经改进，请更新到 3.2.0 及以上版本
