### ISSUE TITLE
vue-cli-service 4.4.4build production 之后 utils.js中 var xhr=createXHR() 没有upload对象

### ISSUE THREAD

**Issue by danamy** [qiniu/js-sdk#473]
如题。
run dev本地开发模式是正常的。

打包部署生产环境后，utils.js中的xhr对象 就不正常了。

开发框架 vue-element-admin , 
github地址：https://github.com/PanJiaChen/vue-element-admin
你们可以试试。
任何版本的qiniu-js都存在此问题

**Comment by danamy** [comment]
生产环境的xhr:
http://picpub.baixuezhihui.com/830221a0536c48c8ad5865e5c7efb6f3.jpg?imageView2/1/w/700/h/700
开发环境：
http://picpub.baixuezhihui.com/b1091203cdf840dd9899e49df75b30cd.jpg?imageView2/1/w/700/h/700

错误就是 upload对象为空

**Comment by danamy** [comment]
你们的用不了，我就自己写了一个xmlhttprequest ，生产环境没这个问题
http://picpub.baixuezhihui.com/4eadfcf2c9a44687b37b8a92dd6e732f.jpg

**Comment by danamy** [comment]
@winddies  我提的这个 是个问题吗，还是跟我用的wabpack打包配置有问题。但是运行dev没问题啊。

**Comment by zhaoyajie413** [comment]
vue-cli-service  production下确实有这个问题   我也遇到了。目前没有什么好办法。

**Comment by yinxulai** [comment]
@danamy
问题有解决吗？
这个项目是否依旧有这个问题：https://github.com/PanJiaChen/vue-element-admin

我希望有一个复现的例子可以帮我去查看这个问题

**Comment by lifeforfun** [comment]
坑，已找到问题所在，是vue-template-admin的mock模块重写了XMLHttpRequest
解决办法应该就是注释掉main.js里这几行
```js
// src/main.js
if (process.env.NODE_ENV === 'production') {
  const { mockXHR } = require('../mock')
  mockXHR()
}

// mock/index.js

// for front mock
// please use it cautiously, it will redefine XMLHttpRequest,
// which will cause many of your third-party libraries to be invalidated(like progress event).
function mockXHR() {
....
}
```

**Comment by yinxulai** [comment]
@lifeforfun 非常感谢，确实是该问题导致的。我将会向相关相关仓库提交 issue，以向他们汇报该问题。
