### ISSUE TITLE
连续两次上传同一张图片 第二次上传无响应

### ISSUE THREAD

**Issue by subdance** [qiniu/js-sdk#474]
### 情况是这样的：
1. A情况：上传x.jpg -> 成功 -> 再上传x.jpg -> 不触发上传事件
2. B情况：上传x.jpg -> 成功 -> 上传y.jpg -> 成功  -> 再上传x.jpg -> 触发上传事件

### 我想了解
1. 请问A情况是异常还是刻意这样设置的呢？
2. 如果我想重复上传同一文件，应该怎样操作呢

**Comment by winddies** [comment]
@subdance 这个是浏览器对同一个文件的选择事件的限制，input type="file" 下，onChange 并不会多次触发
网上有很多关于这个的解决方案，最方便的就是每次选择前都去清除一下 input 的 value

**Comment by subdance** [comment]
@winddies 
好的 十分感谢 我去试试。

**Comment by subdance** [comment]
将`input`的`value`赋值为`null`即可避免出现此现象
