### ISSUE TITLE
qiniu-js 不支持web worker, web worker 里面没有window ，希望添加web worker 支持

### ISSUE THREAD

**Issue by lpdxlong** [qiniu/js-sdk#483]
qiniu-js 不支持web worker, web worker 里面没有window ，希望添加web worker 支持

**Comment by yinxulai** [comment]
建议很棒，我们确实可以剔除一些对 `window` 的依赖以支持 `WebWorker`，也许你可以试试帮我们完成这一点。

**Comment by yinxulai** [comment]
内部跟进：KODO-11678

**Comment by yinxulai** [comment]
暂时无法支持。
