### ISSUE TITLE
关于WEB客户端获取数据问题

### ISSUE THREAD

**Issue by DolphinBoy** [qiniu/js-sdk#49]
用WEB直传的方式上传文件， 如果设置了callbackUrl的话，上传文件成功之后你们只返回了一个"success"的字符串，完全没有返回hash和key，你们这让客户端如何回显图片呢？
我表示很郁闷啊！

**Comment by SunLn** [comment]
http://developer.qiniu.com/docs/v6/api/reference/security/put-policy.html

可以参考 callbackUrl ，设置这个请求的返回为JSON，JSON内容应该由自己的服务器生成。
