### ISSUE TITLE
js-sdk(3.1.2 版本)取消上传的时候，浏览器中会抛出一个错误

### ISSUE THREAD

**Issue by darrell0904** [qiniu/js-sdk#492]
使用 最新版本七牛 js-sdk 上传时，点击取消上传，浏览器会抛出一个错误。

![image](https://user-images.githubusercontent.com/22806990/113971658-c50fc600-986b-11eb-8037-28ccf64da3ef.png)

![image](https://user-images.githubusercontent.com/22806990/113971856-23d53f80-986c-11eb-889c-b37e5134c60b.png)

**Comment by darrell0904** [comment]
我猜应该是这里面的 await 抛出来的错误，没有被 promise catch 到导致的，望回复
![image](https://user-images.githubusercontent.com/22806990/114047733-7d655a80-98bc-11eb-8d78-b52e4eba8f28.png)

**Comment by yinxulai** [comment]
你好，升级到 3.1.4 即可解决
