### ISSUE TITLE
能不能让react-native支持这个库

### ISSUE THREAD

**Issue by ShaoGongBra** [qiniu/js-sdk#513]
react-native没有可用的库

**Comment by yinxulai** [comment]
您好，我们会尽快考虑支持，当有可用版本时会再次通知您

**Comment by ShaoGongBra** [comment]
我们现在通过服务器端转发，由于是上传视频的app，因服务器带宽小，上传就特别慢

**Comment by yinxulai** [comment]
明白了，给个邮件地址，我把我的企业微信退给你，有时间给你支持一下

**Comment by ShaoGongBra** [comment]
908634674@qq.com

**Comment by jaybowong** [comment]
同求react-native版本

大概上线日期有么？ @yinxulai

**Comment by yinxulai** [comment]
暂时没有，最新进度我会尽快在该 `issue` 同步，同时也鼓励大家有兴趣的可以提 `PR` 一起完善这块的内容

**Comment by happy-func** [comment]
只是上传的话，你暂时可以尝试这个hack
---
![image](https://user-images.githubusercontent.com/46747508/122241084-da9d0e00-cef4-11eb-903b-2912445260b5.png)
[摘自七牛社区](https://blog.qiniu.com/archives/5806)

**Comment by yinxulai** [comment]
@happy-func 

这个是七牛直传的接口，不支持断点续传，不过对于各个 SDK 没有覆盖到的运行环境，可以直接使用，应该不属于 Hack，[直传文件接口文档](https://developer.qiniu.com/kodo/1312/upload)

**Comment by yinxulai** [comment]
> @yinxulai 原来如此,我记得我们小程序里面上传也是这么做的,小程序有什么支持断点的官方库吗?

JS-SDK 有计划支持小程序，不过暂时没有排期，有兴趣可以提一个，核心就是改造一下 `request`

**Comment by yinxulai** [comment]
问题本身已有解决方案。
