### ISSUE TITLE
No matching export in "browser-external:querystring" for import "stringify"

### ISSUE THREAD

**Issue by little3201** [qiniu/js-sdk#516]
启动服务报错，node_modules/qiniu-js/esm/api/index.js:48:9: error: No matching export in "browser-external:querystring" for import "stringify"

**Comment by little3201** [comment]
升级内容都不测试吗？

**Comment by yinxulai** [comment]
#517 done
非常感谢，在测试场景中正好有间接依赖命中，导致在多个测试中都没有发现该问题，今后必定之行更加严格的检查！
