### ISSUE TITLE
关于 canvas 绘制图像的方向兼容处理

### ISSUE THREAD

**Issue by yinxulai** [qiniu/js-sdk#522]
### 问题：

1. `JS-SDK` 在处理图像压缩时，使用 `canvas` 来获取图像数据，部分浏览器的 `canvas` 不会自动根据图像的 `Orientation` 信息对图像进行方向 `校正`，这可能导致与用户预期不一致。
    - [问题代码](https://github.com/qiniu/js-sdk/blob/8d26b7cb260f6d5beffdbbdfff17b8a027481183/src/utils/compress.ts#L118)

### 参考讨论： 

- #521 

### 参考资料

- [whatwg#4495](https://github.com/whatwg/html/issues/4495)
- [csswg-drafts#3799](https://github.com/w3c/csswg-drafts/issues/3799)
-  [w3#the-image-orientation](https://www.w3.org/TR/css-images-3/#the-image-orientation)
- [exif-orientation](https://www.impulseadventure.com/photo/exif-orientation.html)

**Comment by nighca** [comment]
补充下可能的做法：

1. 干掉 js-sdk 中当前基于 EXIF 信息来做校正的逻辑

    如果浏览器行为差异足够小的话

2. 根据当前浏览器行为判断是不是做校正

    可能的判断方式见 https://github.com/qiniu/js-sdk/pull/521#discussion_r672545333

3. 干掉 js-sdk 目前提供的图片压缩功能

    如果有靠谱的第三方库可以做这个事情，我们没必要通过 js-sdk 再来提供一份

**Comment by yinxulai** [comment]
由于问题比较严重，所以我倾向先使用 《可能做法》的第一条，移除这个逻辑来使该功能恢复大部分的时候的可用状态
长期来看，客户端图片压缩非七牛的业务，也不在本 SDK 的业务范围，可以有计划的移除改功能，保持 SDK 的简洁。

**Comment by nighca** [comment]
@yinxulai 我没问题，不过建议先验证下

> 浏览器行为差异足够小

这个事情，至少看是不是 evergreen browser 都没有问题

**Comment by yinxulai** [comment]
### 测试情况（WIP）
![canvas-test](https://user-images.githubusercontent.com/22045569/126465333-eb07cf00-9f91-42b0-bb11-112458b02a2d.png)

**Comment by nighca** [comment]
记一下结论：考虑到规范要求默认按 `Orientation` 信息对图片进行旋转后展示 & 主要浏览器的最新版本都已经实现；这里 js-sdk 不再做额外的处理，即，[这里](https://github.com/qiniu/js-sdk/issues/522#issuecomment-883009116) 的第 1 个做法

如果开发者希望兼容老旧浏览器，可以考虑自己实现图像压缩逻辑，或者通过其他第三方库（见 https://github.com/qiniu/js-sdk/issues/522#issuecomment-883009116 ）来做，处理完成后再使用 js-sdk 进行上传
