### ISSUE TITLE
建议增加 unique_name和save_key配置正确性校验

### ISSUE THREAD

**Issue by Feng-Zihao** [qiniu/js-sdk#54]
https://github.com/qiniu/js-sdk/blob/master/src/qiniu.js#L298
按照文档中提到
```
'Key': function(up, file) {
 // 若想在前端对每个文件的key进行个性化处理，可以配置该函数
 // 该配置必须要在 unique_names: false , save_key: false 时才生效

 var key = "";
 // do something with key here
 return key
 }
```

既然配置有冲突，我觉得不应该按照“默认”做法，就应该明显地报错，说配置有冲突。

谢谢。

**Comment by jiaojunjiahanlin** [comment]
// unique_names: true,
        // 默认 false，key为文件名。若开启该选项，SDK会为每个文件自动生成key（文件名）
    // save_key: true,
        // 默认 false。若在服务端生成uptoken的上传策略中指定了 `sava_key`，则开启，SDK在前端将不对key进行任何处理
1,文档里面有关于配置的详细说明。http://developer.qiniu.com/docs/v6/sdk/javascript-sdk.html
2，和你说的一样，如果配置不一样，没有明显的js前端报错提示。这个是我们的sdk当初设计逻辑的问题。如果更新sdk，会将此部分加入优化的。谢谢反馈。
