### ISSUE TITLE
调用addFile 的接口无效

### ISSUE THREAD

**Issue by BenBBear** [qiniu/js-sdk#56]
我没有设置browse_button（设置了无效的值）, 而是通过plupload提供的`addFile` 方法， 来添加文件。  但是发现`addFile`之后 `uploader.files` 仍然为一个空的数组。

请问这是一个bug还是qiniu sdk前端只能通过browse_button来上传呢？

如果想实现addFile 后上传的目的该如何做呢？ 

谢谢啦 🐱

**Comment by BenBBear** [comment]
看了一下qiniu的部分代码感觉不应该， 可能是我用错了， 再调试一下， 一会儿把结果反馈在这里

**Comment by BenBBear** [comment]
貌似plupload的问题。。。。不懂。。。求助。。

**Comment by meilixie** [comment]
browse_button的值表示的是： 触发文件选择对话框的DOM元素，当点击该元素后便后弹出文件选择对话框。该值可以是DOM元素对象本身，也可以是该DOM元素的id
addFile:向上传队列中添加文件，如果成功添加了文件，会触发FilesAdded事件。参数file为要添加的文件,可以是一个原生的文件,或者一个plupload文件对象,或者一个input[type="file"]元素,还可以是一个包括前面那几种东西的数组   
plupload中，文件选择后就会添加文件，然后会触发FilesAdded事件，这个跟browse_button没什么关系browse_button只是获取上传的按钮然后触发事件

**Comment by ErwinCao** [comment]
建议您使用plupload和2.1.1版本。

**Comment by BenBBear** [comment]
谢谢您哈， 太久过去了， 记得当时最后用rest api上传的。。。。。。
