### ISSUE TITLE
没有单独的sdk版本可以下载吗？

### ISSUE THREAD

**Issue by qcjxberin** [qiniu/js-sdk#567]
没有单独的sdk版本可以下载吗？

**Comment by yinxulai** [comment]
如果你是使用 npm 的方式管理依赖，npm 可以看到所有的历史版本 https://www.npmjs.com/package/qiniu-js
如果你是使用 cdn 分发的方式管理依赖，可以在 cdn 的官网上查看所以历史版本 https://cdnjs.com/libraries/qiniu-js
