### ISSUE TITLE
https 网站的上传会被chrome block

### ISSUE THREAD

**Issue by ldnvnbl** [qiniu/js-sdk#57]
chrome 反馈为 "此网页正试图从未经验证的来源加载脚本"
所以建议新增一个 qiniu.ssl.min.js, 将sdk中所有的 http://up.qiniu.com, 改为 https://.....

**Comment by SunLn** [comment]
如果是 https 网站，可以将js里面的 http://up.qiniu.com 替换为 https://up.qbox.me

**Comment by ldnvnbl** [comment]
但你把这点要在文档里写清楚啊, 就因为这个问题花了我一个多小时的时间

**Comment by SunLn** [comment]
sorry. 已经提交pr并合并。#58 。
