### ISSUE TITLE
上传成功，但是接口返回的数据不是正确的json格式

### ISSUE THREAD

**Issue by yinhunfeixue** [qiniu/js-sdk#596]
https://upload.qiniup.com/

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/29660825/183618468-3e726d8d-3865-4957-b8fe-9a03d33954fb.png">

**Comment by yinxulai** [comment]
初步推测是 token 的 putPolicy 中的 returnBody 设置不正确造成的，检查看看
