### ISSUE TITLE
如何用browserify使用七牛js-sdk？

### ISSUE THREAD

**Issue by hujunyi** [qiniu/js-sdk#61]

**Comment by SunLn** [comment]
不好意思，js-sdk 暂未提供 browserify、bower、npm的支持。非常欢迎提PR完善。

**Comment by AndreLion** [comment]
browserify +1

**Comment by longbai** [comment]
npm  已经 提交 https://www.npmjs.com/package/qiniu-js

**Comment by bianjp** [comment]
@longbai 
npm 包中应该只包含用户使用时需要的文件、依赖。

**Comment by longbai** [comment]
收到，我们优化下

**Comment by kxxoling** [comment]
webpack 也能用吗？如果有用 webpack 的 demo 就更好了！

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-951

**Comment by yinxulai** [comment]
该版本已经不再维护，推荐更新到新版，遂关闭。
