### ISSUE TITLE
无法在Safari中上传文件，跨域错误

### ISSUE THREAD

**Issue by enusune** [qiniu/js-sdk#625]
![image](https://user-images.githubusercontent.com/28625375/236407895-225dc55a-8a88-413c-97f6-f0b2bd4eae9a.png)
官方demo可复现 https://js-sdk-demo.qiniu.io
![image](https://user-images.githubusercontent.com/28625375/236408111-bddf91e5-7084-41da-b221-0cbde9892f2d.png)

**Comment by yinxulai** [comment]
昨日服务端异常，已恢复
