### ISSUE TITLE
uptoken安全性问题

### ISSUE THREAD

**Issue by qiukong** [qiniu/js-sdk#63]
您好，包括演示JS在内的uptoken都是暴露的，完全可以用别的方式获取并构造虚假上传凭证。
例如我可以新建一个PHP文件，file_get_contents('http://jssdk.demo.qiniu.io/uptoken');
来伪造本地uptoken，然后在我的环境搭建一个伪授权的上传环境，忽视上传大小限制随意上传。
即便改为直接uptoken处指定，也可以用PHP获取html并正则匹配相关内容。
请问这个问题是否有解决方法？谢谢！

**Comment by SunLn** [comment]
获取到 uptoken 后，用户是可以将其于在其他环境的上传，而绕开js-sdk对文件大小、mimetype等限制。但用户并不能根据获取到的 uptoken 伪造其他 uptoken，因为前端并没有泄密 AK/SK。 

如果你真需要考虑如何限制其他人获取 uptoken，可以考虑在服务端设置 权限检测，eg，未登录状态、判断请求来源Referer 不符合规格时获取token操作返回400等。但web前端跨域上传到七牛，理论上并没有可能限制死其他人获取到uptoken，毕竟它是暴露在网页中的。

除了开始说滴 ，还可以从其他方面考虑：
1、设置token的有效时间，避免设置过长的有效期，从而让其他人获取到token后有足够的时间上传。但token的时效也受到自己业务逻辑限制。
2、其他人获取token上传文件到你的bucket上，在无法下载的情况下并没有攻击性危险，可以通过设置黑白名单来防止他下载。
3、设置bucket 为私有空间，其即便可以上传，但因为无法获取ak/sk，照样无法获取下载url 。
4、ak\sk 一定不能泄密。

以上，希望能有点帮助和解惑。

**Comment by qiukong** [comment]
非常感谢！！
准备采用限制referer和私有空间解决了~

**Comment by SunLn** [comment]
:smile:
