### ISSUE TITLE
uniapp的vue3中如何引入呢？

### ISSUE THREAD

**Issue by BruceAn1978** [qiniu/js-sdk#637]
项目选型为uniapp方式构建跨平台app，在uniapp的vue3环境下如何引用该js库呢？

**Comment by BruceAn1978** [comment]
import后，在真机环境下会报localStorage对象未定义。

**Comment by yinxulai** [comment]
使用 v4 版本可以支持，如果碰到问题欢迎创建新的 issue 来跟踪
