### ISSUE TITLE
max_file_size案例中设置有问题

### ISSUE THREAD

**Issue by AaronWan** [qiniu/js-sdk#64]
在些咱们是引用的plupload的校验
我们应该这样配置：

> @param {Object} [settings.filters={}] Set of file type filters.
> 
> > @param {Array} [settings.filters.mime_types=[]] List of file types to accept, each one defined by title and list of extensions. `e.g. {title : "Image files", extensions : "jpg,jpeg,gif,png"}`. Dispatches `plupload.FILE_EXTENSION_ERROR`
> > @param {String|Number} [settings.filters.max_file_size=0] Maximum file size that the user can pick, in bytes. Optionally supports b, kb, mb, gb, tb suffixes. `e.g. "10mb" or "1gb"`. By default - not set. Dispatches `plupload.FILE_SIZE_ERROR`.
> > @param {Boolean} [settings.filters.prevent_duplicates=false] Do not let duplicates into the queue. Dispatches `plupload.FILE_DUPLICATE_ERROR`.

**Comment by SunLn** [comment]
你是如何设置出现了问题？

你列的配置貌似是官方的建议。

**Comment by AaronWan** [comment]
咱们选项中   max_file_size: '100mb',           //最大文件体积限制
和
@param {String|Number} [settings.filters.max_file_size=0] Maximum file size that the user can pick, in bytes. Optionally supports b, kb, mb, gb, tb suffixes. e.g. "10mb" or "1gb". By default - not set. Dispatches plupload.FILE_SIZE_ERROR.

功能相同不？

**Comment by AaronWan** [comment]
我开始时只是按demo  设置了一下上传文件单个文件大小限制   1mb  貌似不起作用

**Comment by SunLn** [comment]
按理没有区别，本身 js-sdk 只是把这些参数转给 plpuload 而已。这样试一下看是否 ok：
```
filters : {
 max_file_size: '100mb'
}
```

**Comment by AaronWan** [comment]
嗯这样子是可以的，我看你代码中
plupload.extend(option, op, {
            url: 'http://upload.qiniu.com',
            multipart_params: {
                token: ''
            }
        });
但在plupload代码中校验进取的是 filters.max_file_size
@SunLn

**Comment by SunLn** [comment]
应是 plupload 升级导致的。之前可以不在 filters 中设置，直接传 max_file_size 。

**Comment by ErwinCao** [comment]
建议您使用plupload 2.1.1版本。

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
