### ISSUE TITLE
怎么在angularjs框架中使用

### ISSUE THREAD

**Issue by Mint-Zhao-Chiu** [qiniu/js-sdk#65]
angular中怎么使用，我按照例子中的写了，但是没得反应

**Comment by SunLn** [comment]
能提供一些更具体的代码吗？

**Comment by Mint-Zhao-Chiu** [comment]
就是在ng-view里写script没用啊。或者你给我个例子啊。。。

**Comment by SunLn** [comment]
思路是自己封装 directive。 或者在 自己 的 controller 中调用。没有现成的代码。
