### ISSUE TITLE
2.1.5版本plupload导致sdk上传失败

### ISSUE THREAD

**Issue by lichking1201** [qiniu/js-sdk#70]
初步定位:556 的FileUploaded执行两次，第二次无法取到file.size值，导致:594 ‘http://up.qiniu.com/mkfile/' + file.size路径错误

plupload降级为2.1.1版本后，无此错误

**Comment by meilixie** [comment]
开发者你好。当前qiniu sdk 和 plupload最新版本之间存在兼容性问题，我方正在努力解决兼容性问题；在问题得到解决之前，建议您使用plupload和2.1.1版本。

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
