### ISSUE TITLE
支持多文件同时上传吗？

### ISSUE THREAD

**Issue by jinwei233** [qiniu/js-sdk#71]
如果不支持，理论上能支持多文件并行上传吗，如果能，计划支持吗

**Comment by memorysevencat** [comment]
会出么？感觉不会  你看分块上传  都是一个一个的 我还以为会并发呢

**Comment by codedogfish** [comment]
@WeweTom @memorysevencat 这个取决于 Plupload 了，因为底层用的是 [Plupload](http://www.plupload.com/) 。目前看来是支持不了，换底层上传插件，牵涉面比较广。

**Comment by forrest-mao** [comment]
> 会出么？感觉不会 你看分块上传 都是一个一个的 我还以为会并发呢

目前最新的 3.x 版本的 jssdk 可以通过 config.concurrentRequestLimit 的配置上传的并发数，这个并发数是单文件分片上传的并发数。

**Comment by forrest-mao** [comment]
仅七牛内部员工可见：https://jira.qiniu.io/browse/TS-952

**Comment by winddies** [comment]
@forrest-mao 这个问题实际上是业务逻辑问题，比如我们现在 portal 上的上传就是可以同时多个文件上传，写个循环即可

**Comment by forrest-mao** [comment]
> @forrest-mao 这个问题实际上是业务逻辑问题，比如我们现在 portal 上的上传就是可以同时多个文件上传，写个循环即可

恩恩，主要是看是否可以支持多文件并行上传，串行上传其实一直没有什么问题

**Comment by yinxulai** [comment]
长时间未得到有效，且该版本已不在维护，推荐升级到新版。
