### ISSUE TITLE
有没有办法让上传的key就是hash值来避免重复上传？

### ISSUE THREAD

**Issue by chenweiyj** [qiniu/js-sdk#86]
我试了`unique_names: true`，但这个也只是给文件生成一个唯一的文件名，重复的文件还是会生成多份，很占空间。有没有选项和办法让上传的key就是hash值？

我用iOS SDK的时候不设定key是直接设成hash的，但JavaScript没有找到类似方法。

**Comment by SunLn** [comment]
可以试一下，是否 work 

```
save_key : true
```

**Comment by chenweiyj** [comment]
@SunLn 可以了，谢谢

**Comment by SunLn** [comment]
:smile:
