### ISSUE TITLE
为什么一定要跟Plupload绑定呢？这样不能直接从手机摄像头获取图片了

### ISSUE THREAD

**Issue by chenweiyj** [qiniu/js-sdk#88]
有没有提供直接上传文件的接口而不用绑定Plupload？用了Plupload我在手机端就不能拍照上传了。

我上传到自己的服务都是用 [ng-file-upload](https://github.com/danialfarid/ng-file-upload) 的，我能不能用`ng-file-upload`自己上传到七牛呢？

**Comment by JackZhang1988** [comment]
我也有这样的问题，这样设计实在太不灵活了

**Comment by SunLn** [comment]
可以基于社区的其他上传插件比如web-uploader、flow.js、ng-file-upload 等，再封装 qiniu  api 上传文件到七牛 bucket 。

当初基于 plupload 封装是因为其社区成熟，兼容性好，功能强大。 而自主开发这样的插件是需要耗费相当大的精力的。所以就决定基于 plupload 封装了。

**Comment by chenweiyj** [comment]
我用ng-file-upload解决了，直接把上传的url设成七牛的up server就可以了。谢谢
