### ISSUE TITLE
plupload的mime_types属性怎么设置？

### ISSUE THREAD

**Issue by wendylw** [qiniu/js-sdk#97]
是要像plupload这样设置
filters: {
  mime_types : [
    { title : "Image files", extensions : "jpg,gif,png" },
    { title : "Zip files", extensions : "zip" }
  ]
}
还是直接设置呢?
例如：
mime_type:[
    { title : "Image files", extensions : "jpg,gif,png" },
    { title : "Zip files", extensions : "zip" }
]

**Comment by twn39** [comment]
链接：http://plupload.com/docs/Options#wiki-filters.mime_types

**Comment by forrest-mao** [comment]
目前从 2.x 以上的 jssdk 版本已经不依赖 plupload，且最新 SDK 版本已经升级到 3.x 版本，可以尝试使用最新的 3.x jssdk。
3.x 的 SDK 可以通过 putExtra 中的 mimeType 参数设置待上传文件的 mimetype，如果要限制文件格式可以配合上传 token 中的 mimeLimit 策略来做限制，详细文档可以参考 https://developer.qiniu.com/kodo/sdk/1283/javascript
