### ISSUE TITLE
上传文件fileuploaded事件在ie6,7下可能不触发

### ISSUE THREAD

**Issue by longlywork** [qiniu/js-sdk#99]
可能原因是ie6,7无json对象，建议给用户提示

**Comment by codedogfish** [comment]
@longlywork 
已经在 #105 中，通过改写 parseJSON 和 增加 stringifyJSON 方法解决了 IE低版本的兼容问题，目前在 Windows 7 上 IE 9 中将浏览器模式和文档模式设置为 IE 7 通过测试，稍后会进行更全面的测试并合并到 master 分支后发布。

**Comment by codedogfish** [comment]
@longlywork 抱歉那么晚回复，已经在 v1.0.13 中发布
关闭...
